{
  lib,
  buildPythonPackage,
  fetchPypi,
  graphviz,
  pyparsing,
  pytestCheckHook,
  replaceVars,
  setuptools,
  texliveSmall,
}:

buildPythonPackage (finalAttrs: {
  pname = "dot2tex";
  version = "2.11.3";

  src = fetchPypi {
    inherit (finalAttrs) pname version;
    hash = "sha256-KZoq8FruW74CV6VipQapPieSk9XDjyjQirissyM/584=";
  };

  patches = [
    (replaceVars ./path.patch {
      inherit graphviz;
    })
    ./test.patch # https://github.com/kjellmf/dot2tex/issues/5

    # https://github.com/xyz2tex/dot2tex/pull/104 does not merge cleanly
    ./remove-duplicate-script.patch
  ];

  nativeCheckInputs = [
    pytestCheckHook
    (texliveSmall.withPackages (
      ps: with ps; [
        preview
        pstricks
      ]
    ))
  ];

  build-system = [ setuptools ];
  dependencies = [ pyparsing ];
  pyproject = true;

  meta = {
    description = "Convert graphs generated by Graphviz to LaTeX friendly formats";
    homepage = "https://github.com/kjellmf/dot2tex";
    license = lib.licenses.mit;
    mainProgram = "dot2tex";
  };
})
