# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  fetchgit,
  fetchzip,
  linkFarm,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAAgPfAB2dLHqe8Vw--VN8ULPqqYFewfk4tobT8ov";

    path = fetchgit {
      hash = "sha256-CrFA9utsqHc5UE8ue6yqMTlUQCjFDpOMYPK6aB0dRd4=";
      rev = "23359a1039d054b6e46ca97fa8789a755457fbd5";
      url = "https://github.com/webmproject/libwebp.git";
    };
  }
  {
    name = "N-V-__8AAB0eQwD-0MdOEBmz7intriBReIsIDNlukNVoNu6o";

    path = fetchzip {
      hash = "sha256-TkPLWSN5QcPlL9D0kc/yhH0/puE9bFND24aj5NVDKYs=";
      url = "https://github.com/madler/zlib/archive/refs/tags/v1.3.1.tar.gz";
    };
  }
  {
    name = "N-V-__8AAGxifwAAGwXwvsnl_aOXFGLZTeYCu0WBhuEXr96u";

    path = fetchgit {
      hash = "sha256-tNFWIT9ydfozB8dWcmTMuZLCQmQudTFJIkSr0aG7S44=";
      rev = "f8745da6ff1ad1e7bab384bd1f9d742439278e99";
      url = "https://github.com/facebook/zstd.git";
    };
  }
  {
    name = "N-V-__8AAM5leQDoUCIdk0aoRB23XUlXRCDajkBojfoAcK9q";

    path = fetchzip {
      hash = "sha256-k3vR3acwdiPw8rwI/U7QKX//8lWZgDypBA2ARabFJHo=";
      url = "https://gitlab.com/libtiff/libtiff/-/archive/57dd777d7f4ec687e067dc51ec99877e774b57fe/libtiff-57dd777d7f4ec687e067dc51ec99877e774b57fe.tar.gz";
    };
  }
  {
    name = "N-V-__8AAModCAATNPKPcCapFcZFQHw0a8VjUyjAokEkvmW7";

    path = fetchzip {
      hash = "sha256-BiRuPQEKVJYYgfUsglIuxrBoJBFiQ0ygQmAFrVvCz4Q=";
      url = "https://github.com/randy408/libspng/archive/refs/tags/v0.7.4.zip";
    };
  }
  {
    name = "N-V-__8AAPdUlQAUAx3gzEYFfTSNog15JPi1d6S5uDyDt-qA";

    path = fetchzip {
      hash = "sha256-tmeWLJxieV42f9ljSpKJoLER4QOYQLsLFC7jW54YZAk=";
      url = "https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/3.1.2.zip";
    };
  }
  {
    name = "imgz-0.2.0-BqHzkKdnCwCNWVkntlBIrAD-_DByuc4fQQN7xy0pB-D6";

    path = fetchgit {
      hash = "sha256-JuYja284173noSQ4r8FkUuVasw7o8eqpRdrd+p7RYRU=";
      rev = "0ab36f0649772a5dd93d9eab9e7a8a22082a9256";
      url = "https://github.com/shreyassanthu77/imgz.git";
    };
  }
  {
    name = "zlib-1.3.1-ZZQ7lbYMAAB1hTSOKSXAKAgHsfDcyWNH_37ojw5WSpgR";

    path = fetchgit {
      hash = "sha256-Z9TlunK+ISlTPbudB63dpkGeQO+5epGdAI4qfBd9ra0=";
      rev = "61e7df7e996ec5a5f13a653db3c419adb340d6ef";
      url = "https://github.com/allyourcodebase/zlib";
    };
  }
  {
    name = "zstd-1.5.7-KEItkJ8vAAC5_rRlKmLflYQ-eKXbAIQBWZNmmJtS18q0";

    path = fetchgit {
      hash = "sha256-1w+hR2U9t6R4sNvUMynDsYO0sNAan2svjxjUvxT+x6A=";
      rev = "01327d49cbc56dc24c20a167bb0055d7fc23de84";
      url = "https://github.com/allyourcodebase/zstd.git";
    };
  }
]
