{
  atdgen-codec-runtime,
  biniou,
  buildDunePackage,
  yojson,
}:

buildDunePackage {
  inherit (atdgen-codec-runtime) version src;
  pname = "atdgen-runtime";

  propagatedBuildInputs = [
    biniou
    yojson
  ];

  meta = atdgen-codec-runtime.meta // {
    description = "Runtime library for code generated by atdgen";
  };

}
