{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.docuseal;

  env = {
    HOST = cfg.host;
    NODE_ENV = "production";
    PORT = toString (cfg.port);
    RAILS_ENV = "production";
    REDIS_URL = "redis://${cfg.redis.host}:${toString cfg.redis.port}";
    WORKDIR = "/var/lib/docuseal";
  }
  // cfg.extraConfig;
in
{
  options.services.docuseal = {
    enable = lib.mkEnableOption "DocuSeal, open source document signing";
    package = lib.mkPackageOption pkgs "docuseal" { };

    extraConfig = lib.mkOption {
      default = { };

      description = ''
        Extra environment variables to pass to DocuSeal services.

        Refer to <https://www.docuseal.com/docs/configuring-docuseal-via-environment-variables>.
      '';

      type = lib.types.attrs;
    };

    extraEnvFiles = lib.mkOption {
      default = [ ];

      description = ''
        Extra environment files to pass to DocuSeal services. Useful for passing down environmental secrets.
        e.g. DATABASE_URL
      '';

      example = [ "/etc/docuseal/s3config.env" ];
      type = with lib.types; listOf path;
    };

    host = lib.mkOption {
      default = "127.0.0.1";
      description = "DocuSeal host.";
      type = lib.types.str;
    };

    port = lib.mkOption {
      default = 3000;
      description = "DocuSeal port.";
      type = lib.types.port;
    };

    redis = {
      createLocally = lib.mkOption {
        default = true;
        description = "Whether to create a local redis automatically.";
        type = lib.types.bool;
      };

      host = lib.mkOption {
        default = "localhost";

        description = ''
          Redis server address.
        '';

        type = lib.types.str;
      };

      name = lib.mkOption {
        default = "docuseal";

        description = ''
          Name of the redis server. Only used if `createLocally` is set to true.
        '';

        type = lib.types.str;
      };

      port = lib.mkOption {
        default = 6379;
        description = "Port of the redis server.";
        type = lib.types.port;
      };
    };

    secretKeyBaseFile = lib.mkOption {
      default = "/var/lib/docuseal/secrets/secret-key-base";

      description = ''
        Path to file containing the secret key base.
        A new secret key base can be generated by running:

        `openssl rand -hex 64`

        If this file does not exist, it will be created with a new secret key base.
      '';

      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {

    assertions = [
      {
        assertion = cfg.redis.createLocally -> cfg.redis.host == "localhost";
        message = "the redis host must be localhost if services.docuseal.redis.createLocally is set to true";
      }
    ];

    services.redis = lib.optionalAttrs cfg.redis.createLocally {
      servers."${cfg.redis.name}" = {
        enable = true;
        port = cfg.redis.port;
      };
    };

    systemd.services.docuseal = {
      description = "DocuSeal server";
      environment = env;

      serviceConfig = {
        # Capabilities
        CapabilityBoundingSet = "";
        # User and group
        DynamicUser = true;
        EnvironmentFile = [ "docuseal.env" ] ++ cfg.extraEnvFiles;
        ExecStart = "${cfg.package}/bin/rails server --pid=/var/lib/docuseal/docuseal.pids";

        ExecStartPre = pkgs.writeShellScript "docuseal-pre-script" ''
          cat > /var/lib/docuseal/docuseal.env <<EOF
          SECRET_KEY_BASE="$(cat ${cfg.secretKeyBaseFile})"
          EOF
        '';

        LockPersonality = true;
        # Logs directory and mode
        LogsDirectory = "docuseal";
        LogsDirectoryMode = "0750";
        MemoryDenyWriteExecute = false;
        # Security
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateMounts = true;
        PrivateTmp = true;
        PrivateUsers = (cfg.port >= 1024);
        # Proc filesystem
        ProcSubset = "pid";
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectProc = "invisible";
        # Sandboxing
        ProtectSystem = "strict";
        RemoveIPC = true;
        Restart = "always";

        RestrictAddressFamilies = [
          "AF_UNIX"
          "AF_INET"
          "AF_INET6"
          "AF_NETLINK"
        ];

        RestrictNamespaces = true;
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        # Runtime directory and mode
        RuntimeDirectory = "docuseal";
        RuntimeDirectoryMode = "0750";
        # State directory and mode
        StateDirectory = "docuseal";
        StateDirectoryMode = "0750";
        # System Call Filtering
        SystemCallArchitectures = "native";

        # System Call Filtering
        SystemCallFilter = [
          "@system-service"
          "~@privileged"
        ];

        Type = "simple";
        # Access write directories
        UMask = "0027";
        # Working directory
        WorkingDirectory = "/var/lib/docuseal";
      }
      // lib.optionalAttrs (cfg.port < 1024) {
        AmbientCapabilities = [ "CAP_NET_BIND_SERVICE" ];
        CapabilityBoundingSet = [ "CAP_NET_BIND_SERVICE" ];
      };

      wantedBy = [ "multi-user.target" ];
    };
  };

  meta.maintainers = with lib.maintainers; [ stunkymonkey ];
}
