{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib) types;
  cfg = config.services.ocis;
  defaultUser = "ocis";
  defaultGroup = defaultUser;
in
{
  options = {
    services.ocis = {
      enable = lib.mkEnableOption "ownCloud Infinite Scale";

      package = lib.mkOption {
        description = "Which package to use for the ownCloud Infinite Scale instance.";
        relatedPackages = [ "ocis_5-bin" ];
        type = types.package;
      };

      address = lib.mkOption {
        default = "127.0.0.1";
        description = "Web interface address.";
        type = types.str;
      };

      configDir = lib.mkOption {
        default = null;

        description = ''
          Path to directory containing oCIS config file.

          Example config can be generated by `ocis init --config-path fileName --admin-password "adminPass"`.
          Add `--insecure true` if SSL certificates are generated and managed externally (e.g. using oCIS behind reverse proxy).

          Note: This directory must contain at least a {file}`ocis.yaml`. Ensure
          [user](#opt-services.ocis.user) has read/write access to it. In some
          circumstances you may need to add additional oCIS configuration files (e.g.,
          {file}`proxy.yaml`) to this directory.
        '';

        example = "/var/lib/ocis/config";
        type = types.nullOr types.path;
      };

      environment = lib.mkOption {
        default = { };

        description = ''
          Extra config options.

          See [the documentation](https://doc.owncloud.com/ocis/next/deployment/services/services.html) for available options.
          See [notes for environment variables](https://doc.owncloud.com/ocis/next/deployment/services/env-var-note.html) for more information.

          Note that all the attributes here will be copied to /nix/store/ and will be world readable. Options like *_PASSWORD or *_SECRET should be part of     [environmentFile](#opt-services.ocis.environmentFile) instead, and are only provided here for illustrative purpose.

          Configuration here will override those from [environmentFile](#opt-services.ocis.environmentFile) and will have highest precedence, at the cost of security. Do NOT put security sensitive stuff here.
        '';

        example = {
          CS3_ALLOW_INSECURE = "true";
          GATEWAY_STORAGE_USERS_MOUNT_ID = "123";
          GRAPH_APPLICATION_ID = "1234";
          IDM_IDPSVC_PASSWORD = "password";
          IDM_REVASVC_PASSWORD = "password";
          IDM_SVC_PASSWORD = "password";
          IDP_ISS = "https://localhost:9200";
          IDP_TLS = "false";
          OCIS_INSECURE = "false";
          OCIS_INSECURE_BACKENDS = "true";
          OCIS_JWT_SECRET = "super_secret";
          OCIS_LDAP_BIND_PASSWORD = "password";
          OCIS_LOG_LEVEL = "error";
          OCIS_MACHINE_AUTH_API_KEY = "foo";
          OCIS_MOUNT_ID = "123";
          OCIS_SERVICE_ACCOUNT_ID = "foo";
          OCIS_SERVICE_ACCOUNT_SECRET = "foo";
          OCIS_STORAGE_USERS_MOUNT_ID = "123";
          OCIS_SYSTEM_USER_API_KEY = "foo";
          OCIS_SYSTEM_USER_ID = "123";
          OCIS_TRANSFER_SECRET = "foo";
          STORAGE_USERS_MOUNT_ID = "123";
          TLS_INSECURE = "true";
          TLS_SKIP_VERIFY_CLIENT_CERT = "true";
          WEBDAV_ALLOW_INSECURE = "true";
        };

        type = types.attrsOf types.str;
      };

      environmentFile = lib.mkOption {
        default = null;

        description = ''
          An environment file as defined in {manpage}`systemd.exec(5)`.

          Configuration provided in this file will override those from [configDir](#opt-services.ocis.configDir)/ocis.yaml.
        '';

        example = "/run/keys/ocis.env";
        type = types.nullOr types.path;
      };

      group = lib.mkOption {
        default = defaultGroup;

        description = ''
          The group to run oCIS under.
          By default, a group named `${defaultGroup}` will be created.
        '';

        example = "yourGroup";
        type = types.str;
      };

      port = lib.mkOption {
        default = 9200;
        description = "Web interface port.";
        type = types.port;
      };

      stateDir = lib.mkOption {
        default = "/var/lib/ocis";
        description = "ownCloud data directory.";
        type = types.str;
      };

      url = lib.mkOption {
        default = "https://localhost:9200";
        description = "Web interface address.";
        example = "https://some-hostname-or-ip:9200";
        type = types.str;
      };

      user = lib.mkOption {
        default = defaultUser;

        description = ''
          The user to run oCIS as.
          By default, a user named `${defaultUser}` will be created whose home
          directory is [stateDir](#opt-services.ocis.stateDir).
        '';

        example = "yourUser";
        type = types.str;
      };
    };
  };

  config = lib.mkIf cfg.enable {
    services.ocis.package = lib.mkDefault pkgs.ocis_5-bin;

    systemd = {
      services.ocis = {
        description = "ownCloud Infinite Scale Stack";

        environment = {
          OCIS_BASE_DATA_PATH = cfg.stateDir;
          OCIS_CONFIG_DIR = if (cfg.configDir == null) then "${cfg.stateDir}/config" else cfg.configDir;
          OCIS_URL = cfg.url;
          PROXY_HTTP_ADDR = "${cfg.address}:${toString cfg.port}";
        }
        // cfg.environment;

        serviceConfig = {
          EnvironmentFile = lib.optional (cfg.environmentFile != null) cfg.environmentFile;
          ExecStart = "${lib.getExe cfg.package} server";
          Group = cfg.group;
          LockPersonality = true;
          MemoryDenyWriteExecute = true;
          NoNewPrivileges = true;
          PrivateDevices = true;
          PrivateTmp = true;
          ProtectControlGroups = true;
          ProtectHome = true;
          ProtectKernelLogs = true;
          ProtectKernelModules = true;
          ProtectKernelTunables = true;
          ProtectSystem = "strict";
          ReadOnlyPaths = [ cfg.configDir ];
          ReadWritePaths = [ cfg.stateDir ];
          Restart = "always";

          RestrictAddressFamilies = [
            "AF_UNIX"
            "AF_INET"
            "AF_INET6"
            "AF_NETLINK"
          ];

          RestrictNamespaces = true;
          RestrictRealtime = true;
          RestrictSUIDSGID = true;
          SystemCallArchitectures = "native";
          Type = "simple";
          User = cfg.user;
          WorkingDirectory = cfg.stateDir;
        };

        wantedBy = [ "multi-user.target" ];
      };
    };

    users.groups = lib.mkIf (cfg.group == defaultGroup) { ${defaultGroup} = { }; };

    users.users.${defaultUser} = lib.mkIf (cfg.user == defaultUser) {
      createHome = true;
      description = "ownCloud Infinite Scale daemon user";
      group = cfg.group;
      home = cfg.stateDir;
      isSystemUser = true;
    };
  };

  meta.maintainers = with lib.maintainers; [
    bhankas
    ramblurr
  ];
}
