# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  fetchgit,
  fetchzip,
  linkFarm,
}:

linkFarm "zig-packages" [
  {
    name = "fcft-2.0.0-zcx6C5EaAADIEaQzDg5D4UvFFMjSEwDE38vdE9xObeN9";

    path = fetchzip {
      hash = "sha256-qDEtiZNSkzN8jUSnZP/itqh8rMf+lakJy4xMB0I8sxQ=";
      url = "https://git.sr.ht/~novakane/zig-fcft/archive/v2.0.0.tar.gz";
    };
  }
  {
    name = "pixman-0.3.0-LClMnz2VAAAs7QSCGwLimV5VUYx0JFnX5xWU6HwtMuDX";

    path = fetchzip {
      hash = "sha256-8tA4auo5FEI4IPnomV6bkpQHUe302tQtorFQZ1l14NU=";
      url = "https://codeberg.org/ifreund/zig-pixman/archive/v0.3.0.tar.gz";
    };
  }
  {
    name = "wayland-0.3.0-lQa1kjPIAQDmhGYpY-zxiRzQJFHQ2VqhJkQLbKKdt5wl";

    path = fetchzip {
      hash = "sha256-ydEavD9z20wRwn9ZVX56ZI2T5i1tnm3LupVxfa30o84=";
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.3.0.tar.gz";
    };
  }
]
