# This file has been autogenerated with cabal2nix.
# Update via ./update.sh
{
  lib,
  ansi-wl-pprint,
  base,
  base64-bytestring,
  binary,
  bytestring,
  containers,
  directory,
  edit-distance,
  fetchgit,
  filepath,
  ghc-prim,
  haskeline,
  hspec,
  hspec-discover,
  indexed-traversable,
  mkDerivation,
  mtl,
  prettyprinter,
  process,
  raw-strings-qq,
  scientific,
  text,
  utf8-string,
  vector,
}:
mkDerivation {
  pname = "gren";
  version = "0.6.6";

  src = fetchgit {
    url = "https://github.com/gren-lang/compiler.git";
    rev = "03c52374f82036e7a3276a94e345a4aa98738b9b";
    sha256 = "02hin22kyh2zgxn2fklnfa60iw3ppfr3xnv4z7r39vkf6c2q7fhq";
    fetchSubmodules = true;
  };

  description = "The `gren` command line interface";
  doHaddock = false;

  executableHaskellDepends = [
    base
    bytestring
    containers
    directory
    filepath
    haskeline
    mtl
    process
    utf8-string
  ];

  homepage = "https://gren-lang.org";
  isExecutable = true;
  isLibrary = false;
  jailbreak = true;

  libraryHaskellDepends = [
    ansi-wl-pprint
    base
    base64-bytestring
    binary
    bytestring
    containers
    directory
    edit-distance
    filepath
    ghc-prim
    indexed-traversable
    mtl
    prettyprinter
    raw-strings-qq
    scientific
    text
    utf8-string
    vector
  ];

  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
  mainProgram = "gren";

  testHaskellDepends = [
    base
    bytestring
    containers
    hspec
    prettyprinter
    text
    utf8-string
  ];

  testToolDepends = [ hspec-discover ];
}
