{
  buildDunePackage,
  dolmen,
  dolmen_loop,
  farith,
  ppx_deriving,
  zarith,
}:

buildDunePackage {
  inherit (dolmen) src version;
  pname = "dolmen_model";

  propagatedBuildInputs = [
    dolmen
    dolmen_loop
    farith
    ppx_deriving
    zarith
  ];

  meta = dolmen.meta // {
    description = "Dolmen library for verifying models generated by automated theorem provers and SMT solvers";
  };
}
