{
  lib,
  stdenv,
  fetchFromGitHub,
  installShellFiles,
  llvmPackages,
  nix-update-script,
  nixosTests,
  pcsclite,
  pkg-config,
  runCommand,
  rustPlatform,
  versionCheckHook,
}:

rustPlatform.buildRustPackage (finalAttrs: {
  pname = "yb";
  version = "0.4.2";

  src = fetchFromGitHub {
    owner = "douzebis";
    repo = "yb";
    tag = "v${finalAttrs.version}";
    hash = "sha256-gX9s1R/75ipaPJFPTBMR2riIxMmw1KfuURx2Up6ovOM=";
  };

  nativeBuildInputs = [
    pkg-config
    installShellFiles
  ];

  buildInputs = lib.optionals stdenv.isLinux [ pcsclite ];
  cargoHash = "sha256-J91BH0eXuTtGZCSWWLYGM5KHtBjczD1Qu5PxIXAnFRI=";

  postInstall = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
    # Bash completion: patch two clap_complete quirks:
    #   1. Add `compopt -o filenames` so path arguments complete correctly.
    #   2. Replace $2 (bash-tokenized word) with the actual typed text up to
    #      the cursor, so arguments with spaces (e.g. --reader "Yubico YubiKey
    #      OTP+FIDO+CCID 00 00") complete correctly.
    YB_COMPLETE=bash $out/bin/yb > _yb.bash
    substituteInPlace _yb.bash \
      --replace-fail '    ) )' '    ) )
    compopt -o filenames 2>/dev/null' \
      --replace-fail 'words[COMP_CWORD]="$2"' 'local _cur="''${COMP_LINE:0:''${COMP_POINT}}"
        _cur="''${_cur##* }"
        words[COMP_CWORD]="''${_cur}"'
    installShellCompletion --cmd yb \
      --bash _yb.bash \
      --zsh  <(YB_COMPLETE=zsh  $out/bin/yb) \
      --fish <(YB_COMPLETE=fish $out/bin/yb)

    # Man pages (generated by the yb-gen-man helper binary, also in this crate).
    $out/bin/yb-gen-man $out/share/man/man1
  '';

  doInstallCheck = true;

  nativeInstallCheckInputs = [
    versionCheckHook
  ];

  # Build and test only the yb crate (not the yb-piv-harness test harness,
  # which requires a virtual smart card and runs in the NixOS VM test below).
  buildAndTestSubdir = "rust/yb";

  cargoBuildFlags = [
    "-p"
    "yb"
    "--features"
    "self-test"
  ];

  cargoRoot = "rust";

  cargoTestFlags = [
    "-p"
    "yb"
    "--features"
    "self-test"
  ];

  passthru =
    let
      # Fixture files needed by yb_cli_tests at VM runtime. rustPlatform vendors
      # the entire workspace but strips non-Rust files, so the compile-time
      # CARGO_MANIFEST_DIR path for fixtures is gone at VM time. We ship them as
      # a separate store path and inject YB_FIXTURE_DIR in the testScript.
      testFixtures = runCommand "yb-test-fixtures" { } ''
        mkdir -p $out
        cp ${finalAttrs.src}/rust/yb-core/tests/fixtures/with_key.yaml $out/with_key.yaml
        cp ${finalAttrs.src}/rust/yb-core/tests/fixtures/default.yaml  $out/default.yaml
      '';

      # Compile the harness test binaries (--no-run: compiled but not executed
      # here; the testScript in tests.nix invokes them directly).
      ybPivHarnessTests = rustPlatform.buildRustPackage {
        inherit (finalAttrs)
          version
          src
          cargoRoot
          cargoHash
          ;

        pname = "yb-piv-harness-tests";

        nativeBuildInputs = [
          pkg-config
          llvmPackages.libclang
        ];

        buildInputs = lib.optionals stdenv.isLinux [ pcsclite ];

        # Skip the normal build — we only want the test binaries.
        buildPhase = ''
          (cd rust && cargo test --no-run \
            -p yb-piv-harness --features integration-tests \
            --offline --release)
        '';

        doCheck = false;

        installPhase = ''
          mkdir -p $out/bin
          (cd rust && for name in hardware_piv_tests yb_cli_tests; do
            bin=$(find target/release/deps -maxdepth 1 -name "$name-*" ! -name "*.d" -type f)
            if [ -z "$bin" ] || [ ! -f "$bin" ]; then
              echo "ERROR: could not find $name binary" >&2
              exit 1
            fi
            cp "$bin" $out/bin/$name
          done)
        '';

        BINDGEN_EXTRA_CLANG_ARGS = "-I${llvmPackages.libclang.lib}/lib/clang/${lib.versions.major llvmPackages.release_version}/include";
        LIBCLANG_PATH = "${llvmPackages.libclang.lib}/lib";
        buildAndTestSubdir = "rust";
      };
    in
    {
      inherit ybPivHarnessTests testFixtures;
      tests.integration = nixosTests.yb;
      updateScript = nix-update-script { };
    };

  meta = {
    description = "Secure blob storage on a YubiKey";

    longDescription = ''
      Command-line tool for storing encrypted binary blobs on a YubiKey using
      the PIV application. Uses hybrid encryption (ECDH + AES-256-GCM) with
      hardware-backed keys, supports PIN-protected management key setup
      (--protect), glob-pattern blob listing, and shell completions for bash,
      zsh, and fish.
    '';

    homepage = "https://github.com/douzebis/yb";
    changelog = "https://github.com/douzebis/yb/releases/tag/v${finalAttrs.version}";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ douzebis ];
    platforms = lib.platforms.unix;
    mainProgram = "yb";
  };
})
