{
  lib,
  stdenv,
  fetchFromGitHub,
  autoreconfHook,
  glib,
  libcap_ng,
  ncurses,
  nixosTests,
  pkg-config,
  systemdMinimal,
  enableSystemd ? lib.meta.availableOn stdenv.hostPlatform systemdMinimal,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "irqbalance";
  version = "1.9.5";

  src = fetchFromGitHub {
    owner = "Irqbalance";
    repo = "irqbalance";
    tag = "v${finalAttrs.version}";
    hash = "sha256-DSXFJZ0MyI10ZVFcGY0Sx1kye1ALMeG41nmyqbfO8vQ=";
  };

  nativeBuildInputs = [
    autoreconfHook
    pkg-config
  ];

  buildInputs = [
    glib
    ncurses
    libcap_ng
  ]
  ++ (lib.optionals enableSystemd [
    systemdMinimal
  ]);

  configureFlags = lib.optionals enableSystemd [
    "--with-systemd"
    "systemdsystemunitdir=$$out/lib/systemd/system"
  ];

  postInstall = ''
    # Systemd service
    sed -i "/^EnvironmentFile=/d" "$out/lib/systemd/system/irqbalance.service"
    substituteInPlace "$out/lib/systemd/system/irqbalance.service" \
      --replace-fail /usr/sbin/irqbalance "$out/bin/irqbalance --journal" \
      --replace-fail ' $IRQBALANCE_ARGS' ""
  '';

  passthru.tests.nixos = nixosTests.irqbalance;

  meta = {
    description = "Daemon to help balance the cpu load generated by interrupts across all of a systems cpus";
    homepage = "https://github.com/Irqbalance/irqbalance";

    changelog = lib.strings.optionalString (
      !lib.strings.hasInfix "-unstable-" finalAttrs.version
    ) "https://github.com/Irqbalance/irqbalance/releases/tag/v${finalAttrs.version}";

    license = lib.licenses.gpl2Only;
    maintainers = with lib.maintainers; [ moni ];
    platforms = lib.platforms.linux;
    mainProgram = "irqbalance";
  };
})
