# This has been automatically generated by the script
# ./update.sh.  This should not be changed by hand.
{
  lib,
  Glob,
  QuickCheck,
  aeson,
  aeson-pretty,
  ansi-terminal,
  async-pool,
  base,
  bower-json,
  bytestring,
  containers,
  cryptonite,
  dhall,
  directory,
  either,
  extra,
  fetchgit,
  file-embed,
  filepath,
  foldl,
  fsnotify,
  generic-lens,
  hspec,
  hspec-discover,
  hspec-megaparsec,
  http-client,
  http-conduit,
  http-types,
  lens-family-core,
  megaparsec,
  mkDerivation,
  mtl,
  network-uri,
  open-browser,
  optparse-applicative,
  prettyprinter,
  process,
  retry,
  rio,
  rio-orphans,
  safe,
  semver-range,
  stm,
  stringsearch,
  tar,
  template-haskell,
  temporary,
  text,
  time,
  transformers,
  turtle,
  unliftio,
  unordered-containers,
  uri-encode,
  utf8-string,
  versions,
  with-utf8,
  yaml,
  zlib,
}:
mkDerivation {
  pname = "spago-legacy";
  version = "0.21.1";

  src = fetchgit {
    url = "https://github.com/purescript/spago-legacy.git";
    rev = "2790261c28f59940f192c56f3b8245b3ae8b798d";
    sha256 = "18p9cic1y9b2v12np4b5sd82rz5njxh8f1vgqs4gwm6xjccmszmr";
    fetchSubmodules = true;
  };

  executableHaskellDepends = [
    ansi-terminal
    base
    text
    turtle
    with-utf8
  ];

  homepage = "https://github.com/purescript/spago-legacy#readme";
  isExecutable = true;
  isLibrary = true;

  libraryHaskellDepends = [
    aeson
    aeson-pretty
    ansi-terminal
    async-pool
    base
    bower-json
    bytestring
    containers
    cryptonite
    dhall
    directory
    either
    file-embed
    filepath
    foldl
    fsnotify
    generic-lens
    Glob
    http-client
    http-conduit
    http-types
    lens-family-core
    megaparsec
    mtl
    network-uri
    open-browser
    optparse-applicative
    prettyprinter
    process
    retry
    rio
    rio-orphans
    safe
    semver-range
    stm
    stringsearch
    tar
    template-haskell
    temporary
    text
    time
    transformers
    turtle
    unliftio
    unordered-containers
    uri-encode
    utf8-string
    versions
    with-utf8
    yaml
    zlib
  ];

  license = lib.licenses.bsd3;
  mainProgram = "spago";

  testHaskellDepends = [
    base
    containers
    directory
    extra
    hspec
    hspec-megaparsec
    megaparsec
    process
    QuickCheck
    temporary
    text
    turtle
    versions
  ];

  testToolDepends = [ hspec-discover ];
}
