{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.cross-seed;

  inherit (lib)
    mkEnableOption
    mkPackageOption
    mkOption
    types
    ;
  settingsFormat = pkgs.formats.json { };

  generatedConfig =
    pkgs.runCommand "cross-seed-gen-config" { nativeBuildInputs = [ pkgs.cross-seed ]; }
      ''
        export HOME=$(mktemp -d)
        cross-seed gen-config
        mkdir $out
        cp -r $HOME/.cross-seed/config.js $out/
      '';
in
{
  options.services.cross-seed = {
    enable = mkEnableOption "cross-seed";
    package = mkPackageOption pkgs "cross-seed" { };

    configDir = mkOption {
      default = "/var/lib/cross-seed";
      description = "Cross-seed config directory";
      type = types.path;
    };

    group = mkOption {
      default = "cross-seed";
      description = "Group to run cross-seed as.";
      example = "torrents";
      type = types.str;
    };

    settings = mkOption {
      default = { };

      description = ''
        Configuration options for cross-seed.

        Secrets should not be set in this option, as they will be available in
        the Nix store. For secrets, please use settingsFile.

        For more details, see [the cross-seed documentation](https://www.cross-seed.org/docs/basics/options).
      '';

      type = types.submodule {
        options = {
          dataDirs = mkOption {
            default = [ ];

            description = ''
              Paths to be searched for matching data.

              If you use Injection, cross-seed will use the specified linkType
              to create a link to the original file in the linkDirs.

              If linkType is hardlink, these must be on the same volume as the
              data.
            '';

            type = types.listOf types.path;
          };

          linkDirs = mkOption {
            default = [ ];

            description = ''
              List of directories where cross-seed will create links.

              If linkType is hardlink, these must be on the same volume as the data.
            '';

            type = types.listOf types.path;
          };

          outputDir = mkOption {
            default = "${cfg.configDir}/output";
            defaultText = "\${cfg.configDir}/output";
            description = "Directory where cross-seed will place torrent files it finds.";
            type = types.nullOr types.path;
          };

          port = mkOption {
            default = 2468;
            description = "Port the cross-seed daemon listens on.";
            example = 3000;
            type = types.port;
          };

          torrentDir = mkOption {
            default = null;

            description = ''
              Directory containing torrent files, or if you're using a torrent
              client integration and injection - your torrent client's .torrent
              file store/cache.
            '';

            type = types.nullOr types.path;
          };
        };

        freeformType = settingsFormat.type;
      };
    };

    settingsFile = lib.mkOption {
      default = null;

      description = ''
        Path to a JSON file containing settings that will be merged with the
        settings option. This is suitable for storing secrets, as they will not
        be exposed on the Nix store.
      '';

      type = types.nullOr types.path;
    };

    useGenConfigDefaults = mkOption {
      default = false;

      description = ''
        Whether to use the option defaults from the configuration generated by
        {command}`cross-seed gen-config`.

        Those are the settings recommended by the project, and can be inspected
        from their [template file](https://github.com/cross-seed/cross-seed/blob/master/src/config.template.cjs).

        Settings set in {option}`services.cross-seed.settings` and
        {option}`services.cross-seed.settingsFile` will override the ones from
        this option.
      '';

      type = types.bool;
    };

    user = mkOption {
      default = "cross-seed";
      description = "User to run cross-seed as.";
      type = types.str;
    };
  };

  config =
    let
      jsonSettingsFile = settingsFormat.generate "settings.json" cfg.settings;

      genConfigSegment =
        lib.optionalString cfg.useGenConfigDefaults # js
          ''
            const gen_config_js = "${generatedConfig}/config.js";
            Object.assign(loaded_settings, require(gen_config_js));
          '';

      # Since cross-seed uses a javascript config file, we can use node's
      # ability to parse JSON directly to avoid having to do any conversion.
      # This also means we don't need to use any external programs to merge the
      # secrets.
      secretSettingsSegment =
        lib.optionalString (cfg.settingsFile != null) # js
          ''
            const path = require("node:path");
            const secret_settings_json = path.join(process.env.CREDENTIALS_DIRECTORY, "secretSettingsFile");
            Object.assign(loaded_settings, JSON.parse(fs.readFileSync(secret_settings_json, "utf8")));
          '';

      javascriptConfig =
        pkgs.writeText "config.js" # js
          ''
            "use strict";
            const fs = require("fs");
            const settings_json = "${jsonSettingsFile}";
            let loaded_settings = {};
            ${genConfigSegment}
            Object.assign(loaded_settings, JSON.parse(fs.readFileSync(settings_json, "utf8")));
            ${secretSettingsSegment}
            module.exports = loaded_settings;
          '';
    in
    lib.mkIf (cfg.enable) {
      assertions = [
        {
          assertion = !(cfg.settings ? apiKey);

          message = ''
            The API key should be set via the settingsFile option, to avoid
            exposing it on the Nix store.
          '';
        }
      ];

      # It's useful to have the package in the path, to be able to e.g. get the API key.
      environment.systemPackages = [ cfg.package ];

      systemd.services.cross-seed = {
        after = [ "network-online.target" ];
        description = "cross-seed";
        environment.CONFIG_DIR = cfg.configDir;

        preStart = ''
          install -D -m 600 -o '${cfg.user}' -g '${cfg.group}' '${javascriptConfig}' '${cfg.configDir}/config.js'
        '';

        serviceConfig = {
          ExecStart = "${lib.getExe cfg.package} daemon";
          Group = cfg.group;
          LoadCredential = lib.mkIf (cfg.settingsFile != null) "secretSettingsFile:${cfg.settingsFile}";
          ReadOnlyPaths = lib.optional (cfg.settings.torrentDir != null) cfg.settings.torrentDir;
          ReadWritePaths = lib.optional (cfg.settings.outputDir != null) cfg.settings.outputDir;
          SocketBindAllow = cfg.settings.port;
          # Only allow binding to the specified port.
          SocketBindDeny = "any";
          StateDirectory = "cross-seed";
          User = cfg.user;
        };

        unitConfig = {
          # Unfortunately, we can not protect these if we are to hardlink between them, as they need to be on the same volume for hardlinks to work.
          RequiresMountsFor = lib.flatten [
            cfg.settings.dataDirs
            cfg.settings.linkDirs
            (lib.optional (cfg.settings.outputDir != null) cfg.settings.outputDir)
          ];
        };

        wantedBy = [ "multi-user.target" ];
        wants = [ "network-online.target" ];
      };

      systemd.tmpfiles.settings."10-cross-seed" = {
        ${cfg.configDir}.d = {
          inherit (cfg) group user;
          mode = "700";
        };
      }
      // lib.optionalAttrs (cfg.settings.outputDir != null) {
        ${cfg.settings.outputDir}.d = {
          inherit (cfg) group user;
          mode = "750";
        };
      };

      users.groups = lib.mkIf (cfg.group == "cross-seed") {
        cross-seed = { };
      };

      users.users = lib.mkIf (cfg.user == "cross-seed") {
        cross-seed = {
          description = "cross-seed user";
          group = cfg.group;
          home = cfg.configDir;
          isSystemUser = true;
        };
      };
    };
}
