{
  config,
  lib,
  pkgs,
  utils,
  ...
}:
let
  cfg = config.services.qbittorrent;
  inherit (builtins) concatStringsSep isAttrs isString;
  inherit (lib)
    literalExpression
    getExe
    mkEnableOption
    mkOption
    mkPackageOption
    mkIf
    maintainers
    escape
    replaceString
    collect
    mapAttrsRecursive
    optionals
    ;
  inherit (lib.types)
    str
    port
    path
    nullOr
    listOf
    attrsOf
    anything
    submodule
    ;
  inherit (lib.generators) toINI mkKeyValueDefault mkValueStringDefault;
  gendeepINI = toINI {
    mkKeyValue =
      let
        sep = "=";
      in
      k: v:
      if isAttrs v then
        concatStringsSep "\n" (
          collect isString (
            mapAttrsRecursive (
              path: value:
              "${escape [ sep ] (concatStringsSep "\\" ([ k ] ++ path))}${sep}${
                replaceString "\n" "\\n" (mkValueStringDefault { } value)
              }"
            ) v
          )
        )
      else
        mkKeyValueDefault { } sep k v;
  };
  configFile = pkgs.writeText "qBittorrent.conf" (gendeepINI cfg.serverConfig);
in
{
  options.services.qbittorrent = {
    enable = mkEnableOption "qbittorrent, BitTorrent client";
    package = mkPackageOption pkgs "qbittorrent-nox" { };

    extraArgs = mkOption {
      default = [ ];

      description = ''
        Extra arguments passed to qbittorrent. See `qbittorrent -h`, or the [source code](https://github.com/qbittorrent/qBittorrent/blob/master/src/app/cmdoptions.cpp), for the available arguments.
      '';

      example = [
        "--confirm-legal-notice"
      ];

      type = listOf str;
    };

    group = mkOption {
      default = "qbittorrent";
      description = "Group under which qbittorrent runs.";
      type = str;
    };

    openFirewall = mkEnableOption "opening both the webuiPort and torrentPort over TCP in the firewall";

    profileDir = mkOption {
      default = "/var/lib/qBittorrent/";
      description = "the path passed to qbittorrent via --profile.";
      type = path;
    };

    serverConfig = mkOption {
      default = { };

      description = ''
        Free-form settings mapped to the {file}`qBittorrent.conf` file in the profile.
        Refer to [Explanation-of-Options-in-qBittorrent](https://github.com/qbittorrent/qBittorrent/wiki/Explanation-of-Options-in-qBittorrent).
        The Password_PBKDF2 format is oddly unique, you will likely want to use [this tool](https://codeberg.org/feathecutie/qbittorrent_password) to generate the format.
        Alternatively you can run qBittorrent independently first and use its webUI to generate the format.

        Optionally an alternative webUI can be easily set. VueTorrent for example:
        ```nix
        {
          Preferences = {
            WebUI = {
              AlternativeUIEnabled = true;
              RootFolder = "''${pkgs.vuetorrent}/share/vuetorrent";
            };
          };
        }
        ];
        ```
      '';

      example = literalExpression ''
        {
          LegalNotice.Accepted = true;
          Preferences = {
            WebUI = {
              Username = "user";
              Password_PBKDF2 = "generated ByteArray.";
            };
            General.Locale = "en";
          };
        }
      '';

      type = submodule {
        freeformType = attrsOf (attrsOf anything);
      };
    };

    torrentingPort = mkOption {
      default = null;
      description = "the port passed to qbittorrent via `--torrenting-port`";
      type = nullOr port;
    };

    user = mkOption {
      default = "qbittorrent";
      description = "User account under which qbittorrent runs.";
      type = str;
    };

    webuiPort = mkOption {
      default = 8080;
      description = "the port passed to qbittorrent via `--webui-port`";
      type = nullOr port;
    };
  };

  config = mkIf cfg.enable {
    networking.firewall.allowedTCPPorts = mkIf cfg.openFirewall (
      optionals (cfg.webuiPort != null) [ cfg.webuiPort ]
      ++ optionals (cfg.torrentingPort != null) [ cfg.torrentingPort ]
    );

    systemd = {
      services.qbittorrent = {
        after = [
          "local-fs.target"
          "network-online.target"
          "nss-lookup.target"
        ];

        description = "qbittorrent BitTorrent client";
        restartTriggers = optionals (cfg.serverConfig != { }) [ configFile ];

        serviceConfig = {
          CapabilityBoundingSet = "";

          ExecStart = utils.escapeSystemdExecArgs (
            [
              (getExe cfg.package)
              "--profile=${cfg.profileDir}"
            ]
            ++ optionals (cfg.webuiPort != null) [ "--webui-port=${toString cfg.webuiPort}" ]
            ++ optionals (cfg.torrentingPort != null) [ "--torrenting-port=${toString cfg.torrentingPort}" ]
            ++ cfg.extraArgs
          );

          # the config file has to be writable, so we have to do this weird dance
          ExecStartPre = lib.mkIf (cfg.serverConfig != { }) ''
            ${pkgs.coreutils}/bin/install -Dm600 ${configFile} "${cfg.profileDir}/qBittorrent/config/qBittorrent.conf"
          '';

          Group = cfg.group;
          LockPersonality = true;
          MemoryDenyWriteExecute = true;
          NoNewPrivileges = true;
          PrivateDevices = true;
          PrivateNetwork = false;
          # https://github.com/qbittorrent/qBittorrent/pull/6806#discussion_r121478661
          PrivateTmp = false;
          PrivateUsers = true;
          ProcSubset = "pid";
          ProtectClock = true;
          ProtectControlGroups = true;
          ProtectHome = "yes";
          ProtectHostname = true;
          ProtectKernelLogs = true;
          ProtectKernelModules = true;
          ProtectKernelTunables = true;
          ProtectProc = "invisible";
          ProtectSystem = "full";
          RemoveIPC = true;

          RestrictAddressFamilies = [
            "AF_INET"
            "AF_INET6"
            "AF_NETLINK"
          ];

          RestrictNamespaces = true;
          RestrictRealtime = true;
          RestrictSUIDSGID = true;
          SystemCallArchitectures = "native";
          SystemCallFilter = [ "@system-service" ];
          TimeoutStopSec = 1800;
          Type = "simple";
          User = cfg.user;
        };

        wantedBy = [ "multi-user.target" ];
        wants = [ "network-online.target" ];
      };

      tmpfiles.settings = {
        qbittorrent = {
          "${cfg.profileDir}/qBittorrent/"."d" = {
            inherit (cfg) user group;
            mode = "755";
          };

          "${cfg.profileDir}/qBittorrent/config/"."d" = {
            inherit (cfg) user group;
            mode = "755";
          };
        };
      };
    };

    users = {
      groups = mkIf (cfg.group == "qbittorrent") { qbittorrent = { }; };

      users = mkIf (cfg.user == "qbittorrent") {
        qbittorrent = {
          inherit (cfg) group;
          isSystemUser = true;
        };
      };
    };
  };

  meta.maintainers = with maintainers; [
    fsnkty
    undefined-landmark
  ];
}
