{
  config,
  lib,
  pkgs,
  options,
  ...
}:

let
  cfg = config.services.prometheus.exporters.nginxlog;
  inherit (lib) mkOption types;
in
{
  extraOpts = {
    metricsEndpoint = mkOption {
      default = "/metrics";

      description = ''
        Path under which to expose metrics.
      '';

      type = types.str;
    };

    settings = mkOption {
      default = { };

      description = ''
        All settings of nginxlog expressed as an Nix attrset.

        Check the official documentation for the corresponding YAML
        settings that can all be used here: <https://github.com/martin-helmich/prometheus-nginxlog-exporter>

        The `listen` object is already generated by `port`, `listenAddress` and `metricsEndpoint` and
        will be merged with the value of `settings` before writing it as JSON.
      '';

      type = types.submodule {
        options = {
          consul = mkOption {
            default = null;

            description = ''
              Consul integration options. For more information see the [example config](https://github.com/martin-helmich/prometheus-nginxlog-exporter#configuration-file).

              This is disabled by default.
            '';

            type = types.nullOr (types.attrsOf types.anything);
          };

          namespaces = mkOption {
            default = [ ];

            description = ''
              Namespaces to collect the metrics for. For more information see the [example config](https://github.com/martin-helmich/prometheus-nginxlog-exporter#configuration-file).
            '';

            type = types.listOf (types.attrsOf types.anything);
          };
        };
      };
    };
  };

  port = 9117;

  serviceOpts =
    let
      listenConfig = {
        listen = {
          address = cfg.listenAddress;
          metrics_endpoint = cfg.metricsEndpoint;
          port = cfg.port;
        };
      };
      completeConfig = pkgs.writeText "nginxlog-exporter.yaml" (
        builtins.toJSON (lib.recursiveUpdate listenConfig cfg.settings)
      );
    in
    {
      serviceConfig = {
        ExecStart = ''
          ${pkgs.prometheus-nginxlog-exporter}/bin/prometheus-nginxlog-exporter -config-file ${completeConfig}
        '';

        ProtectSystem = "full";
        Restart = "always";
      };
    };
}
