{
  config,
  lib,
  pkgs,
  options,
  ...
}:

with lib;

let
  cfg = config.services.caddy;

  certs = config.security.acme.certs;
  virtualHosts = attrValues cfg.virtualHosts;
  acmeEnabledVhosts = filter (hostOpts: hostOpts.useACMEHost != null) virtualHosts;
  vhostCertNames = unique (map (hostOpts: hostOpts.useACMEHost) acmeEnabledVhosts);

  mkVHostConf =
    hostOpts:
    let
      sslCertDir = certs.${hostOpts.useACMEHost}.directory;
    in
    ''
      ${hostOpts.hostName} ${concatStringsSep " " hostOpts.serverAliases} {
        ${optionalString (
          hostOpts.listenAddresses != [ ]
        ) "bind ${concatStringsSep " " hostOpts.listenAddresses}"}
        ${optionalString (
          hostOpts.useACMEHost != null
        ) "tls ${sslCertDir}/cert.pem ${sslCertDir}/key.pem"}
        ${optionalString (hostOpts.logFormat != null) ''
          log {
            ${hostOpts.logFormat}
          }
        ''}

        ${hostOpts.extraConfig}
      }
    '';

  settingsFormat = pkgs.formats.json { };

  configFile =
    if cfg.settings != { } then
      settingsFormat.generate "caddy.json" cfg.settings
    else
      let
        Caddyfile = pkgs.writeTextDir "Caddyfile" ''
          {
            ${cfg.globalConfig}
          }
          ${cfg.extraConfig}
          ${concatMapStringsSep "\n" mkVHostConf virtualHosts}
        '';

        Caddyfile-formatted = pkgs.runCommand "Caddyfile-formatted" { } ''
          mkdir -p $out
          cp --no-preserve=mode ${Caddyfile}/Caddyfile $out/Caddyfile
          ${lib.getExe cfg.package} fmt --overwrite $out/Caddyfile
        '';
      in
      "${
        if pkgs.stdenv.buildPlatform == pkgs.stdenv.hostPlatform then Caddyfile-formatted else Caddyfile
      }/Caddyfile";

  etcConfigFile = "caddy/caddy_config";

  configPath = "/etc/${etcConfigFile}";

  mkCertOwnershipAssertion = import ../../../security/acme/mk-cert-ownership-assertion.nix lib;
in
{
  imports = [
    (mkRemovedOptionModule [
      "services"
      "caddy"
      "agree"
    ] "this option is no longer necessary for Caddy 2")
    (mkRenamedOptionModule [ "services" "caddy" "ca" ] [ "services" "caddy" "acmeCA" ])
    (mkRenamedOptionModule [ "services" "caddy" "config" ] [ "services" "caddy" "extraConfig" ])
  ];

  # interface
  options.services.caddy = {
    enable = mkEnableOption "Caddy web server";
    package = mkPackageOption pkgs "caddy" { };

    acmeCA = mkOption {
      default = null;

      description = ''
        ::: {.note}
        Sets the [`acme_ca` option](https://caddyserver.com/docs/caddyfile/options#acme-ca)
        in the global options block of the resulting Caddyfile.
        :::

        The URL to the ACME CA's directory. It is strongly recommended to set
        this to `https://acme-staging-v02.api.letsencrypt.org/directory` for
        Let's Encrypt's [staging endpoint](https://letsencrypt.org/docs/staging-environment/)
        while testing or in development.

        Value `null` should be prefered for production setups,
        as it omits the `acme_ca` option to enable
        [automatic issuer fallback](https://caddyserver.com/docs/automatic-https#issuer-fallback).
      '';

      example = "https://acme-v02.api.letsencrypt.org/directory";
      type = with types; nullOr str;
    };

    adapter = mkOption {
      default =
        if ((cfg.configFile != configFile) || (baseNameOf cfg.configFile) == "Caddyfile") then
          "caddyfile"
        else
          null;

      defaultText = literalExpression ''
        if ((cfg.configFile != configFile) || (baseNameOf cfg.configFile) == "Caddyfile") then "caddyfile" else null
      '';

      description = ''
        Name of the config adapter to use.
        See <https://caddyserver.com/docs/config-adapters>
        for the full list.

        If `null` is specified, the `--adapter` argument is omitted when
        starting or restarting Caddy. Notably, this allows specification of a
        configuration file in Caddy's native JSON format, as long as the
        filename does not start with `Caddyfile` (in which case the `caddyfile`
        adapter is implicitly enabled). See
        <https://caddyserver.com/docs/command-line#caddy-run> for details.

        ::: {.note}
        Any value other than `null` or `caddyfile` is only valid when providing
        your own `configFile`.
        :::
      '';

      example = literalExpression "nginx";
      type = with types; nullOr str;
    };

    configFile = mkOption {
      default = configFile;
      defaultText = "A Caddyfile automatically generated by values from services.caddy.*";

      description = ''
        Override the configuration file used by Caddy. By default,
        NixOS generates one automatically.

        The configuration file is exposed at {file}`${configPath}`.
      '';

      example = literalExpression ''
        pkgs.writeText "Caddyfile" '''
          example.com

          root * /var/www/wordpress
          php_fastcgi unix//run/php/php-version-fpm.sock
          file_server
        ''';
      '';

      type = types.path;
    };

    dataDir = mkOption {
      default = "/var/lib/caddy";

      description = ''
        The data directory for caddy.

        ::: {.note}
        If left as the default value this directory will automatically be created
        before the Caddy server starts, otherwise you are responsible for ensuring
        the directory exists with appropriate ownership and permissions.

        Caddy v2 replaced `CADDYPATH` with XDG directories.
        See <https://caddyserver.com/docs/conventions#file-locations>.
        :::
      '';

      type = types.path;
    };

    email = mkOption {
      default = null;

      description = ''
        Your email address. Mainly used when creating an ACME account with your
        CA, and is highly recommended in case there are problems with your
        certificates.
      '';

      type = with types; nullOr str;
    };

    enableReload = mkOption {
      default = true;

      description = ''
        Reload Caddy instead of restarting it when configuration file changes.

        Note that enabling this option requires the [admin API](https://caddyserver.com/docs/caddyfile/options#admin)
        to not be turned off.

        If you enable this option, consider setting [`grace_period`](https://caddyserver.com/docs/caddyfile/options#grace-period)
        to a non-infinite value in {option}`services.caddy.globalConfig`
        to prevent Caddy waiting for active connections to finish,
        which could delay the reload essentially indefinitely.
      '';

      type = types.bool;
    };

    environmentFile = mkOption {
      default = null;

      description = ''
        Environment file as defined in {manpage}`systemd.exec(5)`.

        You can use environment variables to pass secrets to the service without adding
        them to the world-redable nix store.

        ```
        # in configuration.nix
        services.caddy.environmentFile = "/run/secrets/caddy.env";
        services.caddy.globalConfig = '''
          {
            acme_ca https://acme.zerossl.com/v2/DV90
            acme_eab {
              key_id {$EAB_KEY_ID}
              mac_key {$EAB_MAC_KEY}
            }
          }
        ''';
        ```

        ```
        # in /run/secrets/caddy.env
        EAB_KEY_ID=secret
        EAB_MAC_KEY=secret
        ```

        Find more examples
        [here](https://caddyserver.com/docs/caddyfile/concepts#environment-variables)
      '';

      example = "/run/secrets/caddy.env";
      type = with types; nullOr path;
    };

    extraConfig = mkOption {
      default = "";

      description = ''
        Additional lines of configuration appended to the automatically
        generated `Caddyfile`.
      '';

      example = ''
        example.com {
          encode gzip
          log
          root /srv/http
        }
      '';

      type = types.lines;
    };

    globalConfig = mkOption {
      default = "";

      description = ''
        Additional lines of configuration appended to the global config section
        of the `Caddyfile`.

        Refer to <https://caddyserver.com/docs/caddyfile/options#global-options>
        for details on supported values.
      '';

      example = ''
        debug
        servers {
          protocol {
            experimental_http3
          }
        }
      '';

      type = types.lines;
    };

    group = mkOption {
      default = "caddy";

      description = ''
        Group under which caddy runs.

        ::: {.note}
        If left as the default value this group will automatically be created
        on system activation, otherwise you are responsible for
        ensuring the group exists before the Caddy service starts.
        :::
      '';

      type = types.str;
    };

    httpPort = mkOption {
      default = 80;

      description = ''
        The default port to listen on for HTTP traffic.
      '';

      type = with types; nullOr port;
    };

    httpsPort = mkOption {
      default = 443;

      description = ''
        The default port to listen on for HTTPS traffic.
        Will also be used for HTTP/3.
      '';

      type = with types; nullOr port;
    };

    logDir = mkOption {
      default = "/var/log/caddy";

      description = ''
        Directory for storing Caddy access logs.

        ::: {.note}
        If left as the default value this directory will automatically be created
        before the Caddy server starts, otherwise the sysadmin is responsible for
        ensuring the directory exists with appropriate ownership and permissions.
        :::
      '';

      type = types.path;
    };

    logFormat = mkOption {
      default = ''
        level ERROR
      '';

      description = ''
        Configuration for the default logger. See
        <https://caddyserver.com/docs/caddyfile/options#log>
        for details.
      '';

      example = literalExpression ''
        mkForce "level INFO";
      '';

      type = types.lines;
    };

    openFirewall = mkOption {
      default = false;

      description = ''
        Whether to enable opening the specified http(s) ports in the firewall.
        Any port set to `null` will not be opened.

        ::: {.note}
        If you use other ports for your virtual hosts, you need to open them manually.
        :::
      '';

      example = true;
      type = types.bool;
    };

    resume = mkOption {
      default = false;

      description = ''
        Use saved config, if any (and prefer over any specified configuration passed with `--config`).
      '';

      type = types.bool;
    };

    settings = mkOption {
      default = { };

      description = ''
        Structured configuration for Caddy to generate a Caddy JSON configuration file.
        See <https://caddyserver.com/docs/json/> for available options.

        ::: {.warning}
        Using a [Caddyfile](https://caddyserver.com/docs/caddyfile) instead of a JSON config is highly recommended by upstream.
        There are only very few exception to this.

        Please use a Caddyfile via {option}`services.caddy.configFile`, {option}`services.caddy.virtualHosts` or
        {option}`services.caddy.extraConfig` with {option}`services.caddy.globalConfig` instead.
        :::

        ::: {.note}
        Takes presence over most `services.caddy.*` options, such as {option}`services.caddy.configFile` and {option}`services.caddy.virtualHosts`, if specified.
        :::
      '';

      type = settingsFormat.type;
    };

    user = mkOption {
      default = "caddy";

      description = ''
        User account under which caddy runs.

        ::: {.note}
        If left as the default value this user will automatically be created
        on system activation, otherwise you are responsible for
        ensuring the user exists before the Caddy service starts.
        :::
      '';

      type = types.str;
    };

    virtualHosts = mkOption {
      default = { };

      description = ''
        Declarative specification of virtual hosts served by Caddy.
      '';

      example = literalExpression ''
        {
          "hydra.example.com" = {
            serverAliases = [ "www.hydra.example.com" ];
            extraConfig = '''
              encode gzip
              root * /srv/http
            ''';
          };
        };
      '';

      type = with types; attrsOf (submodule (import ./vhost-options.nix { inherit cfg; }));
    };
  };

  # implementation
  config = mkIf cfg.enable {

    assertions = [
      {
        assertion = cfg.configFile == configFile -> cfg.adapter == "caddyfile" || cfg.adapter == null;
        message = "To specify an adapter other than 'caddyfile' please provide your own configuration via `services.caddy.configFile`";
      }
    ]
    ++ map (
      name:
      mkCertOwnershipAssertion {
        cert = certs.${name};
        groups = config.users.groups;
        services = [ config.systemd.services.caddy ];
      }
    ) vhostCertNames;

    # https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
    boot.kernel.sysctl."net.core.rmem_max" = mkDefault 2500000;
    boot.kernel.sysctl."net.core.wmem_max" = mkDefault 2500000;
    environment.etc.${etcConfigFile}.source = cfg.configFile;

    networking.firewall = mkIf cfg.openFirewall {
      allowedTCPPorts = filter (port: port != null) [
        cfg.httpPort
        cfg.httpsPort
      ];

      allowedUDPPorts = optional (cfg.httpsPort != null) cfg.httpsPort;
    };

    security.acme.certs =
      let
        certCfg = map (
          certName:
          nameValuePair certName {
            group = mkDefault cfg.group;
            reloadServices = [ "caddy.service" ];
          }
        ) vhostCertNames;
      in
      listToAttrs certCfg;

    services.caddy.globalConfig = ''
      ${optionalString (cfg.email != null) "email ${cfg.email}"}
      ${optionalString (cfg.acmeCA != null) "acme_ca ${cfg.acmeCA}"}
      ${optionalString (
        !elem cfg.httpPort [
          null
          options.services.caddy.httpPort.default
        ]
      ) "http_port ${toString cfg.httpPort}"}
      ${optionalString (
        !elem cfg.httpsPort [
          null
          options.services.caddy.httpsPort.default
        ]
      ) "https_port ${toString cfg.httpsPort}"}
      log {
        ${cfg.logFormat}
      }
    '';

    systemd.packages = [ cfg.package ];

    systemd.services.caddy = {
      after = map (certName: "acme-${certName}.service") vhostCertNames;
      reloadTriggers = optional cfg.enableReload cfg.configFile;
      restartTriggers = optional (!cfg.enableReload) cfg.configFile;

      serviceConfig =
        let
          runOptions = "--config ${configPath} ${
            optionalString (cfg.adapter != null) "--adapter ${cfg.adapter}"
          }";
        in
        {
          EnvironmentFile = optional (cfg.environmentFile != null) cfg.environmentFile;

          # Validating the configuration before applying it ensures we’ll get a proper error that will be reported when switching to the configuration
          ExecReload = [
            ""
          ]
          ++ lib.optional cfg.enableReload "${lib.getExe cfg.package} reload ${runOptions} --force";

          # Override the `ExecStart` line from upstream's systemd unit file by our own:
          # https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=
          # If the empty string is assigned to this option, the list of commands to start is reset, prior assignments of this option will have no effect.
          ExecStart = [
            ""
            "${lib.getExe cfg.package} run ${runOptions} ${optionalString cfg.resume "--resume"}"
          ];

          Group = cfg.group;
          LogsDirectory = mkIf (cfg.logDir == "/var/log/caddy") [ "caddy" ];
          # TODO: attempt to upstream these options
          NoNewPrivileges = true;
          PrivateDevices = true;
          ProtectHome = true;
          ReadWritePaths = [ cfg.dataDir ];
          Restart = "on-failure";
          RestartPreventExitStatus = 1;
          RestartSec = "5s";
          StateDirectory = mkIf (cfg.dataDir == "/var/lib/caddy") [ "caddy" ];
          User = cfg.user;
        };

      startLimitBurst = 10;
      startLimitIntervalSec = 14400;
      wantedBy = [ "multi-user.target" ];
      wants = map (certName: "acme-${certName}.service") vhostCertNames;
    };

    users.groups = optionalAttrs (cfg.group == "caddy") {
      caddy.gid = config.ids.gids.caddy;
    };

    users.users = optionalAttrs (cfg.user == "caddy") {
      caddy = {
        group = cfg.group;
        home = cfg.dataDir;
        uid = config.ids.uids.caddy;
      };
    };
  };
}
