{
  lib,
  stdenv,
  fetchFromGitHub,
  mpv,
  qt6,
  # "Free" key generated by pasqui23
  withAPIKey ? "AIzaSyBQvZXseEVvgu5Ega_DI-AIJ55v0OsHmVY",
}:

stdenv.mkDerivation rec {
  pname = "minitube";
  version = "4.0";

  src = fetchFromGitHub {
    owner = "flaviotordini";
    repo = "minitube";
    tag = version;
    hash = "sha256-JAxdPiiPDpmhJBiNtlaMbdcC/YEGJyc9mP3kBvee/74=";
    fetchSubmodules = true;
  };

  # https://github.com/NixOS/nixpkgs/issues/214765
  postPatch = ''
    substituteInPlace locale/locale.pri \
      --replace-fail '$$[QT_INSTALL_BINS]/lrelease' '${lib.getDev qt6.qttools}/bin/lrelease'
  '';

  nativeBuildInputs = [
    qt6.qmake
    qt6.qttools
    qt6.wrapQtAppsHook
  ];

  buildInputs = [
    qt6.qtbase
    qt6.qtdeclarative
    mpv
  ];

  qmakeFlags = [ "DEFINES+=APP_GOOGLE_API_KEY=${withAPIKey}" ];

  meta = {
    description = "Stand-alone YouTube video player";

    longDescription = ''
      Watch YouTube videos in a new way: you type a keyword, Minitube gives
      you an endless video stream. Minitube is not about cloning the YouTube
      website, it aims to create a new TV-like experience.
    '';

    homepage = "https://flavio.tordini.org/minitube";
    license = lib.licenses.gpl3Plus;
    maintainers = [ ];
    platforms = lib.platforms.linux;
    mainProgram = "minitube";
  };
}
