{
  lib,
  stdenv,
  bashNonInteractive,
  fetchgit,
  gradle_8,
  jdk_headless,
  jre_minimal,
  makeWrapper,
}:
let
  # "Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0."
  gradle = gradle_8;
  jre = jre_minimal.override {
    modules = [
      "java.base"
      "java.compiler"
      "java.logging"
      "java.naming"
      "java.security.jgss"
      "java.sql"
      "jdk.unsupported"
    ];
  };
in
stdenv.mkDerivation (finalAttrs: {
  pname = "apksigner";
  # Major version is derived from the API version of the corresponding Android release.
  # Patch version is derived from the release number.
  # For example, Android 15 had releases starting at r24 -> r30 is patch 6.
  version = "35.0.6";

  src = fetchgit {
    url = "https://android.googlesource.com/platform/tools/apksig";
    tag = "android-15.0.0_r30";
    hash = "sha256-f/PggxvBv8nYUyL9Ukd4YVpunpRWbLL5UYsYhsiDWRE=";
    # use pname here because the final jar uses this as the filename
    name = "apksigner";
  };

  nativeBuildInputs = [
    gradle
    makeWrapper
  ];

  buildInputs = [
    # required for startup script generated by Gradle
    bashNonInteractive
  ];

  doCheck = true;

  installPhase = ''
    runHook preInstall

    mkdir -p $out/opt
    tar xf build/distributions/apksigner.tar
    mv apksigner $out/opt
    mkdir -p $out/bin
    makeWrapper $out/opt/apksigner/bin/apksigner $out/bin/apksigner \
      --set JAVA_HOME ${jre.home}

    runHook postInstall
  '';

  __darwinAllowLocalNetworking = true;

  mitmCache = gradle.fetchDeps {
    inherit (finalAttrs) pname;
    data = ./deps.json;
  };

  meta = {
    description = "Command line tool to sign and verify Android APKs";
    homepage = "https://developer.android.com/tools/apksigner";
    license = lib.licenses.asl20;

    maintainers = with lib.maintainers; [
      linsui
      fliegendewurst
    ];

    platforms = lib.platforms.unix;
    mainProgram = "apksigner";
    downloadPage = "https://android.googlesource.com/platform/tools/apksig/";
    teams = [ lib.teams.android ];
  };
})
