{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.woodpecker-agents;

  agentModule = lib.types.submodule {
    options = {
      enable = lib.mkEnableOption "this Woodpecker-Agent. Agents execute tasks generated by a Server, every install will need one server and at least one agent";
      package = lib.mkPackageOption pkgs "woodpecker-agent" { };

      environment = lib.mkOption {
        default = { };
        description = "woodpecker-agent config environment variables, for other options read the [documentation](https://woodpecker-ci.org/docs/administration/configuration/agent)";

        example = lib.literalExpression ''
          {
            WOODPECKER_SERVER = "localhost:9000";
            WOODPECKER_BACKEND = "docker";
            DOCKER_HOST = "unix:///run/podman/podman.sock";
          }
        '';

        type = lib.types.attrsOf lib.types.str;
      };

      environmentFile = lib.mkOption {
        default = [ ];

        description = ''
          File to load environment variables
          from. This is helpful for specifying secrets.
          Example content of environmentFile:
          ```
          WOODPECKER_AGENT_SECRET=your-shared-secret-goes-here
          ```
        '';

        example = [ "/var/secrets/woodpecker-agent.env" ];
        type = lib.types.listOf lib.types.path;
      };

      extraGroups = lib.mkOption {
        default = [ ];

        description = ''
          Additional groups for the systemd service.
        '';

        example = [ "podman" ];
        type = lib.types.listOf lib.types.str;
      };

      path = lib.mkOption {
        default = [ ];

        description = ''
          Additional packages that should be added to the agent's `PATH`.
          Mostly useful for the `local` backend.
        '';

        example = [ "" ];
        type = lib.types.listOf lib.types.package;
      };
    };
  };

  mkAgentService = name: agentCfg: {
    name = "woodpecker-agent-${name}";

    value = {
      inherit (agentCfg) environment path;
      after = [ "network-online.target" ];
      description = "Woodpecker-Agent Service - ${name}";

      serviceConfig = {
        BindReadOnlyPaths = [
          "-/etc/resolv.conf"
          "-/etc/nsswitch.conf"
          "-/etc/ssl/certs"
          "-/etc/static/ssl/certs"
          "-/etc/hosts"
          "-/etc/localtime"
        ];

        CapabilityBoundingSet = "";
        DynamicUser = true;
        EnvironmentFile = agentCfg.environmentFile;
        ExecStart = lib.getExe agentCfg.package;
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateMounts = true;
        PrivateTmp = true;
        PrivateUsers = true;
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectSystem = "strict";
        Restart = "on-failure";
        RestartSec = 15;
        RestrictAddressFamilies = [ "AF_UNIX AF_INET AF_INET6" ];
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        SupplementaryGroups = agentCfg.extraGroups;
        SystemCallArchitectures = "native";
        SystemCallFilter = "~@clock @privileged @cpu-emulation @debug @keyring @module @mount @obsolete @raw-io @reboot @setuid @swap";
      };

      wantedBy = [ "multi-user.target" ];
      wants = [ "network-online.target" ];
    };
  };
in
{
  options = {
    services.woodpecker-agents = {
      agents = lib.mkOption {
        default = { };
        description = "woodpecker-agents configurations";

        example = lib.literalExpression ''
          {
            podman = {
              environment = {
                WOODPECKER_SERVER = "localhost:9000";
                WOODPECKER_BACKEND = "docker";
                DOCKER_HOST = "unix:///run/podman/podman.sock";
              };

              extraGroups = [ "podman" ];

              environmentFile = [ "/run/secrets/woodpecker/agent-secret.txt" ];
            };

            exec = {
              environment = {
                WOODPECKER_SERVER = "localhost:9000";
                WOODPECKER_BACKEND = "local";
              };

              environmentFile = [ "/run/secrets/woodpecker/agent-secret.txt" ];

              path = [
                # Needed to clone repos
                git
                git-lfs
                woodpecker-plugin-git
                # Used by the runner as the default shell
                bash
                # Most likely to be used in pipeline definitions
                coreutils
              ];
            };
          }
        '';

        type = lib.types.attrsOf agentModule;
      };
    };
  };

  config = {
    systemd.services =
      let
        mkServices = lib.mapAttrs' mkAgentService;
        enabledAgents = lib.filterAttrs (_: agent: agent.enable) cfg.agents;
      in
      mkServices enabledAgents;
  };

  meta.maintainers = with lib.maintainers; [
    ambroisie
    marcusramberg
  ];
}
