{
  config,
  lib,
  pkgs,
  options,
  ...
}:
let
  cfg = config.services.ipfs-cluster;

  # secret is by envvar, not flag
  initFlags = toString [
    (lib.optionalString (cfg.initPeers != [ ]) "--peers")
    (lib.strings.concatStringsSep "," cfg.initPeers)
  ];
in
{
  options = {

    services.ipfs-cluster = {

      enable = lib.mkEnableOption "Pinset orchestration for IPFS - requires ipfs daemon to be useful";

      consensus = lib.mkOption {
        description = "Consensus protocol - 'raft' or 'crdt'. <https://cluster.ipfs.io/documentation/guides/consensus/>";

        type = lib.types.enum [
          "raft"
          "crdt"
        ];
      };

      dataDir = lib.mkOption {
        default = "/var/lib/ipfs-cluster";
        description = "The data dir for ipfs-cluster.";
        type = lib.types.str;
      };

      initPeers = lib.mkOption {
        default = [ ];
        description = "Peer addresses to initialize with on first run.";
        type = lib.types.listOf lib.types.str;
      };

      openSwarmPort = lib.mkOption {
        default = false;
        description = "Open swarm port, secured by the cluster secret. This does not expose the API or proxy. <https://cluster.ipfs.io/documentation/guides/security/>";
        type = lib.types.bool;
      };

      secretFile = lib.mkOption {
        default = null;

        description = ''
          File containing the cluster secret in the format of EnvironmentFile as described by
          {manpage}`systemd.exec(5)`. For example:
          <programlisting>
          CLUSTER_SECRET=<replaceable>...</replaceable>
          </programlisting>

          If null, a new secret will be generated on first run and stored in the data directory.
          A secret in the correct format can also be generated by: `openssl rand -hex 32`
        '';

        type = lib.types.nullOr lib.types.path;
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.enable -> config.services.kubo.enable;
        message = "ipfs-cluster requires ipfs - configure and enable services.kubo";
      }
    ];

    environment.systemPackages = [ pkgs.ipfs-cluster ];
    networking.firewall.allowedTCPPorts = lib.mkIf cfg.openSwarmPort [ 9096 ];

    systemd.services.ipfs-cluster = {
      after = [ "ipfs-cluster-init.service" ];
      environment.IPFS_CLUSTER_PATH = cfg.dataDir;

      serviceConfig = {
        ExecStart = [ "${lib.getExe' pkgs.ipfs-cluster "ipfs-cluster-service"} daemon" ];
        Group = config.services.kubo.group;
        Type = "notify";
        User = config.services.kubo.user;
      };

      wantedBy = [ "multi-user.target" ];
      wants = [ "ipfs-cluster-init.service" ];
    };

    systemd.services.ipfs-cluster-init = {
      environment.IPFS_CLUSTER_PATH = cfg.dataDir;

      path = [
        "/run/wrappers"
        pkgs.ipfs-cluster
      ];

      serviceConfig = {
        EnvironmentFile = lib.mkIf (cfg.secretFile != null) cfg.secretFile;

        ExecStart = [
          "${lib.getExe' pkgs.ipfs-cluster "ipfs-cluster-service"} init --consensus ${cfg.consensus} ${initFlags}"
        ];

        Group = config.services.kubo.group;
        RemainAfterExit = true;
        Type = "oneshot";
        User = config.services.kubo.user;
      };

      # only run once (= when the data directory is empty)
      unitConfig.ConditionDirectoryNotEmpty = "!${cfg.dataDir}";
      wantedBy = [ "default.target" ];
    };

    systemd.tmpfiles.rules = [
      "d '${cfg.dataDir}' - ${config.services.kubo.user} ${config.services.kubo.group} - -"
    ];
  };

  meta = {
    maintainers = with lib.maintainers; [
      sorki
    ];
  };
}
