{
  buildDunePackage,
  menhirLib,
}:

buildDunePackage {
  inherit (menhirLib) version src;
  pname = "menhirGLR";

  meta = menhirLib.meta // {
    description = "Runtime support library for GLR parsers generated by Menhir";
  };
}
