{
  lib,
  stdenv,
  fetchurl,
  buildPackages,
  libgnurx,
  testers,
  updateAutotoolsGnuConfigScriptsHook,
  zlib,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

stdenv.mkDerivation (finalAttrs: {
  pname = "file";
  version = "5.48";

  src = fetchurl {
    hash = "sha256-7RRlaIOyOjZLQFfAVZXZMlLam8Rz0wEGUZUZ0NoUEoM=";

    urls = [
      "https://astron.com/pub/file/file-${finalAttrs.version}.tar.gz"
      "https://distfiles.macports.org/file/file-${finalAttrs.version}.tar.gz"
    ];
  };

  outputs = [
    "out"
    "dev"
    "man"
  ];

  strictDeps = true;

  nativeBuildInputs = [
    updateAutotoolsGnuConfigScriptsHook
  ];

  buildInputs = [ zlib ] ++ lib.optional stdenv.hostPlatform.isMinGW libgnurx;

  # In native builds, it will use the newly-compiled file instead.
  makeFlags = lib.optional (
    !lib.systems.equals stdenv.hostPlatform stdenv.buildPlatform
  ) "FILE_COMPILE=${lib.getExe buildPackages.file}";

  # https://bugs.astron.com/view.php?id=382
  doCheck = !stdenv.buildPlatform.isMusl;
  enableParallelBuilding = true;
  passthru.tests.pkg-config = testers.testMetaPkgConfig finalAttrs.finalPackage;

  meta = {
    description = "Program that shows the type of files";
    homepage = "https://darwinsys.com/file";
    license = lib.licenses.bsd2;
    maintainers = with lib.maintainers; [ doronbehar ];
    platforms = lib.platforms.all;
    mainProgram = "file";
    pkgConfigModules = [ "libmagic" ];
  };
})
