# Generated by rebar3_nix
let
  fetchOnly = { src, ... }: src;
in
{
  fetchFromGitHub,
  fetchHex,
  fetchgit,
  builder ? fetchOnly,
  overrides ? (x: y: { }),
}:
let
  self = packages // (overrides self packages);
  packages = with self; {
    cache_tab = builder {
      version = "1.0.34";

      src = fetchHex {
        sha256 = "sha256-DbnzF/OUHBfJ+OqBJeJe+ie77Uy/JKQsQm+tp0yCtpI=";
        pkg = "cache_tab";
        version = "1.0.34";
      };

      beamDeps = [ p1_utils ];
      name = "cache_tab";
    };

    eimp = builder {
      version = "1.0.27";

      src = fetchHex {
        sha256 = "sha256-PH6D4pO8+vUKG/BU/Etit7jEhKbkIY45dwmk0NhX8/w=";
        pkg = "eimp";
        version = "1.0.27";
      };

      beamDeps = [ p1_utils ];
      name = "eimp";
    };

    epam = builder {
      version = "1.0.14";

      src = fetchHex {
        sha256 = "sha256-LzRJ5yiFpypsKoQ/VhrdD8L3DXoh9hRWkwpUdHPU2Yk=";
        pkg = "epam";
        version = "1.0.14";
      };

      beamDeps = [ ];
      name = "epam";
    };

    eredis = builder {
      version = "1.7.1";

      src = fetchHex {
        sha256 = "sha256-fCtUxWb+1V/u8zQcp5sBAKY0j9PxYhhLftURjSWMPME=";
        pkg = "eredis";
        version = "1.7.1";
      };

      beamDeps = [ ];
      name = "eredis";
    };

    erlydtl = builder {
      version = "0.14.0";

      src = fetchHex {
        sha256 = "sha256-2A7ARM2PWICcGdKaxWBb4J6VUECRG2RFBeMendgUNDE=";
        pkg = "erlydtl";
        version = "0.14.0";
      };

      beamDeps = [ ];
      name = "erlydtl";
    };

    esip = builder {
      version = "1.0.60";

      src = fetchHex {
        sha256 = "sha256-BgTL1LvI2hWSwAgwz+MGIM5PZlurEZnRSjtF+v0DFE8=";
        pkg = "esip";
        version = "1.0.60";
      };

      beamDeps = [
        fast_tls
        p1_utils
        stun
      ];

      name = "esip";
    };

    ezlib = builder {
      version = "1.0.16";

      src = fetchHex {
        sha256 = "sha256-tIGVQEA9Hst+rmRf3/FCqNsrR22JMojTm6u5KSIlBAU=";
        pkg = "ezlib";
        version = "1.0.16";
      };

      beamDeps = [ p1_utils ];
      name = "ezlib";
    };

    fast_tls = builder {
      version = "1.1.26";

      src = fetchHex {
        sha256 = "sha256-aw1N0jCQN1Zeuqms858CgI9fghWjkQGh2jPCpbG1mz8=";
        pkg = "fast_tls";
        version = "1.1.26";
      };

      beamDeps = [ p1_utils ];
      name = "fast_tls";
    };

    fast_xml = builder {
      version = "1.1.60";

      src = fetchHex {
        sha256 = "sha256-z54nSd1HIEcCy3oEq1BFZC+gCW/fyc/y6cptPyq9N8U=";
        pkg = "fast_xml";
        version = "1.1.60";
      };

      beamDeps = [ p1_utils ];
      name = "fast_xml";
    };

    fast_yaml = builder {
      version = "1.0.40";

      src = fetchHex {
        sha256 = "sha256-J3BcKZAsHG8yaLqb84fV+pKLLmVbUxEPpHuOR20ys4Y=";
        pkg = "fast_yaml";
        version = "1.0.40";
      };

      beamDeps = [ p1_utils ];
      name = "fast_yaml";
    };

    idna = builder {
      version = "7.1.0";

      src = fetchHex {
        sha256 = "sha256-aulZoCW/Nt9hqMq4UI2WVIkbVCaoTETYLer/1t34xx8=";
        pkg = "idna";
        version = "7.1.0";
      };

      beamDeps = [ ];
      name = "idna";
    };

    jose = builder {
      version = "1.11.12";

      src = fetchHex {
        sha256 = "sha256-MekrZT6SELaWdlzdiFQ3RX3hrdKpAR2S+M9j5GQbq3s=";
        pkg = "jose";
        version = "1.11.12";
      };

      beamDeps = [ ];
      name = "jose";
    };

    luerl = builder {
      version = "1.2.3";

      src = fetchHex {
        sha256 = "sha256-G0udDKXX0oDR0nh6al7p9aISZBtiv/kVVrqlOAXfOu0=";
        pkg = "luerl";
        version = "1.2.3";
      };

      beamDeps = [ ];
      name = "luerl";
    };

    mqtree = builder {
      version = "1.0.20";

      src = fetchHex {
        sha256 = "sha256-XsDge5xIp4QGSWAL+W4UC0++nlAX4d3T6JjhXAo4PtA=";
        pkg = "mqtree";
        version = "1.0.20";
      };

      beamDeps = [ p1_utils ];
      name = "mqtree";
    };

    p1_acme = builder {
      version = "1.0.31";

      src = fetchHex {
        sha256 = "sha256-m1kiqQq5TaWInmTeXMrTrcbmim08P7cI3VA3V7Iy2xw=";
        pkg = "p1_acme";
        version = "1.0.31";
      };

      beamDeps = [
        idna
        jose
        yconf
      ];

      name = "p1_acme";
    };

    p1_mysql = builder {
      version = "1.0.28";

      src = fetchHex {
        sha256 = "sha256-bk0A6OzlBbpQkcjas67+QVzy2Db/OVCDRMNSezZtmRk=";
        pkg = "p1_mysql";
        version = "1.0.28";
      };

      beamDeps = [ ];
      name = "p1_mysql";
    };

    p1_oauth2 = builder {
      version = "0.6.14";

      src = fetchHex {
        sha256 = "sha256-H9OsR05Dci2dWofG34029pjth697uBy7tmNhRR2Zro8=";
        pkg = "p1_oauth2";
        version = "0.6.14";
      };

      beamDeps = [ ];
      name = "p1_oauth2";
    };

    p1_pgsql = builder {
      version = "1.1.41";

      src = fetchHex {
        sha256 = "sha256-Ju4quj1FBGTt1LP/nassalP8ILv9Mwppc5grkGUEoXI=";
        pkg = "p1_pgsql";
        version = "1.1.41";
      };

      beamDeps = [ stringprep ];
      name = "p1_pgsql";
    };

    p1_utils = builder {
      version = "1.0.29";

      src = fetchHex {
        sha256 = "sha256-IHFCHK21uP/xFOkdTZRPFIUcMyOR9uk/xQEarWSr4bk=";
        pkg = "p1_utils";
        version = "1.0.29";
      };

      beamDeps = [ ];
      name = "p1_utils";
    };

    pkix = builder {
      version = "1.0.10";

      src = fetchHex {
        sha256 = "sha256-4CFk+DCUyxJMQbGrKJiKYV1Uua3DhXXwDxmll6OsXQ4=";
        pkg = "pkix";
        version = "1.0.10";
      };

      beamDeps = [ ];
      name = "pkix";
    };

    sqlite3 = builder {
      version = "1.1.15";

      src = fetchHex {
        sha256 = "sha256-PAuk4TMiwq1J3k4t3SgxE2at3lS+ro26nZ44iPadKFc=";
        pkg = "sqlite3";
        version = "1.1.15";
      };

      beamDeps = [ ];
      name = "sqlite3";
    };

    stringprep = builder {
      version = "1.0.34";

      src = fetchHex {
        sha256 = "sha256-J+eOo3GIF2TgVvvoRdOtMEdA/14xMbwfOKZvC6qMm0c=";
        pkg = "stringprep";
        version = "1.0.34";
      };

      beamDeps = [ p1_utils ];
      name = "stringprep";
    };

    stun = builder {
      version = "1.2.22";

      src = fetchHex {
        sha256 = "sha256-NAi0sR1SN6CI9TsmCgaUDDCxb0pICUiS1qkgThZDGIo=";
        pkg = "stun";
        version = "1.2.22";
      };

      beamDeps = [
        fast_tls
        p1_utils
      ];

      name = "stun";
    };

    xmpp = builder {
      version = "1.13.3";

      src = fetchHex {
        sha256 = "sha256-BWSKpNvM/uYqqnlLKSowWEY50DyR9cCGa+jDQ0tqb0g=";
        pkg = "xmpp";
        version = "1.13.3";
      };

      beamDeps = [
        ezlib
        fast_tls
        fast_xml
        idna
        p1_utils
        stringprep
      ];

      name = "xmpp";
    };

    yconf = builder {
      version = "1.0.23";

      src = fetchHex {
        sha256 = "sha256-JbTft1MoAmrKp3TPXG+4fUi1XuvOYw3aozYkQdrDFDc=";
        pkg = "yconf";
        version = "1.0.23";
      };

      beamDeps = [ fast_yaml ];
      name = "yconf";
    };
  };
in
self
