# This is automatically generated by the update script.
# DO NOT MANUALLY EDIT.
{
  assets-hash = "sha256-cta4k6yxrdaFFfum0eshEzLODExBfA+oVPqcOpXG9uk=";
  edopro-hash = "sha256-ZkQXWt73S3Nn+RnkG+e91BId7keI5OpM3NSeDMJWlZY=";
  edopro-rev = "e5c0578aa504d0831dcbe29dbacd018f7b885b2c";
  edopro-version = "41.0.2";
  irrlicht-hash = "sha256-AwUCHQOivNgSnYe8kG6JxDIz7H5PC6RoozGiOGUejTI=";
  irrlicht-rev = "47264fc2bc3223d110c589c9ffe4339d696a3dd0";
  irrlicht-version = "1.9.0-unstable-2025-03-30";
}
