{
  lib,
  stdenv,
  dub,
  dubBuildHook,
  dubCheckHook,
  dubSetupHook,
  importDubLock,
  ldc,
  removeReferencesTo,
}:

lib.extendMkDerivation {
  constructDrv = stdenv.mkDerivation;

  excludeDrvArgNames = [
    "dubLock"
    "compiler"
  ];

  extendDrvArgs =
    finalAttrs:
    {
      # A lockfile generated by `dub-to-nix` from the source of the package.
      # Can be either a path to the file, or an attrset already parsed with `lib.importJSON`.
      dubLock,
      compiler ? ldc,
      ...
    }@args:

    {
      strictDeps = args.strictDeps or true;

      nativeBuildInputs = args.nativeBuildInputs or [ ] ++ [
        dubSetupHook
        (dubBuildHook.override { inherit dub; })
        compiler
        removeReferencesTo
      ];

      doCheck = args.doCheck or false;

      nativeCheckInputs = [
        (dubCheckHook.override { inherit dub; })
      ];

      preFixup = ''
        ${args.preFixup or ""}

        find "$out" -type f -exec remove-references-to ${
          lib.concatMapStringsSep " " (output: "-t ${output}") compiler.all
        } '{}' +
      '';

      __structuredAttrs = args.__structuredAttrs or true;

      configurePhase = ''
        runHook preConfigure
        dubFlags+=("--compiler=${lib.getExe compiler}")
        runHook postConfigure
      '';

      disallowedReferences = args.disallowedReferences or compiler.all;

      dubDeps = importDubLock {
        inherit (finalAttrs) pname version;
        lock = dubLock;
      };

      meta = {
        platforms = dub.meta.platforms;
      }
      // args.meta or { };
    };
}
