{
  lib,
  stdenv,
  fetchurl,
  anthy,
  autoconf,
  automake116x,
  cmake,
  curl,
  expat,
  gtk2,
  gtk3,
  intltool,
  libeb,
  libffi,
  libnotify,
  librsvg,
  libtool,
  m17n_db,
  m17n_lib,
  ncurses,
  openssl,
  pkg-config,
  qt5,
  ruby,
  shared-mime-info,
  sqlite,
  withAnthy ? true,
  withFFI ? true,
  withGtk ? true,
  withGtk2 ? withGtk,
  withGtk3 ? withGtk,
  withLibnotify ? true,
  # Things that are clearly an overkill to be enabled by default
  withMisc ? false,
  withNetworking ? true,
  # Was never enabled in the history of this package and is not needed by any
  # dependent package, hence disabled to save up closure size.
  withQt ? false,
  withQt5 ? withQt,
  withSqlite ? true,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "uim";
  version = "1.9.6";

  src = fetchurl {
    url = "https://github.com/uim/uim/releases/download/${finalAttrs.version}/uim-${finalAttrs.version}.tar.bz2";
    hash = "sha256-Z/Dl+kKSpTPtxvmLhC32DFMaic+C0DNqThq3IgKrjIM=";

    meta = {
      homepage = "https://github.com/uim/uim/";
    };
  };

  patches = [
    ./data-hook.patch
  ];

  postPatch = ''
    patchShebangs *.sh */*.sh */*/*.sh
    cp replace/*.h uim
  '';

  nativeBuildInputs = [
    autoconf
    automake116x
    intltool
    libtool
    pkg-config
    cmake

    ruby # used by sigscheme build to generate function tables
    librsvg # used by uim build to generate png pixmaps from svg
  ]
  ++ lib.optionals withQt5 [
    qt5.wrapQtAppsHook
  ];

  buildInputs = [
    ncurses
    m17n_lib
    m17n_db
    expat
  ]
  ++ lib.optional withAnthy anthy
  ++ lib.optional withGtk2 gtk2
  ++ lib.optional withGtk3 gtk3
  ++ lib.optionals withQt5 [
    qt5.qtbase
    qt5.qtx11extras
  ]
  ++ lib.optional withLibnotify libnotify
  ++ lib.optional withSqlite sqlite
  ++ lib.optionals withNetworking [
    curl
    openssl
  ]
  ++ lib.optional withFFI libffi
  ++ lib.optional withMisc libeb;

  configureFlags = [
    # configure in maintainer mode or else some pixmaps won't get autogenerated
    # this should imply the above `--enable-maintainer-mode`, but it does not
    "--enable-maintainer-mode"

    "--enable-pref"
    "--with-skk"
    "--with-x"
    "--with-xft"
    "--with-expat=${expat.dev}"
  ]
  ++ lib.optional withAnthy "--with-anthy-utf8"
  ++ lib.optional withGtk2 "--with-gtk2"
  ++ lib.optional withGtk3 "--with-gtk3"
  ++ lib.optionals withQt5 [
    "--with-qt5"
    "--with-qt5-immodule"
  ]
  ++ lib.optional withLibnotify "--enable-notify=libnotify"
  ++ lib.optional withSqlite "--with-sqlite3"
  ++ lib.optionals withNetworking [
    "--with-curl"
    "--with-openssl-dir=${openssl.dev}"
  ]
  ++ lib.optional withFFI "--with-ffi"
  ++ lib.optional withMisc "--with-eb";

  # TODO: things in `./configure --help`, but not in nixpkgs
  #--with-canna            Use Canna [default=no]
  #--with-wnn              Build with libwnn [default=no]
  #--with-mana             Build a plugin for Mana [default=yes]
  #--with-prime            Build a plugin for PRIME [default=yes]
  #--with-sj3              Use SJ3 [default=no]
  #--with-osx-dcs          Build with OS X Dictionary Services [default=no]
  # TODO: fix this in librsvg/glib later
  # https://github.com/NixOS/nixpkgs/pull/57027#issuecomment-475461733
  preBuild = ''
    export XDG_DATA_DIRS="${shared-mime-info}/share"
  '';

  dontUseCmakeConfigure = true;

  meta = {
    inherit (finalAttrs.src.meta) homepage;
    description = "Multilingual input method framework";
    license = lib.licenses.bsd3;

    maintainers = with lib.maintainers; [
      oxij
    ];

    platforms = lib.platforms.unix;
  };
})
