# Generated by rebar3_nix
let
  fetchOnly = { src, ... }: src;
in
{
  fetchFromGitHub,
  fetchHex,
  fetchgit,
  builder ? fetchOnly,
  overrides ? (x: y: { }),
}:
let
  self = packages // (overrides self packages);
  packages = with self; {
    elvis_core = builder {
      version = "5.0.4";

      src = fetchHex {
        sha256 = "sha256-fgzg0yNrG1afDvE5jrJzIf2GNnJy4LFPOJDQQTrMPpo=";
        pkg = "elvis_core";
        version = "5.0.4";
      };

      beamDeps = [ katana_code ];
      name = "elvis_core";
    };

    getopt = builder {
      version = "1.0.3";

      src = fetchHex {
        sha256 = "sha256-fgHekKxUDyFJT/cnkrHjFi05mWbrv8Z0tM5Sy49JMk8=";
        pkg = "getopt";
        version = "1.0.3";
      };

      beamDeps = [ ];
      name = "getopt";
    };

    katana_code = builder {
      version = "2.4.3";

      src = fetchHex {
        sha256 = "sha256-YUxjQ9uqRc7e8n0j6wkBo4PEa/61dwOaXmDK0XGGzO4=";
        pkg = "katana_code";
        version = "2.4.3";
      };

      beamDeps = [ ];
      name = "katana_code";
    };
  };
in
self
