{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.minio;

  legacyCredentials =
    cfg:
    pkgs.writeText "minio-legacy-credentials" ''
      MINIO_ROOT_USER=${cfg.accessKey}
      MINIO_ROOT_PASSWORD=${cfg.secretKey}
    '';
in
{
  options.services.minio = {
    enable = mkEnableOption "Minio Object Storage";
    package = mkPackageOption pkgs "minio" { };

    accessKey = mkOption {
      default = "";

      description = ''
        Access key of 5 to 20 characters in length that clients use to access the server.
        This overrides the access key that is generated by minio on first startup and stored inside the
        `configDir` directory.
      '';

      type = types.str;
    };

    browser = mkOption {
      default = true;
      description = "Enable or disable access to web UI.";
      type = types.bool;
    };

    certificatesDir = mkOption {
      default = "/var/lib/minio/certs";
      description = "The directory where TLS certificates are stored.";
      type = types.path;
    };

    configDir = mkOption {
      default = "/var/lib/minio/config";
      description = "The config directory, for the access keys and other settings.";
      type = types.path;
    };

    consoleAddress = mkOption {
      default = ":9001";
      description = "IP address and port of the web UI (console).";
      type = types.str;
    };

    dataDir = mkOption {
      default = [ "/var/lib/minio/data" ];
      description = "The list of data directories or nodes for storing the objects. Use one path for regular operation and the minimum of 4 endpoints for Erasure Code mode.";
      type = types.listOf (types.either types.path types.str);
    };

    listenAddress = mkOption {
      default = ":9000";
      description = "IP address and port of the server.";
      type = types.str;
    };

    region = mkOption {
      default = "us-east-1";

      description = ''
        The physical location of the server. By default it is set to us-east-1, which is same as AWS S3's and Minio's default region.
      '';

      type = types.str;
    };

    rootCredentialsFile = mkOption {
      default = null;

      description = ''
        File containing the MINIO_ROOT_USER, default is "minioadmin", and
        MINIO_ROOT_PASSWORD (length >= 8), default is "minioadmin"; in the format of
        an EnvironmentFile=, as described by {manpage}`systemd.exec(5)`.
      '';

      example = "/etc/nixos/minio-root-credentials";
      type = types.nullOr types.path;
    };

    secretKey = mkOption {
      default = "";

      description = ''
        Specify the Secret key of 8 to 40 characters in length that clients use to access the server.
        This overrides the secret key that is generated by minio on first startup and stored inside the
        `configDir` directory.
      '';

      type = types.str;
    };
  };

  config = mkIf cfg.enable {
    systemd = lib.mkMerge [
      {
        services.minio = {
          after = [ "network-online.target" ];
          description = "Minio Object Storage";

          environment = {
            MINIO_BROWSER = "${if cfg.browser then "on" else "off"}";
            MINIO_REGION = "${cfg.region}";
          };

          serviceConfig = {
            CapabilityBoundingSet = "";
            DeviceAllow = "";
            # hardening
            DevicePolicy = "closed";

            EnvironmentFile =
              if (cfg.rootCredentialsFile != null) then
                cfg.rootCredentialsFile
              else if ((cfg.accessKey != "") || (cfg.secretKey != "")) then
                (legacyCredentials cfg)
              else
                null;

            ExecStart = "${cfg.package}/bin/minio server --json --address ${cfg.listenAddress} --console-address ${cfg.consoleAddress} --config-dir=${cfg.configDir} --certs-dir=${cfg.certificatesDir} ${toString cfg.dataDir}";
            Group = "minio";
            LimitNOFILE = 65536;
            LockPersonality = true;
            MemoryDenyWriteExecute = true;
            NoNewPrivileges = true;
            PrivateDevices = true;
            PrivateMounts = true;
            PrivateTmp = true;
            PrivateUsers = true;
            # minio opens /proc/mounts on startup
            ProcSubset = "all";
            ProtectClock = true;
            ProtectControlGroups = true;
            ProtectHome = true;
            ProtectHostname = true;
            ProtectKernelLogs = true;
            ProtectKernelModules = true;
            ProtectKernelTunables = true;
            ProtectProc = "invisible";
            RemoveIPC = true;

            RestrictAddressFamilies = [
              "AF_INET"
              "AF_INET6"
              "AF_NETLINK"
              "AF_UNIX"
            ];

            RestrictNamespaces = true;
            RestrictRealtime = true;
            RestrictSUIDSGID = true;
            SystemCallArchitectures = "native";

            SystemCallFilter = [
              "@system-service"
              "~@privileged"
            ];

            Type = "simple";
            UMask = "0077";
            User = "minio";
          };

          wantedBy = [ "multi-user.target" ];
          wants = [ "network-online.target" ];
        };

        tmpfiles.rules = [
          "d '${cfg.configDir}' - minio minio - -"
        ]
        ++ (map (x: "d '" + x + "' - minio minio - - ") (builtins.filter lib.types.path.check cfg.dataDir));
      }

      (lib.mkIf (cfg.rootCredentialsFile != null) {
        # The service will not restart if the credentials file has
        # been changed. This can cause stale root credentials.
        paths.minio-root-credentials = {
          pathConfig = {
            PathChanged = [ cfg.rootCredentialsFile ];
            Unit = "minio-restart.service";
          };

          wantedBy = [ "multi-user.target" ];
        };

        # The service will fail if the credentials file is missing
        services.minio.unitConfig.ConditionPathExists = cfg.rootCredentialsFile;

        services.minio-restart = {
          description = "Restart MinIO";

          script = ''
            systemctl restart minio.service
          '';

          serviceConfig = {
            Restart = "on-failure";
            RestartSec = 5;
            Type = "oneshot";
          };
        };
      })
    ];

    users.groups.minio.gid = config.ids.uids.minio;

    users.users.minio = {
      group = "minio";
      uid = config.ids.uids.minio;
    };

    warnings =
      optional ((cfg.accessKey != "") || (cfg.secretKey != ""))
        "services.minio.`accessKey` and services.minio.`secretKey` are deprecated, please use services.minio.`rootCredentialsFile` instead.";
  };

  meta.maintainers = with maintainers; [
    bachp
    ryan4yin
  ];
}
