{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.stargazer;
  globalSection = ''
    listen = ${lib.concatStringsSep " " cfg.listen}
    connection-logging = ${lib.boolToString cfg.connectionLogging}
    log-ip = ${lib.boolToString cfg.ipLog}
    log-ip-partial = ${lib.boolToString cfg.ipLogPartial}
    request-timeout = ${toString cfg.requestTimeout}
    response-timeout = ${toString cfg.responseTimeout}

    [:tls]
    store = ${toString cfg.store}
    organization = ${cfg.certOrg}
    gen-certs = ${lib.boolToString cfg.genCerts}
    regen-certs = ${lib.boolToString cfg.regenCerts}
    ${lib.optionalString (cfg.certLifetime != "") "cert-lifetime = ${cfg.certLifetime}"}

  '';
  genINI = lib.generators.toINI { };
  configFile = pkgs.writeText "config.ini" (
    lib.strings.concatStrings (
      [ globalSection ]
      ++ (lib.lists.forEach cfg.routes (
        section:
        let
          name = section.route;
          params = removeAttrs section [ "route" ];
        in
        genINI {
          "${name}" = params;
        }
        + "\n"
      ))
    )
  );
in
{
  options.services.stargazer = {
    enable = lib.mkEnableOption "Stargazer Gemini server";

    allowCgiUser = lib.mkOption {
      default = false;

      description = ''
        When enabled, the stargazer process will be given `CAP_SETGID`
        and `CAP_SETUID` so that it can run cgi processes as a different
        user. This is required if the `cgi-user` option is used for a route.
        Note that these capabilities could allow privilege escalation so be
        careful. For that reason, this is disabled by default.

        You will need to create the user mentioned `cgi-user` if it does not
        already exist.
      '';

      type = lib.types.bool;
    };

    certLifetime = lib.mkOption {
      default = "";

      description = ''
        How long certs generated by Stargazer should live for.
        Certs live forever by default.
      '';

      example = lib.literalExpression "\"1y\"";
      type = lib.types.str;
    };

    certOrg = lib.mkOption {
      default = "stargazer";

      description = ''
        The name of the organization responsible for the X.509
        certificate's /O name.
      '';

      type = lib.types.str;
    };

    connectionLogging = lib.mkOption {
      default = true;
      description = "Whether or not to log connections to stdout.";
      type = lib.types.bool;
    };

    debugMode = lib.mkOption {
      default = false;
      description = "Run Stargazer in debug mode.";
      type = lib.types.bool;
    };

    genCerts = lib.mkOption {
      default = true;

      description = ''
        Set to false to disable automatic certificate generation.
        Use if you want to provide your own certs.
      '';

      type = lib.types.bool;
    };

    group = lib.mkOption {
      default = "stargazer";
      description = "Group account under which stargazer runs.";
      type = lib.types.str;
    };

    ipLog = lib.mkOption {
      default = false;
      description = "Log client IP addresses in the connection log.";
      type = lib.types.bool;
    };

    ipLogPartial = lib.mkOption {
      default = false;
      description = "Log partial client IP addresses in the connection log.";
      type = lib.types.bool;
    };

    listen = lib.mkOption {
      default = [ "0.0.0.0" ] ++ lib.optional config.networking.enableIPv6 "[::0]";
      defaultText = lib.literalExpression ''[ "0.0.0.0" ] ++ lib.optional config.networking.enableIPv6 "[::0]"'';

      description = ''
        Address and port to listen on.
      '';

      example = lib.literalExpression ''[ "10.0.0.12" "[2002:a00:1::]" ]'';
      type = lib.types.listOf lib.types.str;
    };

    regenCerts = lib.mkOption {
      default = true;

      description = ''
        Set to false to turn off automatic regeneration of expired certificates.
        Use if you want to provide your own certs.
      '';

      type = lib.types.bool;
    };

    requestTimeout = lib.mkOption {
      default = 5;

      description = ''
        Number of seconds to wait for the client to send a complete
        request. Set to 0 to disable.
      '';

      type = lib.types.ints.unsigned;
    };

    responseTimeout = lib.mkOption {
      default = 0;

      description = ''
        Number of seconds to wait for the client to send a complete
        request and for stargazer to finish sending the response.
        Set to 0 to disable.
      '';

      type = lib.types.ints.unsigned;
    };

    routes = lib.mkOption {
      default = [ ];

      description = ''
        Routes that Stargazer should server.

        Expressed as a list of attribute sets. Each set must have a key `route`
        that becomes the section name for that route in the stargazer ini cofig.
        The remaining keys and values become the parameters for that route.

        [Refer to upstream docs for other params](https://git.sr.ht/~zethra/stargazer/tree/main/item/doc/stargazer.ini.5.txt)
      '';

      example = lib.literalExpression ''
        [
          {
            route = "example.com";
            root = "/srv/gemini/example.com"
          }
          {
            route = "example.com:/man";
            root = "/cgi-bin";
            cgi = true;
          }
          {
            route = "other.org~(.*)";
            redirect = "gemini://example.com";
            rewrite = "\1";
          }
        ]
      '';

      type = lib.types.listOf (
        lib.types.submodule {
          options.route = lib.mkOption {
            description = "Route section name";
            type = lib.types.str;
          };

          freeformType =
            with lib.types;
            attrsOf (
              nullOr (oneOf [
                bool
                int
                float
                str
              ])
              // {
                description = "INI atom (null, bool, int, float or string)";
              }
            );
        }
      );
    };

    store = lib.mkOption {
      default = "/var/lib/gemini/certs";

      description = ''
        Path to the certificate store on disk. This should be a
        persistent directory writable by Stargazer.
      '';

      type = lib.types.path;
    };

    user = lib.mkOption {
      default = "stargazer";
      description = "User account under which stargazer runs.";
      type = lib.types.str;
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.services.stargazer = {
      after = [ "network.target" ];
      description = "Stargazer gemini server";

      serviceConfig = {
        AmbientCapabilities = lib.mkIf cfg.allowCgiUser [
          "CAP_SETGID"
          "CAP_SETUID"
        ];

        CapabilityBoundingSet = [
          "~CAP_SYS_PTRACE"
          "~CAP_SYS_ADMIN"
          "~CAP_SETPCAP"
          "~CAP_SYS_TIME"
          "~CAP_SYS_PACCT"
          "~CAP_SYS_TTY_CONFIG "
          "~CAP_SYS_CHROOT"
          "~CAP_SYS_BOOT"
          "~CAP_NET_ADMIN"
        ]
        ++ lib.lists.optional (!cfg.allowCgiUser) [
          "~CAP_SETGID"
          "~CAP_SETUID"
        ];

        ExecStart = "${pkgs.stargazer}/bin/stargazer ${configFile} ${lib.optionalString cfg.debugMode "-D"}";
        Group = cfg.group;
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateMounts = true;
        PrivateTmp = true;
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectProc = "invisible";
        ProtectSystem = "full";
        RemoveIPC = true;
        Restart = "always";
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        SystemCallArchitectures = "native";

        SystemCallFilter = [
          "~@cpu-emulation @debug @keyring @mount @obsolete"
        ]
        ++ lib.lists.optional (!cfg.allowCgiUser) [ "@privileged @setuid" ];

        # Hardening
        UMask = "0077";
        # User and group
        User = cfg.user;
      };

      wantedBy = [ "multi-user.target" ];
    };

    # Create default cert store
    systemd.tmpfiles.rules = lib.mkIf ((builtins.toString cfg.store) == "/var/lib/gemini/certs") [
      ''d /var/lib/gemini/certs - "${cfg.user}" "${cfg.group}" -''
    ];

    users.groups = lib.optionalAttrs (cfg.group == "stargazer") {
      stargazer = { };
    };

    users.users = lib.optionalAttrs (cfg.user == "stargazer") {
      stargazer = {
        group = cfg.group;
        isSystemUser = true;
      };
    };
  };

  meta.maintainers = with lib.maintainers; [ gaykitty ];
}
