{
  lib,
  stdenv,
  fetchFromGitHub,
  autoreconfHook,
  perl,
  pkg-config,
  zlib,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "vcftools";
  version = "0.1.17";

  src = fetchFromGitHub {
    owner = "vcftools";
    repo = "vcftools";
    rev = "v${finalAttrs.version}";
    sha256 = "sha256-IiePgDpaL/6XOpQsOn90clB6ST7F/37sztmHrC7Ysbw=";
  };

  nativeBuildInputs = [
    pkg-config
    autoreconfHook
  ];

  buildInputs = [
    zlib
    perl
  ];

  meta = {
    description = "Set of tools written in Perl and C++ for working with VCF files, such as those generated by the 1000 Genomes Project";
    homepage = "https://vcftools.github.io/index.html";
    license = lib.licenses.lgpl3;
    maintainers = [ lib.maintainers.rybern ];
    platforms = lib.platforms.linux;
  };
})
