{
  lib,
  stdenv,
  fetchCrate,
  fixDarwinDylibNames,
  haskellPackages,
  rustPlatform,
}:

let
  pin = lib.importJSON ./pin.json;
in

rustPlatform.buildRustPackage {
  inherit (pin) pname version;
  src = fetchCrate pin;

  outputs = [
    "out"
    "dev"
  ];

  # upstream doesn't ship a Cargo.lock, is generated by the update script
  postPatch = ''
    cp ${./Cargo.lock} Cargo.lock
  '';

  nativeBuildInputs = lib.optionals stdenv.hostPlatform.isDarwin [
    fixDarwinDylibNames
  ];

  cargoLock.lockFile = ./Cargo.lock;

  # Headers are not handled by cargo nor buildRustPackage
  postInstall = ''
    install -Dm644 include/rure.h -t "$dev/include"
  '';

  passthru = {
    tests.haskell-bindings = haskellPackages.regex-rure;
    updateScript = ./update.sh;
  };

  meta = {
    description = "C API for Rust's regular expression library";
    homepage = "https://crates.io/crates/rure";

    license = [
      lib.licenses.mit
      lib.licenses.asl20
    ];

    maintainers = [ lib.maintainers.sternenseemann ];
  };
}
