# Generated by update.sh
{ fetchurl }:

{
  "boringssl-673e61fc215b178a90c0e67858bbf162c8158993.zip" = fetchurl {
    hash = "sha256-7bfWHo3j95EHAXJyPuQfvFUPtVCAzbGHu0oF5g4FmiI=";
    url = "https://github.com/google/boringssl/archive/673e61fc215b178a90c0e67858bbf162c8158993.zip";
  };

  "brotli-1.2.0.tar.gz" = fetchurl {
    hash = "sha256-gWyW6Ojxk7QBUdrX6P83sSIdAZ28ucNc0/rb/mR33+w=";
    url = "https://github.com/google/brotli/archive/refs/tags/v1.2.0.tar.gz";
  };

  "curl-8_15_0.tar.gz" = fetchurl {
    hash = "sha256-KTfK3eAHqjpSoXwhrJFT6gVHAPN5JtHZZgK/B+iIyEc=";
    url = "https://github.com/curl/curl/archive/curl-8_15_0.tar.gz";
  };

  "libidn2-2.3.7.tar.gz" = fetchurl {
    hash = "sha256-TCGnkbYQuVGbnQ4SuAl78vNZsS+N2SZHYRqSnmv9fWQ=";
    url = "https://ftp.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz";
  };

  "libunistring-1.1.tar.gz" = fetchurl {
    hash = "sha256-oiUr7uyDCsREufaNazitiD2xmRnbNbUiIs+CfDhb22o=";
    url = "https://ftp.gnu.org/gnu/libunistring/libunistring-1.1.tar.gz";
  };

  "nghttp2-1.63.0.tar.bz2" = fetchurl {
    hash = "sha256-YHsXRVTSKoKLxTLR1zT+D3KbXV7SB/LxLpamLoPynFU=";
    url = "https://github.com/nghttp2/nghttp2/releases/download/v1.63.0/nghttp2-1.63.0.tar.bz2";
  };

  "nghttp3-1.15.0.tar.bz2" = fetchurl {
    hash = "sha256-xsSRpSgEgUCY5EZjDm78RZr8DT2nlS/+bL3As/mbK2I=";
    url = "https://github.com/ngtcp2/nghttp3/releases/download/v1.15.0/nghttp3-1.15.0.tar.bz2";
  };

  "ngtcp2-1.20.0.tar.bz2" = fetchurl {
    hash = "sha256-hx7JethoA88xKQGww5Ow7nAWPiWofJsolNEjQ0HOTpc=";
    url = "https://github.com/ngtcp2/ngtcp2/releases/download/v1.20.0/ngtcp2-1.20.0.tar.bz2";
  };

  "zlib-1.3.1.tar.gz" = fetchurl {
    hash = "sha256-mpOyt9/ax3zrpaVYpYDnRmfdb+3kWFuR7vtg8Dty3yM=";
    url = "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz";
  };

  "zstd-1.5.6.tar.gz" = fetchurl {
    hash = "sha256-jCngbPQqrMHq/EB3ri7Gxvy5amJhV+BZPV6Co0/UA8E=";
    url = "https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-1.5.6.tar.gz";
  };
}
