# Generated by ./update.sh - do not update manually!
# Last updated: 2026-06-21
{
  aarch64-darwin = {
    hash = "sha256-vlT96ROqB/6Jt/x60Zeh6B4MtN2NGyn5PWv9pNafF/8=";
    url = "https://package.mac.wpscdn.cn/mac_wps_pkg/12.1.26016/WPS_Office_12.1.26016(26016)_arm64.dmg";
  };

  darwin-version = "12.1.26016";
  linux-version = "12.1.2.26885";

  x86_64-linux = {
    hash = "sha256-VdpRSUZ6FYS0ttEoDLWrBMBhRTl0gQ+slnmzO9hmTlE=";
    url = "https://wps-linux-personal.wpscdn.cn/wps/download/ep/Linux2023/26885/wps-office_12.1.2.26885.AK.preread.sw.Personal_715971_amd64.deb";
  };
}
