{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.factorio;
  name = "Factorio";
  stateDir = "/var/lib/${cfg.stateDirName}";
  mkSavePath = name: "${stateDir}/saves/${name}.zip";
  configFile = pkgs.writeText "factorio.conf" ''
    use-system-read-write-data-directories=true
    [path]
    read-data=${cfg.package}/share/factorio/data
    write-data=${stateDir}
  '';
  serverSettings = {
    afk_autokick_interval = 0;
    allow_commands = "admins-only";
    auto_pause = true;
    autosave_interval = cfg.autosave-interval;
    autosave_only_on_server = true;
    autosave_slots = 5;
    description = cfg.description;
    game_password = cfg.game-password;
    ignore_player_limit_for_returning_players = false;
    max_upload_in_kilobytes_per_second = 0;
    minimum_latency_in_ticks = 0;
    name = cfg.game-name;
    non_blocking_saving = cfg.nonBlockingSaving;
    only_admins_can_pause_the_game = true;
    password = cfg.password;
    require_user_verification = cfg.requireUserVerification;
    token = cfg.token;
    username = cfg.username;

    visibility = {
      lan = cfg.lan;
      public = cfg.public;
    };
  }
  // cfg.extraSettings;
  serverSettingsString = builtins.toJSON (lib.filterAttrsRecursive (n: v: v != null) serverSettings);
  serverSettingsFile = pkgs.writeText "server-settings.json" serverSettingsString;
  playerListOption =
    name: list:
    lib.optionalString (
      list != [ ]
    ) "--${name}=${pkgs.writeText "${name}.json" (builtins.toJSON list)}";
  modDir = pkgs.factorio-utils.mkModDirDrv cfg.mods cfg.mods-dat;
in
{
  options = {
    services.factorio = {
      enable = lib.mkEnableOption name;

      package = lib.mkPackageOption pkgs "factorio-headless" {
        example = "factorio-headless-experimental";
      };

      # Opting not to include the banlist in addition the the whitelist because:
      # - banlists are not as often known in advance,
      # - losing banlist changes on restart seems much more of a headache.
      admins = lib.mkOption {
        default = [ ];

        description = ''
          List of player names which will be admin.
        '';

        example = [ "username" ];
        type = lib.types.listOf lib.types.str;
      };

      allowedPlayers = lib.mkOption {
        default = [ ];

        description = ''
          If non-empty, only these player names are allowed to connect. The game
          will not be able to save any changes made in-game with the /whitelist
          console command, though they will still take effect until the server
          is restarted.

          If empty, the whitelist defaults to open, but can be managed with the
          in-game /whitelist console command (see: /help whitelist), which will
          cause changes to be saved to the game's state directory (see also:
          `stateDirName`).
        '';

        example = [
          "Rseding91"
          "Oxyd"
        ];

        # I would personally prefer for `allowedPlayers = []` to mean "no-one
        # can connect" but Factorio seems to ignore empty whitelists (even with
        # --use-server-whitelist) so we can't implement that behaviour, so we
        # might as well match theirs.
        type = lib.types.listOf lib.types.str;
      };

      autosave-interval = lib.mkOption {
        default = null;

        description = ''
          Autosave interval in minutes.
        '';

        example = 10;
        type = lib.types.nullOr lib.types.int;
      };

      bind = lib.mkOption {
        default = "0.0.0.0";

        description = ''
          The address to which the service should bind.
        '';

        type = lib.types.str;
      };

      # TODO Add more individual settings as nixos-options?
      # TODO XXX The server tries to copy a newly created config file over the old one
      #   on shutdown, but fails, because it's in the nix store. When is this needed?
      #   Can an admin set options in-game and expect to have them persisted?
      configFile = lib.mkOption {
        default = configFile;
        defaultText = lib.literalExpression "configFile";

        description = ''
          The server's configuration file.

          The default file generated by this module contains lines essential to
          the server's operation. Use its contents as a basis for any
          customizations.
        '';

        type = lib.types.path;
      };

      description = lib.mkOption {
        default = "";

        description = ''
          Description of the game that will appear in the listing.
        '';

        type = lib.types.nullOr lib.types.str;
      };

      extraArgs = lib.mkOption {
        default = [ ];
        description = "Extra command line arguments.";

        example = [
          "--rcon-bind=localhost:27015"
          "--rcon-password=..."
        ];

        type = lib.types.listOf lib.types.str;
      };

      extraSettings = lib.mkOption {
        default = { };

        description = ''
          Extra game configuration that will go into server-settings.json
        '';

        example = {
          max_players = 64;
        };

        type = lib.types.attrs;
      };

      extraSettingsFile = lib.mkOption {
        default = null;

        description = ''
          File, which is dynamically applied to server-settings.json before
          startup.

          This option should be used for credentials.

          For example a settings file could contain:
          ```json
          {
            "game-password": "hunter1"
          }
          ```
        '';

        type = lib.types.nullOr lib.types.path;
      };

      game-name = lib.mkOption {
        default = "Factorio Game";

        description = ''
          Name of the game as it will appear in the game listing.
        '';

        type = lib.types.nullOr lib.types.str;
      };

      game-password = lib.mkOption {
        default = null;

        description = ''
          Game password.

          This option is insecure. Use extraSettingsFile instead.
        '';

        type = lib.types.nullOr lib.types.str;
      };

      lan = lib.mkOption {
        default = false;

        description = ''
          Game will be broadcast on LAN.
        '';

        type = lib.types.bool;
      };

      loadLatestSave = lib.mkOption {
        default = false;

        description = ''
          Load the latest savegame on startup. This overrides saveName, in that the latest
          save will always be used even if a saved game of the given name exists. It still
          controls the 'canonical' name of the savegame.

          Set this to true to have the server automatically reload a recent autosave after
          a crash or desync.
        '';

        type = lib.types.bool;
      };

      mods = lib.mkOption {
        default = [ ];

        description = ''
          Mods the server should install and activate.

          The derivations in this list must "build" the mod by simply copying
          the .zip, named correctly, into the output directory. Eventually,
          there will be a way to pull in the most up-to-date list of
          derivations via nixos-channel. Until then, this is for experts only.
        '';

        type = lib.types.listOf lib.types.package;
      };

      mods-dat = lib.mkOption {
        default = null;

        description = ''
          Mods settings can be changed by specifying a dat file, in the [mod
          settings file
          format](https://wiki.factorio.com/Mod_settings_file_format).
        '';

        type = lib.types.nullOr lib.types.path;
      };

      nonBlockingSaving = lib.mkOption {
        default = false;

        description = ''
          Highly experimental feature, enable only at your own risk of losing your saves.
          On UNIX systems, server will fork itself to create an autosave.
          Autosaving on connected Windows clients will be disabled regardless of autosave_only_on_server option.
        '';

        type = lib.types.bool;
      };

      openFirewall = lib.mkOption {
        default = false;

        description = ''
          Whether to automatically open the specified UDP port in the firewall.
        '';

        type = lib.types.bool;
      };

      password = lib.mkOption {
        default = null;

        description = ''
          Your factorio.com login credentials. Required for games with visibility public.

          This option is insecure. Use extraSettingsFile instead.
        '';

        type = lib.types.nullOr lib.types.str;
      };

      port = lib.mkOption {
        default = 34197;

        description = ''
          The port to which the service should bind.
        '';

        type = lib.types.port;
      };

      public = lib.mkOption {
        default = false;

        description = ''
          Game will be published on the official Factorio matching server.
        '';

        type = lib.types.bool;
      };

      requireUserVerification = lib.mkOption {
        default = true;

        description = ''
          When set to true, the server will only allow clients that have a valid factorio.com account.
        '';

        type = lib.types.bool;
      };

      saveName = lib.mkOption {
        default = "default";

        description = ''
          The name of the savegame that will be used by the server.

          When not present in /var/lib/''${config.services.factorio.stateDirName}/saves,
          a new map with default settings will be generated before starting the service.
        '';

        type = lib.types.str;
      };

      stateDirName = lib.mkOption {
        default = "factorio";

        description = ''
          Name of the directory under /var/lib holding the server's data.

          The configuration and map will be stored here.
        '';

        type = lib.types.str;
      };

      token = lib.mkOption {
        default = null;

        description = ''
          Authentication token. May be used instead of 'password' above.
        '';

        type = lib.types.nullOr lib.types.str;
      };

      username = lib.mkOption {
        default = null;

        description = ''
          Your factorio.com login credentials. Required for games with visibility public.

          This option is insecure. Use extraSettingsFile instead.
        '';

        type = lib.types.nullOr lib.types.str;
      };
    };
  };

  config = lib.mkIf cfg.enable {
    networking.firewall.allowedUDPPorts = lib.optional cfg.openFirewall cfg.port;

    systemd.services.factorio = {
      after = [ "network.target" ];
      description = "Factorio headless server";

      preStart =
        (toString [
          "test -e ${stateDir}/saves/${cfg.saveName}.zip"
          "||"
          "${cfg.package}/bin/factorio"
          "--config=${cfg.configFile}"
          "--create=${mkSavePath cfg.saveName}"
          (lib.optionalString (cfg.mods != [ ]) "--mod-directory=${modDir}")
        ])
        + (lib.optionalString (cfg.extraSettingsFile != null) (
          "\necho ${lib.strings.escapeShellArg serverSettingsString}"
          + " \"$(cat ${cfg.extraSettingsFile})\" | ${lib.getExe pkgs.jq} -s add"
          + " > ${stateDir}/server-settings.json"
        ));

      serviceConfig = {
        DynamicUser = true;

        ExecStart = toString [
          "${cfg.package}/bin/factorio"
          "--config=${cfg.configFile}"
          "--port=${toString cfg.port}"
          "--bind=${cfg.bind}"
          (lib.optionalString (!cfg.loadLatestSave) "--start-server=${mkSavePath cfg.saveName}")
          "--server-settings=${
            if (cfg.extraSettingsFile != null) then "${stateDir}/server-settings.json" else serverSettingsFile
          }"
          (lib.optionalString cfg.loadLatestSave "--start-server-load-latest")
          (lib.optionalString (cfg.mods != [ ]) "--mod-directory=${modDir}")
          (playerListOption "server-adminlist" cfg.admins)
          (playerListOption "server-whitelist" cfg.allowedPlayers)
          (lib.optionalString (cfg.allowedPlayers != [ ]) "--use-server-whitelist")
          cfg.extraArgs
        ];

        KillSignal = "SIGINT";
        MemoryDenyWriteExecute = true;
        # Sandboxing
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateTmp = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectSystem = "strict";
        Restart = "always";

        RestrictAddressFamilies = [
          "AF_UNIX"
          "AF_INET"
          "AF_INET6"
          "AF_NETLINK"
        ];

        RestrictNamespaces = true;
        RestrictRealtime = true;
        StateDirectory = cfg.stateDirName;
        UMask = "0007";
      };

      wantedBy = [ "multi-user.target" ];
    };
  };
}
