{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let

  inherit (pkgs) nntp-proxy;

  cfg = config.services.nntp-proxy;

  configBool = b: if b then "TRUE" else "FALSE";

  confFile = pkgs.writeText "nntp-proxy.conf" ''
    nntp_server:
    {
      # NNTP Server host and port address
      server = "${cfg.upstreamServer}";
      port = ${toString cfg.upstreamPort};
      # NNTP username
      username = "${cfg.upstreamUser}";
      # NNTP password in clear text
      password = "${cfg.upstreamPassword}";
      # Maximum number of connections allowed by the NNTP
      max_connections = ${toString cfg.upstreamMaxConnections};
    };

    proxy:
    {
      # Local address and port to bind to
      bind_ip = "${cfg.listenAddress}";
      bind_port = ${toString cfg.port};

      # SSL key and cert file
      ssl_key = "${cfg.sslKey}";
      ssl_cert = "${cfg.sslCert}";

      # prohibit users from posting
      prohibit_posting = ${configBool cfg.prohibitPosting};
      # Verbose levels: ERROR, WARNING, NOTICE, INFO, DEBUG
      verbose = "${toUpper cfg.verbosity}";
      # Password is made with: 'mkpasswd -m sha-512 <password>'
      users = (${
        concatStringsSep ",\n" (
          mapAttrsToList (username: userConfig: ''
            {
                username = "${username}";
                password = "${userConfig.passwordHash}";
                max_connections = ${toString userConfig.maxConnections};
            }
          '') cfg.users
        )
      });
    };
  '';

in

{

  ###### interface

  options = {

    services.nntp-proxy = {
      enable = mkEnableOption "NNTP-Proxy";

      listenAddress = mkOption {
        default = "127.0.0.1";

        description = ''
          Proxy listen address (IPv6 literal addresses need to be enclosed in "[" and "]" characters)
        '';

        example = "[::]";
        type = types.str;
      };

      port = mkOption {
        default = 5555;

        description = ''
          Proxy listen port
        '';

        type = types.port;
      };

      prohibitPosting = mkOption {
        default = true;

        description = ''
          Whether to prohibit posting to the upstream server
        '';

        type = types.bool;
      };

      sslCert = mkOption {
        default = "cert.pem";

        description = ''
          Proxy ssl certificate path
        '';

        example = "/path/to/your/cert.file";
        type = types.str;
      };

      sslKey = mkOption {
        default = "key.pem";

        description = ''
          Proxy ssl key path
        '';

        example = "/path/to/your/key.file";
        type = types.str;
      };

      upstreamMaxConnections = mkOption {
        default = 20;

        description = ''
          Upstream server maximum allowed concurrent connections
        '';

        type = types.int;
      };

      upstreamPassword = mkOption {
        default = "";

        description = ''
          Upstream server password
        '';

        type = types.str;
      };

      upstreamPort = mkOption {
        default = 563;

        description = ''
          Upstream server port
        '';

        type = types.port;
      };

      upstreamServer = mkOption {
        default = "";

        description = ''
          Upstream server address
        '';

        example = "ssl-eu.astraweb.com";
        type = types.str;
      };

      upstreamUser = mkOption {
        default = "";

        description = ''
          Upstream server username
        '';

        type = types.str;
      };

      users = mkOption {
        default = { };

        description = ''
          NNTP-Proxy user configuration
        '';

        example = literalExpression ''
          {
            "user1" = {
              passwordHash = "$6$1l0t5Kn2Dk$appzivc./9l/kjq57eg5UCsBKlcfyCr0zNWYNerKoPsI1d7eAwiT0SVsOVx/CTgaBNT/u4fi2vN.iGlPfv1ek0";
              maxConnections = 5;
            };
            "anotheruser" = {
              passwordHash = "$6$6lwEsWB.TmsS$W7m1riUx4QrA8pKJz8hvff0dnF1NwtZXgdjmGqA1Dx2MDPj07tI9GNcb0SWlMglE.2/hBgynDdAd/XqqtRqVQ0";
              maxConnections = 7;
            };
          }
        '';

        type = types.attrsOf (
          types.submodule {
            options = {
              maxConnections = mkOption {
                default = 1;

                description = ''
                  Maximum number of concurrent connections to the proxy for this user
                '';

                type = types.int;
              };

              passwordHash = mkOption {
                description = ''
                  SHA-512 password hash (can be generated by
                  `mkpasswd -m sha-512 <password>`)
                '';

                example = "$6$GtzE7FrpE$wwuVgFYU.TZH4Rz.Snjxk9XGua89IeVwPQ/fEUD8eujr40q5Y021yhn0aNcsQ2Ifw.BLclyzvzgegopgKcneL0";
                type = types.str;
              };

              username = mkOption {
                description = ''
                  Username
                '';

                type = types.str;
              };
            };
          }
        );
      };

      verbosity = mkOption {
        default = "info";

        description = ''
          Verbosity level
        '';

        example = "error";

        type = types.enum [
          "error"
          "warning"
          "notice"
          "info"
          "debug"
        ];
      };
    };

  };

  ###### implementation

  config = mkIf cfg.enable {

    systemd.services.nntp-proxy = {
      after = [
        "network.target"
        "nss-lookup.target"
      ];

      description = "NNTP proxy";

      preStart = ''
        if [ ! \( -f ${cfg.sslCert} -a -f ${cfg.sslKey} \) ]; then
          ${pkgs.openssl.bin}/bin/openssl req -subj '/CN=AutoGeneratedCert/O=NixOS Service/C=US' \
          -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout ${cfg.sslKey} -out ${cfg.sslCert};
        fi
      '';

      serviceConfig = {
        User = "nntp-proxy";
      };

      serviceConfig.ExecStart = "${nntp-proxy}/bin/nntp-proxy ${confFile}";
      wantedBy = [ "multi-user.target" ];
    };

    users.groups.nntp-proxy = { };

    users.users.nntp-proxy = {
      description = "NNTP-Proxy daemon user";
      group = "nntp-proxy";
      isSystemUser = true;
    };

  };

}
