{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.services.supybot;
  isStateDirHome = hasPrefix "/home/" cfg.stateDir;
  isStateDirVar = cfg.stateDir == "/var/lib/supybot";
  pyEnv = pkgs.python3.withPackages (p: [ p.limnoria ] ++ (cfg.extraPackages p));
in
{
  options = {

    services.supybot = {

      enable = mkOption {
        default = false;
        description = "Enable Supybot, an IRC bot (also known as Limnoria).";
        type = types.bool;
      };

      configFile = mkOption {
        description = ''
          Path to initial supybot config file. This can be generated by
          running supybot-wizard.

          Note: all paths should include the full path to the stateDir
          directory (backup conf data logs logs/plugins plugins tmp web).
        '';

        type = types.path;
      };

      extraPackages = mkOption {
        default = p: [ ];
        defaultText = literalExpression "p: []";

        description = ''
          Extra Python packages available to supybot plugins. The
          value must be a function which receives the attrset defined
          in {var}`python3Packages` as the sole argument.
        '';

        example = literalExpression "p: [ p.lxml p.requests ]";
        type = types.functionTo (types.listOf types.package);
      };

      plugins = mkOption {
        default = { };

        description = ''
          Attribute set of additional plugins that will be symlinked to the
          {file}`plugin` subdirectory.

          Please note that you still need to add the plugins to the config
          file (or with `!load`) using their attribute name.
        '';

        example = literalExpression ''
          let
            plugins = pkgs.fetchzip {
              url = "https://github.com/ProgVal/Supybot-plugins/archive/57c2450c.zip";
              sha256 = "077snf84ibnva3sbpzdfpfma6hcdw7dflwnhg6pw7mgnf0nd84qd";
            };
          in
          {
            Wikipedia = "''${plugins}/Wikipedia";
            Decide = ./supy-decide;
          }
        '';

        type = types.attrsOf types.path;
      };

      stateDir = mkOption {
        default =
          if versionAtLeast config.system.stateVersion "20.09" then "/var/lib/supybot" else "/home/supybot";

        defaultText = literalExpression "/var/lib/supybot";
        description = "The root directory, logs and plugins are stored here";
        type = types.path;
      };

    };

  };

  config = mkIf cfg.enable {

    environment.systemPackages = [ pkgs.python3Packages.limnoria ];

    systemd.services.supybot = {
      after = [ "network.target" ];
      description = "Supybot, an IRC bot";
      documentation = [ "https://limnoria.readthedocs.io/" ];

      preStart = ''
        # This needs to be created afresh every time
        rm -f '${cfg.stateDir}/supybot.cfg.bak'
      '';

      serviceConfig = {
        CapabilityBoundingSet = "";
        ExecStart = "${pyEnv}/bin/supybot ${cfg.stateDir}/supybot.cfg";
        Group = "supybot";
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        NoNewPrivileges = true;
        PIDFile = "/run/supybot.pid";
        PrivateDevices = true;
        PrivateMounts = true;
        PrivateTmp = true;
        ProtectControlGroups = true;
        ProtectHostname = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectSystem = "full";
        RemoveIPC = true;
        Restart = "on-abort";

        RestrictAddressFamilies = [
          "AF_INET"
          "AF_INET6"
        ];

        RestrictNamespaces = true;
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        SystemCallArchitectures = "native";
        UMask = "0007";
        User = "supybot";
      }
      // optionalAttrs isStateDirVar {
        ProtectSystem = "strict";
        StateDirectory = "supybot";
      }
      // optionalAttrs (!isStateDirHome) {
        ProtectHome = true;
      };

      startLimitBurst = 1;
      startLimitIntervalSec = 5 * 60; # 5 min
      wantedBy = [ "multi-user.target" ];
    };

    systemd.tmpfiles.rules = [
      "d '${cfg.stateDir}'              0700 supybot supybot - -"
      "d '${cfg.stateDir}/backup'       0750 supybot supybot - -"
      "d '${cfg.stateDir}/conf'         0750 supybot supybot - -"
      "d '${cfg.stateDir}/data'         0750 supybot supybot - -"
      "d '${cfg.stateDir}/plugins'      0750 supybot supybot - -"
      "d '${cfg.stateDir}/logs'         0750 supybot supybot - -"
      "d '${cfg.stateDir}/logs/plugins' 0750 supybot supybot - -"
      "d '${cfg.stateDir}/tmp'          0750 supybot supybot - -"
      "d '${cfg.stateDir}/web'          0750 supybot supybot - -"
      "L '${cfg.stateDir}/supybot.cfg'  -    -       -       - ${cfg.configFile}"
    ]
    ++ (flip mapAttrsToList cfg.plugins (
      name: dest: "L+ '${cfg.stateDir}/plugins/${name}' - - - - ${dest}"
    ));

    users.groups.supybot = {
      gid = config.ids.gids.supybot;
    };

    users.users.supybot = {
      description = "Supybot IRC bot user";
      group = "supybot";
      home = cfg.stateDir;
      isSystemUser = true;
      uid = config.ids.uids.supybot;
    };

  };
}
