# CABAL2NIX AUTOGENERATED THIS FILE.
{
  lib,
  ansi-terminal,
  base,
  containers,
  directory,
  fetchgit,
  filepath,
  hs-highlight,
  mkDerivation,
  mtl,
  parsec,
}:
mkDerivation {
  pname = "kind-lang";
  version = "0.1.0.0";

  src = fetchgit {
    url = "https://github.com/higherorderco/kind.git";
    rev = "5cfff210b3aeed01ebd73b2364cf9e5d2df658af";
    sha256 = "1g4pikxh42p3hikzyfzf11cs7zd1miaxapyf8pijdcxhpdx7wwl0";
    fetchSubmodules = false;
  };

  executableHaskellDepends = [
    ansi-terminal
    base
    directory
    filepath
    hs-highlight
    mtl
  ];

  isExecutable = true;
  isLibrary = true;

  libraryHaskellDepends = [
    ansi-terminal
    base
    containers
    directory
    filepath
    hs-highlight
    mtl
    parsec
  ];

  license = lib.licenses.mit;
  mainProgram = "kind";
}
