{
  lib,
  stdenv,
  fetchurl,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

stdenv.mkDerivation (finalAttrs: {
  pname = "lzip";
  version = "1.26";

  src = fetchurl {
    url = "mirror://savannah/lzip/lzip-${finalAttrs.version}.tar.gz";
    hash = "sha256-ZBzzCWFSXL47NAzIg0NsiFTp9QMvRZ9ETeR4K2IeZXI=";
  };

  outputs = [
    "out"
    "man"
    "info"
  ];

  patches = lib.optionals stdenv.hostPlatform.isMinGW [
    ./mingw-install-exe-file.patch
  ];

  strictDeps = true;

  configureFlags = [
    "CPPFLAGS=-DNDEBUG"
    "CFLAGS=-O3"
    "CXXFLAGS=-O3"
    "CXX=${stdenv.cc.targetPrefix}c++"
  ];

  doCheck = true;
  enableParallelBuilding = true;
  setupHook = ./lzip-setup-hook.sh;

  meta = {
    description = "Lossless data compressor based on the LZMA algorithm";
    homepage = "https://www.nongnu.org/lzip/lzip.html";
    license = lib.licenses.gpl2Plus;
    maintainers = with lib.maintainers; [ vlaci ];
    platforms = lib.platforms.all;
    mainProgram = "lzip";
  };
})
