{
  lib,
  fetchFromGitHub,
  buildPgrxExtension,
  cargo-pgrx_0_16_1,
  postgresql,
  postgresqlTestExtension,
}:

buildPgrxExtension (finalAttrs: {
  inherit postgresql;
  pname = "pgvectorscale";
  version = "0.9.0";

  src = fetchFromGitHub {
    owner = "timescale";
    repo = "pgvectorscale";
    tag = finalAttrs.version;
    hash = "sha256-whGTJI73wifYkleC+aAbDV4nhwls3uFs1xKcB0zLDRo=";
  };

  cargoHash = "sha256-uaRKUtsUdZPcrQLAixCiEphXQqdsRhi8nSfh9b3w0ao=";
  doCheck = false;
  cargo-pgrx = cargo-pgrx_0_16_1;

  cargoPatches = [
    ./add-Cargo.lock.patch
  ];

  cargoPgrxFlags = [
    "-p"
    "vectorscale"
  ];

  passthru.tests.extension = postgresqlTestExtension {
    inherit (finalAttrs) finalPackage;

    asserts = [
      {
        description = "Expected vector of row with ID=10 to have an euclidean distance from [1,2,3] of 1.";
        expected = "10";
        query = "SELECT id FROM document_embedding WHERE embedding <-> '[1,2,3]' = 1";
      }
      {
        description = "Expected vector of row with ID=20 to have an euclidean distance from [1,2,3] of 2.";
        expected = "20";
        query = "SELECT id FROM document_embedding WHERE embedding <-> '[1,2,3]' = 2";
      }
    ];

    sql = ''
      CREATE EXTENSION vectorscale CASCADE;
      CREATE TABLE document_embedding  (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          embedding VECTOR(3)
      );

      INSERT INTO document_embedding (id, embedding) VALUES
      (10, '[1,2,4]'),
      (20, '[1,2,5]');

      CREATE INDEX document_embedding_idx ON document_embedding
      USING diskann (embedding vector_cosine_ops);
    '';

    withPackages = [ "pgvector" ];
  };

  meta = {
    description = "Complement to pgvector for high performance, cost efficient vector search on large workloads";
    homepage = "https://github.com/timescale/pgvectorscale";
    changelog = "https://github.com/timescale/pgvectorscale/releases/tag/${finalAttrs.version}";
    license = lib.licenses.postgresql;

    maintainers = [
      lib.maintainers.leona
      lib.maintainers.osnyx
    ];

    platforms = postgresql.meta.platforms;
    # Upstream removed support for PostgreSQL 13 on 0.9.0: https://github.com/timescale/pgvectorscale/releases/tag/0.9.0
    broken = lib.versionOlder postgresql.version "14";
  };
})
