{
  lib,
  stdenv,
  fetchurl,
  gettext,
  libintl,
  perlPackages,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

stdenv.mkDerivation (finalAttrs: {
  pname = "help2man";
  version = "1.49.3";

  src = fetchurl {
    url = "mirror://gnu/help2man/help2man-${finalAttrs.version}.tar.xz";
    sha256 = "sha256-TX5P3vLspq/geiaCFRzqeHgeCk6PliIULZ9wwIOi/U8=";
  };

  patches = lib.optional stdenv.hostPlatform.isCygwin ./1.40.4-cygwin-nls.patch;
  strictDeps = true;

  nativeBuildInputs = [
    gettext
    perlPackages.perl
    perlPackages.LocaleGettext
  ];

  buildInputs = [
    perlPackages.LocaleGettext
    libintl
  ];

  configureFlags = [
    "--enable-nls"
  ];

  doCheck = false; # target `check' is missing

  # We don't use makeWrapper here because it uses substitutions our
  # bootstrap shell can't handle.
  postInstall = ''
    mv $out/bin/help2man $out/bin/.help2man-wrapped
    cat > $out/bin/help2man <<EOF
    #! $SHELL -e
    export PERL5LIB=\''${PERL5LIB:+:}${perlPackages.LocaleGettext}/${perlPackages.perl.libPrefix}
    ${lib.optionalString stdenv.hostPlatform.isCygwin ''export PATH=\''${PATH:+:}${gettext}/bin''}
    exec -a \$0 $out/bin/.help2man-wrapped "\$@"
    EOF
    chmod +x $out/bin/help2man
  '';

  enableParallelBuilding = true;

  meta = {
    description = "Generate man pages from `--help' output";

    longDescription = ''
      help2man produces simple manual pages from the ‘--help’ and ‘--version’ output of other commands.
    '';

    homepage = "https://www.gnu.org/software/help2man/";
    license = lib.licenses.gpl3Plus;
    maintainers = with lib.maintainers; [ pSub ];
    platforms = lib.platforms.all;
    mainProgram = "help2man";
  };
})
