# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  fetchgit,
  fetchzip,
  linkFarm,
}:

linkFarm "zig-packages" [
  {
    name = "chameleon-2.0.1-ZOxajZ17AADmYCpHFqqoGfaXQiRkXM8B5lYJfir9tqsz";

    path = fetchgit {
      hash = "sha256-/TGzbVh+Z6dPEKtW0M0Tv1vXvc6jmb+kHf6Q0rHmEPE=";
      rev = "414169dede742d9ac8261d31b9fca6e31a1d7246";
      url = "https://github.com/tr1ckydev/chameleon";
    };
  }
  {
    name = "recover-1.3.0-Zd97opwlAAB5ocfOuy8Fxp7_prPehOuEnh0R_8rBsNCk";

    path = fetchzip {
      hash = "sha256-3x7ptCcmGjCop703ftS/KWuTlAdcCw431C8Q4VAdLIs=";
      url = "https://github.com/dimdin/zig-recover/archive/refs/tags/1.3.0.tar.gz";
    };
  }
  {
    name = "smart_pointers-0.0.4-NPos2JOtAACuxKEoBGQgkmncI0APAPl-QwaI6klLObuP";

    path = fetchzip {
      hash = "sha256-gSvAggi0qQgTd9avuqI9AspTGXr+w5ZkgNiI3kf0+dU=";
      url = "https://github.com/DonIsaac/smart-pointers/archive/refs/tags/v0.0.4.tar.gz";
    };
  }
]
