# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  fetchgit,
  fetchzip,
  linkFarm,
}:

linkFarm "zig-packages" [
  {
    name = "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX";

    path = fetchzip {
      hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.6.0.tar.gz";
    };
  }
  {
    name = "xkbcommon-0.3.0-VDqIe3K9AQB2fG5ZeRcMC9i7kfrp5m2rWgLrmdNn9azr";

    path = fetchzip {
      hash = "sha256-e5bPEfxl4SQf0cqccLt/py1KOW1+Q1+kWZUEXBbh9oQ=";
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.3.0.tar.gz";
    };
  }
]
