{
  lib,
  stdenv,
  fetchurl,
  haskellPackages,
  luaPackages,
  ocamlPackages,
  perlPackages,
  # for passthru.tests
  python3,
  testers,
  updateAutotoolsGnuConfigScriptsHook,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

let
  version = "2.8.2";
  tag = "R_${lib.replaceStrings [ "." ] [ "_" ] version}";
in
stdenv.mkDerivation (finalAttrs: {
  inherit version;
  pname = "expat";

  src = fetchurl {
    url =
      with finalAttrs;
      "https://github.com/libexpat/libexpat/releases/download/${tag}/${pname}-${version}.tar.xz";

    hash = "sha256-OtibhYjmZEvU5JmBSA1IshKJ7rvNTwoaSvscKfmbarQ=";
  };

  outputs = [
    "out"
    "dev"
  ]; # TODO: fix referrers

  strictDeps = true;
  nativeBuildInputs = [ updateAutotoolsGnuConfigScriptsHook ];
  configureFlags = lib.optional stdenv.hostPlatform.isFreeBSD "--with-pic";
  doCheck = true; # not cross;

  preCheck = ''
    patchShebangs ./run.sh ./test-driver-wrapper.sh
  '';

  # CMake files incorrectly calculate library path from dev prefix
  # https://github.com/libexpat/libexpat/issues/501
  postFixup = ''
    substituteInPlace $dev/lib/cmake/expat-${finalAttrs.version}/expat-noconfig.cmake \
      --replace "$"'{_IMPORT_PREFIX}' $out
  '';

  enableParallelBuilding = true;
  outputBin = "dev";
  outputMan = "dev"; # tiny page for a dev tool

  passthru.tests = {
    inherit python3;
    inherit (python3.pkgs) xmltodict;
    inherit (haskellPackages) hexpat;
    inherit (perlPackages) XMLSAXExpat XMLParser;
    inherit (luaPackages) luaexpat;
    inherit (ocamlPackages) ocaml_expat;

    pkg-config = testers.hasPkgConfigModules {
      package = finalAttrs.finalPackage;
    };
  };

  meta = {
    description = "Stream-oriented XML parser library written in C";
    homepage = "https://libexpat.github.io/";
    changelog = "https://github.com/libexpat/libexpat/blob/${tag}/expat/Changes";
    license = lib.licenses.mit; # expat version
    platforms = lib.platforms.all;
    mainProgram = "xmlwf";
    pkgConfigModules = [ "expat" ];
  };
})
