# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ fetchzip, linkFarm }:

linkFarm "zig-packages" [
  {
    name = "clap-0.12.0-oBajB7foAQDqlSwaSG5g0yq7xGbQARUsBk5T64gAOqP5";

    path = fetchzip {
      hash = "sha256-HveL7aJBC+/8PNlGYxtNZBrk3ytkM8zuXENO9JpygC0=";
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.12.0.tar.gz";
    };
  }
]
