{
  config,
  lib,
  pkgs,
  utils,
  ...
}:
let
  cfg = config.services.kanata;

  upstreamDoc = "See [the upstream documentation](https://github.com/jtroo/kanata/blob/main/docs/config.adoc) and [example config files](https://github.com/jtroo/kanata/tree/main/cfg_samples) for more information.";

  keyboard =
    { config, name, ... }:
    {
      options = {
        config = lib.mkOption {
          description = ''
            Configuration other than `defcfg`.

            ${upstreamDoc}
          '';

          example = ''
            (defsrc
              caps)

            (deflayermap (default-layer)
              ;; tap caps lock as caps lock, hold caps lock as left control
              caps (tap-hold 100 100 caps lctl))
          '';

          type = lib.types.lines;
        };

        configFile = lib.mkOption {
          default = mkConfig name config;
          defaultText = "A config file generated by values from other kanata module options.";

          description = ''
            The config file.

            By default, it is generated by values from other kanata
            module options.

            You can also set it to your own full config file which
            overrides all other kanata module options.  ${upstreamDoc}
          '';

          type = lib.types.path;
        };

        devices = lib.mkOption {
          default = [ ];

          description = ''
            Paths to keyboard devices.

            An empty list, the default value, lets kanata detect which
            input devices are keyboards and intercept them all.
          '';

          example = [ "/dev/input/by-id/usb-0000_0000-event-kbd" ];
          type = lib.types.listOf lib.types.str;
        };

        extraArgs = lib.mkOption {
          default = [ ];
          description = "Extra command line arguments passed to kanata.";
          type = lib.types.listOf lib.types.str;
        };

        extraDefCfg = lib.mkOption {
          default = "";

          description = ''
            Configuration of `defcfg` other than `linux-dev` (generated
            from the devices option) and
            `linux-continue-if-no-devs-found` (hardcoded to be yes).

            ${upstreamDoc}
          '';

          example = "danger-enable-cmd yes";
          type = lib.types.lines;
        };

        port = lib.mkOption {
          default = null;

          description = ''
            Port to run the TCP server on. `null` will not run the server.
          '';

          example = 6666;
          type = lib.types.nullOr lib.types.port;
        };
      };
    };

  mkName = name: "kanata-${name}";

  mkDevices =
    devices:
    let
      devicesString = lib.pipe devices [
        (map (device: "\"" + device + "\""))
        (lib.concatStringsSep " ")
      ];
    in
    lib.optionalString ((lib.length devices) > 0) "linux-dev (${devicesString})";

  mkConfig =
    name: keyboard:
    pkgs.writeTextFile {
      # Only the config file generated by this module is checked.  A
      # user-provided one is not checked because it may not be available
      # at build time.  I think this is a good balance between module
      # complexity and functionality.
      checkPhase = ''
        ${lib.getExe cfg.package} --cfg "$target" --check --debug
      '';

      name = "${mkName name}-config.kdb";

      text = ''
        (defcfg
          ${keyboard.extraDefCfg}
          ${mkDevices keyboard.devices}
          linux-continue-if-no-devs-found yes)

        ${keyboard.config}
      '';
    };

  mkService =
    name: keyboard:
    lib.nameValuePair (mkName name) {
      serviceConfig = {
        CapabilityBoundingSet = [ "" ];

        # hardening
        DeviceAllow = [
          "/dev/uinput rw"
          "char-input r"
        ];

        DevicePolicy = "closed";
        DynamicUser = true;

        ExecStart = ''
          ${lib.getExe cfg.package} \
            --cfg ${keyboard.configFile} \
            --symlink-path ''${RUNTIME_DIRECTORY}/${name} \
            ${lib.optionalString (keyboard.port != null) "--port ${toString keyboard.port}"} \
            ${utils.escapeSystemdExecArgs keyboard.extraArgs}
        '';

        IPAddressAllow = lib.optional (keyboard.port != null) "localhost";
        IPAddressDeny = [ "any" ];
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        PrivateNetwork = keyboard.port == null;
        PrivateUsers = true;
        ProcSubset = "pid";
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectProc = "invisible";
        RestrictAddressFamilies = [ "AF_UNIX" ] ++ lib.optional (keyboard.port != null) "AF_INET";
        RestrictNamespaces = true;
        RestrictRealtime = true;
        RuntimeDirectory = mkName name;

        SupplementaryGroups = with config.users.groups; [
          input.name
          uinput.name
        ];

        SystemCallArchitectures = [ "native" ];

        SystemCallFilter = [
          "@system-service"
          "~@privileged"
          "~@resources"
        ];

        Type = "notify";
        UMask = "0077";
      };

      wantedBy = [ "multi-user.target" ];
    };
in
{
  options.services.kanata = {
    enable = lib.mkEnableOption "kanata, a tool to improve keyboard comfort and usability with advanced customization";

    package = lib.mkPackageOption pkgs "kanata" {
      example = [ "kanata-with-cmd" ];

      extraDescription = ''
        ::: {.note}
        If {option}`danger-enable-cmd` is enabled in any of the keyboards, the
        `kanata-with-cmd` package should be used.
        :::
      '';
    };

    keyboards = lib.mkOption {
      default = { };
      description = "Keyboard configurations.";
      type = lib.types.attrsOf (lib.types.submodule keyboard);
    };
  };

  config = lib.mkIf cfg.enable {
    hardware.uinput.enable = true;
    systemd.services = lib.mapAttrs' mkService cfg.keyboards;

    warnings =
      let
        keyboardsWithEmptyDevices = lib.filterAttrs (name: keyboard: keyboard.devices == [ ]) cfg.keyboards;
        existEmptyDevices = lib.length (lib.attrNames keyboardsWithEmptyDevices) > 0;
        moreThanOneKeyboard = lib.length (lib.attrNames cfg.keyboards) > 1;
      in
      lib.optional (existEmptyDevices && moreThanOneKeyboard)
        "One device can only be intercepted by one kanata instance.  Setting services.kanata.keyboards.${lib.head (lib.attrNames keyboardsWithEmptyDevices)}.devices = [ ] and using more than one services.kanata.keyboards may cause a race condition.";
  };

  meta.maintainers = with lib.maintainers; [ linj ];
}
