{
  lib,
  stdenv,
  fetchurl,
  glibcLocales,
  libiconv,
  pcre2,
  perl,
  runtimeShellPackage,
  updateAutotoolsGnuConfigScriptsHook,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

let
  version = "3.12";
in

stdenv.mkDerivation {
  inherit version;
  pname = "gnugrep";

  src = fetchurl {
    url = "mirror://gnu/grep/grep-${version}.tar.xz";
    hash = "sha256-JkmyfA6Q5jLq3NdXvgbG6aT0jZQd5R58D4P/dkCKB7k=";
  };

  outputs = [
    "out"
    "info"
  ]; # the man pages are rather small

  patches = [
    # Fixes test-float-h failure on ppc64 with C23
    # https://lists.gnu.org/archive/html/bug-gnulib/2025-07/msg00021.html
    # Multiple upstream commits squashed with adjustments, see header
    ./gnulib-float-h-tests-port-to-C23-PowerPC-GCC.patch
  ];

  # Some gnulib tests fail
  # - on Musl: https://github.com/NixOS/nixpkgs/pull/228714
  # - on x86_64-darwin: https://github.com/NixOS/nixpkgs/pull/228714#issuecomment-1576826330
  # - when building on Darwin (cross-compilation): test-nl_langinfo-mt fails
  postPatch =
    if stdenv.hostPlatform.isMusl || stdenv.buildPlatform.isDarwin then
      ''
        sed -i 's:gnulib-tests::g' Makefile.in
      ''
    else
      null;

  nativeBuildInputs = [ updateAutotoolsGnuConfigScriptsHook ];

  buildInputs = [
    pcre2
    libiconv
  ]
  ++ lib.optional (!stdenv.hostPlatform.isWindows) runtimeShellPackage;

  env = lib.optionalAttrs (stdenv.hostPlatform.isMinGW || stdenv.hostPlatform.isCygwin) {
    NIX_CFLAGS_COMPILE = "-Wno-error=format-security";
  };

  # On macOS, force use of mkdir -p, since Grep's fallback
  # (./install-sh) is broken.
  preConfigure = ''
    export MKDIR_P="mkdir -p"
  '';

  # cygwin: FAIL: multibyte-white-space
  # freebsd: FAIL mb-non-UTF8-performance
  # x86_64-darwin: fails 'stack-overflow' tests on Rosetta 2 emulator
  # aarch32: fails 'stack-overflow' when run on qemu under x86_64
  doCheck =
    !stdenv.hostPlatform.isCygwin
    && !stdenv.hostPlatform.isFreeBSD
    && !(stdenv.hostPlatform.isDarwin && stdenv.hostPlatform.isx86_64)
    && !stdenv.buildPlatform.isRiscV64
    && !stdenv.hostPlatform.isAarch32;

  nativeCheckInputs = [
    perl
    glibcLocales
  ];

  # Fix reference to sh in bootstrap-tools, and invoke grep via
  # absolute path rather than looking at argv[0].
  postInstall = ''
    rm $out/bin/egrep $out/bin/fgrep
    echo "#! /bin/sh" > $out/bin/egrep
    echo "exec $out/bin/grep -E \"\$@\"" >> $out/bin/egrep
    echo "#! /bin/sh" > $out/bin/fgrep
    echo "exec $out/bin/grep -F \"\$@\"" >> $out/bin/fgrep
    chmod +x $out/bin/egrep $out/bin/fgrep
  '';

  enableParallelBuilding = true;

  passthru = {
    inherit pcre2;
  };

  meta = {
    description = "GNU implementation of the Unix grep command";

    longDescription = ''
      The grep command searches one or more input files for lines
      containing a match to a specified pattern.  By default, grep
      prints the matching lines.
    '';

    homepage = "https://www.gnu.org/software/grep/";
    license = lib.licenses.gpl3Plus;

    maintainers = [
      lib.maintainers.das_j
      lib.maintainers.m00wl
    ];

    platforms = lib.platforms.all;
    mainProgram = "grep";

    identifiers.cpeParts = lib.meta.cpeFullVersionWithVendor "gnu" version // {
      product = "grep";
    };

    teams = [ lib.teams.security-review ];
  };
}
