# Warning: generated by update-providers.py, do not update manually
{
  airbyte = {
    version = "5.5.1";
    deps = [ "requests" ];

    imports = [
      "airflow.providers.airbyte"
      "airflow.providers.airbyte.get_provider_info"
    ];
  };

  akeyless = {
    version = "0.2.0";
    deps = [ ];

    imports = [
      "airflow.providers.akeyless"
      "airflow.providers.akeyless.get_provider_info"
    ];
  };

  alibaba = {
    version = "3.3.9";
    deps = [ "alibabacloud-tea-openapi" ];

    imports = [
      "airflow.providers.alibaba"
      "airflow.providers.alibaba.get_provider_info"
    ];
  };

  amazon = {
    version = "9.31.0";

    deps = [
      "aiobotocore"
      "asgiref"
      "boto3"
      "botocore"
      "inflection"
      "jmespath"
      "jsonpath-ng"
      "lxml"
      "marshmallow"
      "pandas"
      "pyathena"
      "python3-saml"
      "redshift-connector"
      "s3fs"
      "sqlalchemy"
      "xmlsec"
    ];

    imports = [
      "airflow.providers.amazon"
      "airflow.providers.amazon.get_provider_info"
    ];
  };

  apache_beam = {
    version = "6.2.3";

    deps = [
      "apache-beam"
      "numpy"
      "pyarrow"
    ];

    imports = [
      "airflow.providers.apache.beam"
      "airflow.providers.apache.beam.get_provider_info"
    ];
  };

  apache_cassandra = {
    version = "3.9.5";
    deps = [ "cassandra-driver" ];

    imports = [
      "airflow.providers.apache.cassandra"
      "airflow.providers.apache.cassandra.get_provider_info"
    ];
  };

  apache_drill = {
    version = "3.3.3";
    deps = [ ];

    imports = [
      "airflow.providers.apache.drill"
      "airflow.providers.apache.drill.get_provider_info"
    ];
  };

  apache_druid = {
    version = "4.5.2";
    deps = [ "pydruid" ];

    imports = [
      "airflow.providers.apache.druid"
      "airflow.providers.apache.druid.get_provider_info"
    ];
  };

  apache_flink = {
    version = "1.8.5";
    deps = [ "cryptography" ];

    imports = [
      "airflow.providers.apache.flink"
      "airflow.providers.apache.flink.get_provider_info"
    ];
  };

  apache_hdfs = {
    version = "4.12.1";

    deps = [
      "fastavro"
      "hdfs"
      "pandas"
    ];

    imports = [
      "airflow.providers.apache.hdfs"
      "airflow.providers.apache.hdfs.get_provider_info"
    ];
  };

  apache_hive = {
    version = "9.5.0";

    deps = [
      "jmespath"
      "kerberos"
      "pandas"
      "sqlalchemy"
    ];

    imports = [
      "airflow.providers.apache.hive"
      "airflow.providers.apache.hive.get_provider_info"
    ];
  };

  apache_iceberg = {
    version = "2.0.3";
    deps = [ "pyiceberg" ];

    imports = [
      "airflow.providers.apache.iceberg"
      "airflow.providers.apache.iceberg.get_provider_info"
    ];
  };

  apache_impala = {
    version = "1.9.3";

    deps = [
      "kerberos"
      "sqlalchemy"
    ];

    imports = [
      "airflow.providers.apache.impala"
      "airflow.providers.apache.impala.get_provider_info"
    ];
  };

  apache_kafka = {
    version = "1.14.0";

    deps = [
      "asgiref"
      "confluent-kafka"
    ];

    imports = [
      "airflow.providers.apache.kafka"
      "airflow.providers.apache.kafka.get_provider_info"
    ];
  };

  apache_kylin = {
    version = "3.10.5";
    deps = [ ];

    imports = [
      "airflow.providers.apache.kylin"
      "airflow.providers.apache.kylin.get_provider_info"
    ];
  };

  apache_livy = {
    version = "4.5.7";
    deps = [ "aiohttp" ];

    imports = [
      "airflow.providers.apache.livy"
      "airflow.providers.apache.livy.get_provider_info"
    ];
  };

  apache_pig = {
    version = "4.8.5";
    deps = [ ];

    imports = [
      "airflow.providers.apache.pig"
      "airflow.providers.apache.pig.get_provider_info"
    ];
  };

  apache_pinot = {
    version = "4.10.3";
    deps = [ ];

    imports = [
      "airflow.providers.apache.pinot"
      "airflow.providers.apache.pinot.get_provider_info"
    ];
  };

  apache_spark = {
    version = "6.2.0";

    deps = [
      "grpcio-status"
      "pyspark"
      "requests"
      "tenacity"
    ];

    imports = [
      "airflow.providers.apache.spark"
      "airflow.providers.apache.spark.get_provider_info"
    ];
  };

  apache_tinkerpop = {
    version = "1.1.4";
    deps = [ "gremlinpython" ];

    imports = [
      "airflow.providers.apache.tinkerpop"
      "airflow.providers.apache.tinkerpop.get_provider_info"
    ];
  };

  apprise = {
    version = "2.3.4";
    deps = [ "apprise" ];

    imports = [
      "airflow.providers.apprise"
      "airflow.providers.apprise.get_provider_info"
    ];
  };

  arangodb = {
    version = "2.9.5";
    deps = [ "python-arango" ];

    imports = [
      "airflow.providers.arangodb"
      "airflow.providers.arangodb.get_provider_info"
    ];
  };

  asana = {
    version = "2.11.4";
    deps = [ "asana" ];

    imports = [
      "airflow.providers.asana"
      "airflow.providers.asana.get_provider_info"
    ];
  };

  atlassian_jira = {
    version = "3.3.4";
    deps = [ "atlassian-python-api" ];

    imports = [
      "airflow.providers.atlassian.jira"
      "airflow.providers.atlassian.jira.get_provider_info"
    ];
  };

  celery = {
    version = "3.20.0";

    deps = [
      "celery"
      "flower"
    ];

    imports = [
      "airflow.providers.celery"
      "airflow.providers.celery.get_provider_info"
    ];
  };

  clickhousedb = {
    version = "1.0.0";
    deps = [ "clickhouse-connect" ];

    imports = [
      "airflow.providers.clickhousedb"
      "airflow.providers.clickhousedb.get_provider_info"
    ];
  };

  cloudant = {
    version = "4.3.5";
    deps = [ ];

    imports = [
      "airflow.providers.cloudant"
      "airflow.providers.cloudant.get_provider_info"
    ];
  };

  cncf_kubernetes = {
    version = "10.18.1";

    deps = [
      "aiofiles"
      "asgiref"
      "cryptography"
      "kubernetes"
      "kubernetes-asyncio"
      "urllib3"
    ];

    imports = [
      "airflow.providers.cncf.kubernetes"
      "airflow.providers.cncf.kubernetes.get_provider_info"
    ];
  };

  cohere = {
    version = "1.6.6";

    deps = [
      "cohere"
      "fastavro"
    ];

    imports = [
      "airflow.providers.cohere"
      "airflow.providers.cohere.get_provider_info"
    ];
  };

  common_ai = {
    version = "0.5.0";

    deps = [
      "fastavro"
      "langchain"
      "llama-index-core"
      "llama-index-embeddings-openai"
      "llama-index-llms-openai"
      "pyarrow"
      "pydantic-ai-slim"
      "pypdf"
      "python-docx"
      "sqlglot"
    ];

    imports = [
      "airflow.providers.common.ai"
      "airflow.providers.common.ai.get_provider_info"
    ];
  };

  common_compat = {
    version = "1.15.0";
    deps = [ "asgiref" ];

    imports = [
      "airflow.providers.common.compat"
      "airflow.providers.common.compat.get_provider_info"
    ];
  };

  common_io = {
    version = "1.7.3";
    deps = [ ];

    imports = [
      "airflow.providers.common.io"
      "airflow.providers.common.io.get_provider_info"
    ];
  };

  common_messaging = {
    version = "2.0.4";
    deps = [ ];

    imports = [
      "airflow.providers.common.messaging"
      "airflow.providers.common.messaging.get_provider_info"
    ];
  };

  common_sql = {
    version = "2.0.1";

    deps = [
      "datafusion"
      "methodtools"
      "more-itertools"
      "pandas"
      "polars"
      "pyiceberg-core"
      "sqlalchemy"
      "sqlparse"
    ];

    imports = [
      "airflow.providers.common.sql"
      "airflow.providers.common.sql.get_provider_info"
    ];
  };

  databricks = {
    version = "7.16.1";

    deps = [
      "aiohttp"
      "azure-identity"
      "databricks-sdk"
      "databricks-sql-connector"
      "fastavro"
      "mergedeep"
      "pandas"
      "pyarrow"
      "requests"
    ];

    imports = [
      "airflow.providers.databricks"
      "airflow.providers.databricks.get_provider_info"
    ];
  };

  datadog = {
    version = "3.10.5";
    deps = [ "datadog" ];

    imports = [
      "airflow.providers.datadog"
      "airflow.providers.datadog.get_provider_info"
    ];
  };

  dbt_cloud = {
    version = "4.9.2";

    deps = [
      "aiohttp"
      "asgiref"
      "tenacity"
    ];

    imports = [
      "airflow.providers.dbt.cloud"
      "airflow.providers.dbt.cloud.get_provider_info"
    ];
  };

  dingding = {
    version = "3.9.5";
    deps = [ ];

    imports = [
      "airflow.providers.dingding"
      "airflow.providers.dingding.get_provider_info"
    ];
  };

  discord = {
    version = "3.12.3";
    deps = [ ];

    imports = [
      "airflow.providers.discord"
      "airflow.providers.discord.get_provider_info"
    ];
  };

  docker = {
    version = "4.5.7";

    deps = [
      "docker"
      "python-dotenv"
    ];

    imports = [
      "airflow.providers.docker"
      "airflow.providers.docker.get_provider_info"
    ];
  };

  edge3 = {
    version = "4.0.0";

    deps = [
      "aiofiles"
      "aiohttp"
      "pydantic"
      "retryhttp"
    ];

    imports = [
      "airflow.providers.edge3"
      "airflow.providers.edge3.get_provider_info"
    ];
  };

  elasticsearch = {
    version = "6.7.0";

    deps = [
      "elasticsearch"
      "polars"
    ];

    imports = [
      "airflow.providers.elasticsearch"
      "airflow.providers.elasticsearch.get_provider_info"
    ];
  };

  exasol = {
    version = "4.10.3";

    deps = [
      "pandas"
      "sqlalchemy"
    ];

    imports = [
      "airflow.providers.exasol"
      "airflow.providers.exasol.get_provider_info"
    ];
  };

  fab = {
    version = "3.7.0";

    deps = [
      "authlib"
      "blinker"
      "cachetools"
      "flask"
      "flask-appbuilder"
      "flask-limiter"
      "flask-login"
      "flask-session"
      "flask-sqlalchemy"
      "flask-wtf"
      "jmespath"
      "kerberos"
      "marshmallow"
      "msgpack"
      "pyjwt"
      "werkzeug"
      "wtforms"
    ];

    imports = [
      "airflow.providers.fab"
      "airflow.providers.fab.get_provider_info"
    ];
  };

  facebook = {
    version = "3.9.5";
    deps = [ ];

    imports = [
      "airflow.providers.facebook"
      "airflow.providers.facebook.get_provider_info"
    ];
  };

  ftp = {
    version = "3.15.1";
    deps = [ ];

    imports = [
      "airflow.providers.ftp"
      "airflow.providers.ftp.get_provider_info"
    ];
  };

  git = {
    version = "0.4.0";
    deps = [ "gitpython" ];

    imports = [
      "airflow.providers.git"
      "airflow.providers.git.get_provider_info"
    ];
  };

  github = {
    version = "2.11.3";
    deps = [ "pygithub" ];

    imports = [
      "airflow.providers.github"
      "airflow.providers.github.get_provider_info"
    ];
  };

  google = {
    version = "22.2.0";

    deps = [
      "asgiref"
      "dill"
      "gcsfs"
      "google-api-core"
      "google-api-python-client"
      "google-auth"
      "google-auth-httplib2"
      "google-cloud-automl"
      "google-cloud-bigquery"
      "google-cloud-bigquery-datatransfer"
      "google-cloud-bigquery-storage"
      "google-cloud-bigtable"
      "google-cloud-compute"
      "google-cloud-container"
      "google-cloud-datacatalog"
      "google-cloud-dataproc"
      "google-cloud-dlp"
      "google-cloud-kms"
      "google-cloud-language"
      "google-cloud-logging"
      "google-cloud-monitoring"
      "google-cloud-pubsub"
      "google-cloud-redis"
      "google-cloud-run"
      "google-cloud-secret-manager"
      "google-cloud-spanner"
      "google-cloud-speech"
      "google-cloud-storage"
      "google-cloud-tasks"
      "google-cloud-texttospeech"
      "google-cloud-translate"
      "google-cloud-videointelligence"
      "google-cloud-vision"
      "google-cloud-workflows"
      "grpcio-gcp"
      "httpx"
      "immutabledict"
      "pandas"
      "plyvel"
      "proto-plus"
      "pyarrow"
      "pydantic"
      "python-slugify"
      "ray"
      "tenacity"
      "types-protobuf"
    ];

    imports = [
      "airflow.providers.google"
      "airflow.providers.google.get_provider_info"
    ];
  };

  grpc = {
    version = "3.9.5";

    deps = [
      "google-auth"
      "google-auth-httplib2"
      "grpcio"
    ];

    imports = [
      "airflow.providers.grpc"
      "airflow.providers.grpc.get_provider_info"
    ];
  };

  hashicorp = {
    version = "4.7.1";

    deps = [
      "boto3"
      "hvac"
    ];

    imports = [
      "airflow.providers.hashicorp"
      "airflow.providers.hashicorp.get_provider_info"
    ];
  };

  http = {
    version = "6.0.4";

    deps = [
      "aiohttp"
      "asgiref"
      "pydantic"
      "requests"
      "requests-toolbelt"
    ];

    imports = [
      "airflow.providers.http"
      "airflow.providers.http.get_provider_info"
    ];
  };

  ibm_mq = {
    version = "0.1.0";
    deps = [ "asgiref" ];

    imports = [
      "airflow.providers.ibm.mq"
      "airflow.providers.ibm.mq.get_provider_info"
    ];
  };

  imap = {
    version = "3.11.3";
    deps = [ ];

    imports = [
      "airflow.providers.imap"
      "airflow.providers.imap.get_provider_info"
    ];
  };

  influxdb = {
    version = "2.11.0";

    deps = [
      "influxdb-client"
      "influxdb3-python"
      "requests"
    ];

    imports = [
      "airflow.providers.influxdb"
      "airflow.providers.influxdb.get_provider_info"
    ];
  };

  informatica = {
    version = "0.2.0";
    deps = [ "sqlglot" ];

    imports = [
      "airflow.providers.informatica"
      "airflow.providers.informatica.get_provider_info"
    ];
  };

  jdbc = {
    version = "5.5.0";

    deps = [
      "jaydebeapi"
      "jpype1"
    ];

    imports = [
      "airflow.providers.jdbc"
      "airflow.providers.jdbc.get_provider_info"
    ];
  };

  jenkins = {
    version = "4.2.6";
    deps = [ "python-jenkins" ];

    imports = [
      "airflow.providers.jenkins"
      "airflow.providers.jenkins.get_provider_info"
    ];
  };

  keycloak = {
    version = "0.8.0";
    deps = [ "python-keycloak" ];

    imports = [
      "airflow.providers.keycloak"
      "airflow.providers.keycloak.get_provider_info"
    ];
  };

  microsoft_azure = {
    version = "13.5.0";

    deps = [
      "adlfs"
      "azure-batch"
      "azure-cosmos"
      "azure-datalake-store"
      "azure-identity"
      "azure-keyvault-secrets"
      "azure-kusto-data"
      "azure-mgmt-compute"
      "azure-mgmt-containerinstance"
      "azure-mgmt-containerregistry"
      "azure-mgmt-cosmosdb"
      "azure-mgmt-datafactory"
      "azure-mgmt-datalake-store"
      "azure-mgmt-resource"
      "azure-mgmt-storage"
      "azure-servicebus"
      "azure-storage-blob"
      "azure-storage-file-datalake"
      "azure-storage-file-share"
      "azure-synapse-artifacts"
      "azure-synapse-spark"
      "microsoft-kiota-abstractions"
      "microsoft-kiota-authentication-azure"
      "microsoft-kiota-http"
      "microsoft-kiota-serialization-json"
      "microsoft-kiota-serialization-text"
      "msal-extensions"
      "msgraph-core"
    ];

    imports = [
      "airflow.providers.microsoft.azure"
      "airflow.providers.microsoft.azure.get_provider_info"
    ];
  };

  microsoft_mssql = {
    version = "4.7.0";

    deps = [
      "methodtools"
      "pymssql"
    ];

    imports = [
      "airflow.providers.microsoft.mssql"
      "airflow.providers.microsoft.mssql.get_provider_info"
    ];
  };

  microsoft_psrp = {
    version = "3.2.6";
    deps = [ "pypsrp" ];

    imports = [
      "airflow.providers.microsoft.psrp"
      "airflow.providers.microsoft.psrp.get_provider_info"
    ];
  };

  microsoft_winrm = {
    version = "3.14.3";
    deps = [ "pywinrm" ];

    imports = [
      "airflow.providers.microsoft.winrm"
      "airflow.providers.microsoft.winrm.get_provider_info"
    ];
  };

  mongo = {
    version = "5.4.0";

    deps = [
      "dnspython"
      "pymongo"
    ];

    imports = [
      "airflow.providers.mongo"
      "airflow.providers.mongo.get_provider_info"
    ];
  };

  mysql = {
    version = "6.6.1";

    deps = [
      "aiomysql"
      "mysql-connector-python"
      "mysqlclient"
      "pymysql"
    ];

    imports = [
      "airflow.providers.mysql"
      "airflow.providers.mysql.get_provider_info"
    ];
  };

  neo4j = {
    version = "3.11.6";
    deps = [ "neo4j" ];

    imports = [
      "airflow.providers.neo4j"
      "airflow.providers.neo4j.get_provider_info"
    ];
  };

  odbc = {
    version = "4.12.3";
    deps = [ "pyodbc" ];

    imports = [
      "airflow.providers.odbc"
      "airflow.providers.odbc.get_provider_info"
    ];
  };

  openai = {
    version = "1.7.5";
    deps = [ "openai" ];

    imports = [
      "airflow.providers.openai"
      "airflow.providers.openai.get_provider_info"
    ];
  };

  openfaas = {
    version = "3.9.5";
    deps = [ ];

    imports = [
      "airflow.providers.openfaas"
      "airflow.providers.openfaas.get_provider_info"
    ];
  };

  openlineage = {
    version = "2.18.1";

    deps = [
      "attrs"
      "sqlalchemy"
    ];

    imports = [
      "airflow.providers.openlineage"
      "airflow.providers.openlineage.get_provider_info"
    ];
  };

  opensearch = {
    version = "1.10.0";
    deps = [ "opensearch-py" ];

    imports = [
      "airflow.providers.opensearch"
      "airflow.providers.opensearch.get_provider_info"
    ];
  };

  opsgenie = {
    version = "5.10.4";
    deps = [ ];

    imports = [
      "airflow.providers.opsgenie"
      "airflow.providers.opsgenie.get_provider_info"
    ];
  };

  oracle = {
    version = "4.6.1";

    deps = [
      "numpy"
      "oracledb"
    ];

    imports = [
      "airflow.providers.oracle"
      "airflow.providers.oracle.get_provider_info"
    ];
  };

  pagerduty = {
    version = "5.2.6";
    deps = [ ];

    imports = [
      "airflow.providers.pagerduty"
      "airflow.providers.pagerduty.get_provider_info"
    ];
  };

  papermill = {
    version = "3.13.1";

    deps = [
      "ipykernel"
      "nbconvert"
      "pandas"
      "papermill"
    ];

    imports = [
      "airflow.providers.papermill"
      "airflow.providers.papermill.get_provider_info"
    ];
  };

  pgvector = {
    version = "1.7.2";
    deps = [ "pgvector" ];

    imports = [
      "airflow.providers.pgvector"
      "airflow.providers.pgvector.get_provider_info"
    ];
  };

  pinecone = {
    version = "2.4.5";
    deps = [ ];

    imports = [
      "airflow.providers.pinecone"
      "airflow.providers.pinecone.get_provider_info"
    ];
  };

  postgres = {
    version = "6.8.0";

    deps = [
      "asyncpg"
      "pandas"
      "polars"
      "psycopg"
      "psycopg2-binary"
      "sqlalchemy"
    ];

    imports = [
      "airflow.providers.postgres"
      "airflow.providers.postgres.get_provider_info"
    ];
  };

  presto = {
    version = "5.12.0";

    deps = [
      "pandas"
      "presto-python-client"
      "psycopg2-binary"
      "sqlalchemy"
    ];

    imports = [
      "airflow.providers.presto"
      "airflow.providers.presto.get_provider_info"
    ];
  };

  qdrant = {
    version = "1.5.6";
    deps = [ "qdrant-client" ];

    imports = [
      "airflow.providers.qdrant"
      "airflow.providers.qdrant.get_provider_info"
    ];
  };

  redis = {
    version = "4.5.0";
    deps = [ "redis" ];

    imports = [
      "airflow.providers.redis"
      "airflow.providers.redis.get_provider_info"
    ];
  };

  salesforce = {
    version = "5.14.1";

    deps = [
      "pandas"
      "simple-salesforce"
    ];

    imports = [
      "airflow.providers.salesforce"
      "airflow.providers.salesforce.get_provider_info"
    ];
  };

  samba = {
    version = "4.12.6";
    deps = [ "smbprotocol" ];

    imports = [
      "airflow.providers.samba"
      "airflow.providers.samba.get_provider_info"
    ];
  };

  segment = {
    version = "3.9.5";
    deps = [ ];

    imports = [
      "airflow.providers.segment"
      "airflow.providers.segment.get_provider_info"
    ];
  };

  sendgrid = {
    version = "4.2.4";
    deps = [ "sendgrid" ];

    imports = [
      "airflow.providers.sendgrid"
      "airflow.providers.sendgrid.get_provider_info"
    ];
  };

  sftp = {
    version = "5.8.2";

    deps = [
      "aiofiles"
      "asyncssh"
      "paramiko"
      "pysftp"
      "sshfs"
    ];

    imports = [
      "airflow.providers.sftp"
      "airflow.providers.sftp.get_provider_info"
    ];
  };

  singularity = {
    version = "3.9.4";
    deps = [ "spython" ];

    imports = [
      "airflow.providers.singularity"
      "airflow.providers.singularity.get_provider_info"
    ];
  };

  slack = {
    version = "9.10.2";

    deps = [
      "aiohttp"
      "asgiref"
      "slack-sdk"
    ];

    imports = [
      "airflow.providers.slack"
      "airflow.providers.slack.get_provider_info"
    ];
  };

  smtp = {
    version = "3.0.1";
    deps = [ "aiosmtplib" ];

    imports = [
      "airflow.providers.smtp"
      "airflow.providers.smtp.get_provider_info"
    ];
  };

  snowflake = {
    version = "6.14.0";

    deps = [
      "pandas"
      "pyarrow"
      "setuptools"
      "snowflake-connector-python"
      "snowflake-sqlalchemy"
    ];

    imports = [
      "airflow.providers.snowflake"
      "airflow.providers.snowflake.get_provider_info"
    ];
  };

  sqlite = {
    version = "4.3.3";
    deps = [ ];

    imports = [
      "airflow.providers.sqlite"
      "airflow.providers.sqlite.get_provider_info"
    ];
  };

  ssh = {
    version = "5.0.3";

    deps = [
      "asyncssh"
      "paramiko"
    ];

    imports = [
      "airflow.providers.ssh"
      "airflow.providers.ssh.get_provider_info"
    ];
  };

  standard = {
    version = "1.15.0";
    deps = [ ];

    imports = [
      "airflow.providers.standard"
      "airflow.providers.standard.get_provider_info"
    ];
  };

  tableau = {
    version = "5.5.0";
    deps = [ "tableauserverclient" ];

    imports = [
      "airflow.providers.tableau"
      "airflow.providers.tableau.get_provider_info"
    ];
  };

  telegram = {
    version = "4.9.5";
    deps = [ "python-telegram-bot" ];

    imports = [
      "airflow.providers.telegram"
      "airflow.providers.telegram.get_provider_info"
    ];
  };

  teradata = {
    version = "3.6.0";
    deps = [ "sqlalchemy" ];

    imports = [
      "airflow.providers.teradata"
      "airflow.providers.teradata.get_provider_info"
    ];
  };

  trino = {
    version = "6.6.0";
    deps = [ "pandas" ];

    imports = [
      "airflow.providers.trino"
      "airflow.providers.trino.get_provider_info"
    ];
  };

  vertica = {
    version = "4.4.0";

    deps = [
      "sqlalchemy"
      "vertica-python"
    ];

    imports = [
      "airflow.providers.vertica"
      "airflow.providers.vertica.get_provider_info"
    ];
  };

  vespa = {
    version = "0.1.1";
    deps = [ ];

    imports = [
      "airflow.providers.vespa"
      "airflow.providers.vespa.get_provider_info"
    ];
  };

  weaviate = {
    version = "3.3.5";

    deps = [
      "httpx"
      "pandas"
      "weaviate-client"
    ];

    imports = [
      "airflow.providers.weaviate"
      "airflow.providers.weaviate.get_provider_info"
    ];
  };

  yandex = {
    version = "4.5.0";
    deps = [ "grpcio" ];

    imports = [
      "airflow.providers.yandex"
      "airflow.providers.yandex.get_provider_info"
    ];
  };

  ydb = {
    version = "2.5.3";
    deps = [ ];

    imports = [
      "airflow.providers.ydb"
      "airflow.providers.ydb.get_provider_info"
    ];
  };

  zendesk = {
    version = "4.12.0";
    deps = [ ];

    imports = [
      "airflow.providers.zendesk"
      "airflow.providers.zendesk.get_provider_info"
    ];
  };

}
