# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  fetchgit,
  fetchzip,
  linkFarm,
}:

linkFarm "zig-packages" [
  {
    name = "AFLplusplus-4.21.0-aA1y4UtxAABpnSIF7ARSYDMRyqNcI-2Rwa5UeSsuw70v";

    path = fetchgit {
      hash = "sha256-AlkULC20/RTGMTPk2xWcdXCQlWn3sY3VrD0NRRoTZqY=";
      rev = "a52f1376e2d49720c39e4abf4aa4944afbf82191";
      url = "https://github.com/allyourcodebase/AFLplusplus";
    };
  }
  {
    name = "N-V-__8AAKE4uAAJZgEcPdaXnWqoj-IwYf3G2h9YSm-x92gg";

    path = fetchzip {
      hash = "sha256-DKwPRxSO+JEJYWLldnfrAYqzwqukNzrbo4R5FzJqzzg=";
      url = "https://github.com/AFLplusplus/AFLplusplus/archive/v4.21c.tar.gz";
    };
  }
  {
    name = "afl_kit-0.1.0-NdJ3cvscAACLEvjZTB017IAks_Uq5ux1qpA-klDe384Y";

    path = fetchgit {
      hash = "sha256-J0xbmsokjlhOav9KLlH2y4qiSgBit4nS+x6Q10L2OSA=";
      rev = "8ef04d1db48650345dca68da1e1b8f2615125c40";
      url = "https://github.com/kristoff-it/zig-afl-kit";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJtTTAADUOhGKM0sxzG4eMkNQxRvx9e5dfHVyaeA3";

    path = fetchgit {
      hash = "sha256-Pdn/nUclhHBB1COTzNNR5ysE13h6uLOFJjuFrasv/2I=";
      rev = "ab5cf5feb936fa3b72c95d3ad0c0c67791937ba1";
      url = "https://github.com/ziglibs/known-folders";
    };
  }
  {
    name = "lsp_kit-0.1.0-bi_PLzAyCgClDh8_M0U9Q50ysdsQBuRuBTZfwg6rZPd6";

    path = fetchgit {
      hash = "sha256-1HW8kWhfpbBihzE6PiXXxGN03qIW20KCsBoyfSSWgNU=";
      rev = "fe98e895ca3bd1b39965ab30f0f252f7b7e83ee6";
      url = "https://github.com/zigtools/lsp-kit";
    };
  }
  {
    name = "scripty-0.1.0-LKK5O7v4AADWWXuFcTJky_5sY12tmw3kRi3k2wkpfxAX";

    path = fetchgit {
      hash = "sha256-r3L4iLpJUH93S0tH6d6w3pHcLzAaKZPSFBAgpnTMdeI=";
      rev = "50dbab8945440089384f26ec165d870c29555247";
      url = "https://github.com/kristoff-it/scripty";
    };
  }
  {
    name = "tracy-0.0.0-4Xw-1pwwAABTfMgoDP1unCbZDZhJEfict7XCBGF6IdIn";

    path = fetchgit {
      hash = "sha256-BKo1bhua/u+f5Z//ailur5aSHZWp3GiC0iwmVLrGZkE=";
      rev = "67d2d89e351048c76fc6d161e0ac09d8a831dc60";
      url = "https://github.com/kristoff-it/tracy";
    };
  }
]
