{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.usbguard;

  # valid policy options
  policy = (
    lib.types.enum [
      "allow"
      "block"
      "reject"
      "keep"
      "apply-policy"
    ]
  );

  # decide what file to use for rules
  ruleFile = if cfg.rules != null then pkgs.writeText "usbguard-rules" cfg.rules else cfg.ruleFile;

  daemonConf = ''
    # generated by nixos/modules/services/security/usbguard.nix
    RuleFile=${ruleFile}
    ImplicitPolicyTarget=${cfg.implicitPolicyTarget}
    PresentDevicePolicy=${cfg.presentDevicePolicy}
    PresentControllerPolicy=${cfg.presentControllerPolicy}
    InsertedDevicePolicy=${cfg.insertedDevicePolicy}
    RestoreControllerDeviceState=${lib.boolToString cfg.restoreControllerDeviceState}
    # this does not seem useful for endusers to change
    DeviceManagerBackend=uevent
    IPCAllowedUsers=${lib.concatStringsSep " " cfg.IPCAllowedUsers}
    IPCAllowedGroups=${lib.concatStringsSep " " cfg.IPCAllowedGroups}
    IPCAccessControlFiles=/var/lib/usbguard/IPCAccessControl.d/
    DeviceRulesWithPort=${lib.boolToString cfg.deviceRulesWithPort}
    # HACK: that way audit logs still land in the journal
    AuditFilePath=/dev/null
  '';

  daemonConfFile = pkgs.writeText "usbguard-daemon-conf" daemonConf;

in
{

  imports = [
    (lib.mkRemovedOptionModule [ "services" "usbguard" "IPCAccessControlFiles" ]
      "The usbguard module now hardcodes IPCAccessControlFiles to /var/lib/usbguard/IPCAccessControl.d."
    )
    (lib.mkRemovedOptionModule [
      "services"
      "usbguard"
      "auditFilePath"
    ] "Removed usbguard module audit log files. Audit logs can be found in the systemd journal.")
    (lib.mkRenamedOptionModule
      [ "services" "usbguard" "implictPolicyTarget" ]
      [ "services" "usbguard" "implicitPolicyTarget" ]
    )
  ];

  ###### interface
  options = {
    services.usbguard = {
      enable = lib.mkEnableOption "USBGuard daemon";
      package = lib.mkPackageOption pkgs "usbguard" { };

      IPCAllowedGroups = lib.mkOption {
        default = [ ];

        description = ''
          A list of groupnames that the daemon will accept IPC connections
          from.
        '';

        example = [ "wheel" ];
        type = lib.types.listOf lib.types.str;
      };

      IPCAllowedUsers = lib.mkOption {
        default = [ "root" ];

        description = ''
          A list of usernames that the daemon will accept IPC connections from.
        '';

        example = [
          "root"
          "yourusername"
        ];

        type = lib.types.listOf lib.types.str;
      };

      dbus.enable = lib.mkEnableOption "USBGuard dbus daemon";

      deviceRulesWithPort = lib.mkOption {
        default = false;

        description = ''
          Generate device specific rules including the "via-port" attribute.
        '';

        type = lib.types.bool;
      };

      implicitPolicyTarget = lib.mkOption {
        default = "block";

        description = ''
          How to treat USB devices that don't match any rule in the policy.
          Target should be one of allow, block or reject (logically remove the
          device node from the system).
        '';

        type = lib.types.enum [
          "allow"
          "block"
          "reject"
        ];
      };

      insertedDevicePolicy = lib.mkOption {
        default = "apply-policy";

        description = ''
          How to treat USB devices that are already connected after the daemon
          starts. One of block, reject, apply-policy.
        '';

        type = lib.types.enum [
          "block"
          "reject"
          "apply-policy"
        ];
      };

      presentControllerPolicy = lib.mkOption {
        default = "keep";

        description = ''
          How to treat USB controller devices that are already connected when
          the daemon starts. One of allow, block, reject, keep or apply-policy.
        '';

        type = policy;
      };

      presentDevicePolicy = lib.mkOption {
        default = "apply-policy";

        description = ''
          How to treat USB devices that are already connected when the daemon
          starts. Policy should be one of allow, block, reject, keep (keep
          whatever state the device is currently in) or apply-policy (evaluate
          the rule set for every present device).
        '';

        type = policy;
      };

      restoreControllerDeviceState = lib.mkOption {
        default = false;

        description = ''
          The  USBGuard  daemon  modifies  some attributes of controller
          devices like the default authorization state of new child device
          instances. Using this setting, you can control whether the daemon
          will try to restore the attribute values to the state before
          modification on shutdown.
        '';

        type = lib.types.bool;
      };

      ruleFile = lib.mkOption {
        default = "/var/lib/usbguard/rules.conf";

        description = ''
          This tells the USBGuard daemon which file to load as policy rule set.

          The file can be changed manually or via the IPC interface assuming it has the right file permissions.

          For more details see {manpage}`usbguard-rules.conf(5)`.
        '';

        example = "/run/secrets/usbguard-rules";
        type = lib.types.nullOr lib.types.path;

      };

      rules = lib.mkOption {
        default = null;

        description = ''
          The USBGuard daemon will load this as the policy rule set.
          As these rules are NixOS managed they are immutable and can't
          be changed by the IPC interface.

          If you do not set this option, the USBGuard daemon will load
          it's policy rule set from the option configured in `services.usbguard.ruleFile`.

          Running `usbguard generate-policy` as root will
          generate a config for your currently plugged in devices.

          For more details see {manpage}`usbguard-rules.conf(5)`.
        '';

        example = ''
          allow with-interface equals { 08:*:* }
        '';

        type = lib.types.nullOr lib.types.lines;
      };
    };
  };

  ###### implementation
  config = lib.mkIf cfg.enable {

    environment.systemPackages = [ cfg.package ];

    security.polkit.extraConfig =
      let
        groupCheck =
          (lib.concatStrings (map (g: "subject.isInGroup(\"${g}\") || ") cfg.IPCAllowedGroups)) + "false";
      in
      lib.optionalString cfg.dbus.enable ''
        polkit.addRule(function(action, subject) {
            if ((action.id == "org.usbguard.Policy1.listRules" ||
                 action.id == "org.usbguard.Policy1.appendRule" ||
                 action.id == "org.usbguard.Policy1.removeRule" ||
                 action.id == "org.usbguard.Devices1.applyDevicePolicy" ||
                 action.id == "org.usbguard.Devices1.listDevices" ||
                 action.id == "org.usbguard1.getParameter" ||
                 action.id == "org.usbguard1.setParameter") &&
                subject.active == true && subject.local == true &&
                (${groupCheck})) {
                    return polkit.Result.YES;
            }
        });
      '';

    systemd.services = {
      usbguard = {
        description = "USBGuard daemon";
        # make sure an empty rule file exists
        preStart = ''[ -f "${ruleFile}" ] || touch ${ruleFile}'';

        serviceConfig = {
          AmbientCapabilities = "";
          CapabilityBoundingSet = "CAP_CHOWN CAP_FOWNER";
          DeviceAllow = "/dev/null rw";
          DevicePolicy = "strict";
          ExecStart = "${cfg.package}/bin/usbguard-daemon -P -k -c ${daemonConfFile}";
          IPAddressDeny = "any";
          LockPersonality = true;
          MemoryDenyWriteExecute = true;
          NoNewPrivileges = true;
          PrivateDevices = true;
          PrivateTmp = true;
          ProtectControlGroups = true;
          ProtectHome = true;
          ProtectKernelModules = true;
          ProtectSystem = true;
          ReadOnlyPaths = "-/";
          ReadWritePaths = "-/dev/shm -/tmp";
          Restart = "on-failure";

          RestrictAddressFamilies = [
            "AF_UNIX"
            "AF_NETLINK"
          ];

          RestrictNamespaces = true;
          RestrictRealtime = true;

          StateDirectory = [
            "usbguard"
            "usbguard/IPCAccessControl.d"
          ];

          SystemCallArchitectures = "native";
          SystemCallFilter = "@system-service";
          Type = "simple";
          UMask = "0077";
        };

        wantedBy = [ "basic.target" ];
        wants = [ "systemd-udevd.service" ];
      };

      usbguard-dbus = lib.mkIf cfg.dbus.enable {
        aliases = [ "dbus-org.usbguard.service" ];
        description = "USBGuard D-Bus Service";
        requires = [ "usbguard.service" ];

        serviceConfig = {
          BusName = "org.usbguard1";
          ExecStart = "${cfg.package}/bin/usbguard-dbus --system";
          Restart = "on-failure";
          Type = "dbus";
        };

        wantedBy = [ "multi-user.target" ];
      };
    };
  };
}
