{
  lib,
  stdenv,
  fetchFromGitHub,
  copyDesktopItems,
  electron,
  makeDesktopItem,
  makeWrapper,
  nix-update-script,
  nodejs,
  yarn-berry_4,
  zip,
  commandLineArgs ? "",
}:

let
  yarn-berry = yarn-berry_4;
in
stdenv.mkDerivation (finalAttrs: {
  pname = "ytmdesktop";
  version = "2.0.11";

  src = fetchFromGitHub {
    owner = "ytmdesktop";
    repo = "ytmdesktop";
    tag = "v${finalAttrs.version}";
    hash = "sha256-3gUEdkTFaO6WT13HyVssVX0qSmluOPm4AAy1dovHw6g=";
    leaveDotGit = true;

    postFetch = ''
      cd $out
      git rev-parse HEAD > .COMMIT
      find -name .git -print0 | xargs -0 rm -rf
    '';
  };

  patches = [
    # instead of running git during the build process
    # use the .COMMIT file generated in the fetcher FOD
    ./git-rev-parse.patch

    # Remove after upstream updates to Yarn 4.14
    # https://github.com/ytmdesktop/ytmdesktop/blob/v2.0.11/package.json#L77
    ./yarn-4.14-support.patch

    # zip extraction fails on newer nodejs versions without this fix
    # generated by running `yarn set resolution yauzl@npm:^2.10.0 npm:^3.3.1`
    ./bump-yauzl.patch
  ];

  postPatch = lib.optionalString stdenv.hostPlatform.isLinux ''
    substituteInPlace viteconfig/main.ts

    # workaround for https://github.com/electron/electron/issues/31121
    substituteInPlace src/main/index.ts \
      --replace-fail "process.resourcesPath" "'$out/share/ytmdesktop/resources'"
  '';

  nativeBuildInputs = [
    copyDesktopItems
    makeWrapper
    nodejs
    yarn-berry
    yarn-berry.yarnBerryConfigHook
    zip
  ];

  # Don't auto-run scripts of dependencies
  # We don't need any native modules, so this is fine
  env.YARN_ENABLE_SCRIPTS = "0";

  buildPhase = ''
    runHook preBuild

    cp -r ${electron.dist} electron-dist
    chmod -R u+w electron-dist

    pushd electron-dist
    zip -0Xqr ../electron.zip .
    popd

    rm -r electron-dist

    # force @electron/packager to use our electron instead of downloading it
    substituteInPlace node_modules/@electron/packager/dist/packager.js \
      --replace-fail 'await this.getElectronZipPath(downloadOpts)' '"electron.zip"'

    # electron-forge's console output is squeezed into one narrow column if unset
    export CI="1";

    yarn run package

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
  ''
  + lib.optionalString stdenv.hostPlatform.isLinux ''

    mkdir -p "$out"/share/ytmdesktop
    cp -r out/*/{locales,resources{,.pak}} "$out"/share/ytmdesktop

    install -Dm644 src/assets/icons/ytmd.png "$out"/share/pixmaps/ytmdesktop.png

    makeWrapper ${lib.getExe electron} "$out"/bin/ytmdesktop \
      --add-flags "$out"/share/ytmdesktop/resources/app.asar \
      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime=true}}" \
      --add-flags ${lib.escapeShellArg commandLineArgs}
  ''
  + lib.optionalString stdenv.hostPlatform.isDarwin ''
    mkdir -p $out/Applications
    cp -r out/*/"YouTube Music Desktop App".app "$out"/Applications

    wrapProgram "$out"/Applications/"YouTube Music Desktop App".app/Contents/MacOS/youtube-music-desktop-app \
      --add-flags ${lib.escapeShellArg commandLineArgs}

    makeWrapper "$out"/Applications/"YouTube Music Desktop App".app/Contents/MacOS/youtube-music-desktop-app "$out"/bin/ytmdesktop
  ''
  + ''
    runHook postInstall
  '';

  desktopItems = [
    (makeDesktopItem {
      categories = [
        "AudioVideo"
        "Audio"
      ];

      desktopName = "YouTube Music Desktop App";
      exec = "ytmdesktop";
      genericName = finalAttrs.meta.description;
      icon = "ytmdesktop";
      mimeTypes = [ "x-scheme-handler/ytmd" ];
      name = "ytmdesktop";
      startupNotify = true;
      startupWMClass = "YouTube Music Desktop App";
    })
  ];

  missingHashes = ./missing-hashes.json;

  yarnOfflineCache = yarn-berry.fetchYarnBerryDeps {
    inherit (finalAttrs) src missingHashes patches;
    hash = "sha256-VpNK+44/FwHxZ+Hyx0QShpZ9fdP06VhhpoXxMFeLUzE=";
  };

  passthru.updateScript = nix-update-script { };

  meta = {
    inherit (electron.meta) platforms;
    description = "Desktop App for YouTube Music";
    homepage = "https://ytmdesktop.app/";
    changelog = "https://github.com/ytmdesktop/ytmdesktop/releases/tag/v${finalAttrs.version}";
    license = lib.licenses.gpl3Only;
    maintainers = [ lib.maintainers.cjshearer ];
    mainProgram = "ytmdesktop";
    downloadPage = "https://github.com/ytmdesktop/ytmdesktop/releases";
  };
})
