# This package defines a `TreeSitterConfig` class autogenerated from the
# tree-sitter `config.schema.json` using `datamodel-codegen`.
{
  lib,
  buildPythonPackage,
  datamodel-code-generator,
  hatchling,
  pkgs, # Need to access `pkgs.tree-sitter`, which is different than `pkgs.python3Packages.tree-sitter`.
  pydantic,
  runCommand,
  symlinkJoin,
  writeTextDir,
}:
buildPythonPackage (finalAttrs: {
  pname = "tree-sitter-config";
  version = "1.0.0";

  src = symlinkJoin {
    name = "tree-sitter-config-source";

    paths = [
      (writeTextDir "pyproject.toml" /* toml */ ''
        [build-system]
        requires = ["hatchling >= 1.26"]
        build-backend = "hatchling.build"

        [project]
        name = "tree_sitter_config"
        version = "${finalAttrs.version}"
      '')
      (runCommand "tree_sitter_config/__init__.py"
        {
          nativeBuildInputs = [
            datamodel-code-generator
          ];
        }
        ''
          mkdir -p $out/tree_sitter_config
          datamodel-codegen \
            --input ${pkgs.tree-sitter}/config.schema.json \
            --input-file-type jsonschema \
            --output-model-type pydantic_v2.BaseModel \
            --class-name TreeSitterConfig \
            > $out/tree_sitter_config/__init__.py
        ''
      )
    ];
  };

  build-system = [ hatchling ];
  dependencies = [ pydantic ] ++ pydantic.optional-dependencies.email;
  pyproject = true;
  pythonImportsCheck = [ "tree_sitter_config" ];

  meta = {
    description = "Python types for tree-sitter.json";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ jfly ];
  };
})
