# Generated by rebar3_nix
let
  fetchOnly = { src, ... }: src;
in
{
  fetchFromGitHub,
  fetchHex,
  fetchgit,
  builder ? fetchOnly,
  overrides ? (x: y: { }),
}:
let
  self = packages // (overrides self packages);
  packages = {
    meck = builder {
      version = "0.8.13";

      src = fetchHex {
        sha256 = "sha256-008BPBVttRrVfMVWiRuXIOahwd9f4uFa+ZnITWzr6xo=";
        pkg = "meck";
        version = "0.8.13";
      };

      beamDeps = [ ];
      name = "meck";
    };
  };
in
self
