{
  config,
  lib,
  pkgs,
  ...
}:
let
  format = pkgs.formats.hcl1 { };
  cfg = config.services.spire.agent;
in
{
  imports = [ ./agent-tpm.nix ];

  options.services.spire.agent = {
    enable = lib.mkEnableOption "SPIRE agent";
    package = lib.mkPackageOption pkgs "spire" { };

    configFile = lib.mkOption {
      default = format.generate "agent.conf" (lib.filterAttrsRecursive (_: v: v != null) cfg.settings);
      defaultText = "Config file generated from services.spire.agent.settings";

      description = ''
        Path to the SPIRE agent configuration file. See [the documentation](https://spiffe.io/docs/latest/deploying/spire_agent/) for more information.
      '';

      type = lib.types.path;
    };

    expandEnv = lib.mkOption {
      default = true;
      description = "Expand environment $VARIABLES in the config file";
      type = lib.types.bool;
    };

    settings = lib.mkOption {
      description = ''
        SPIRE Agent configuration file options. See [the documentation](https://spiffe.io/docs/latest/deploying/spire_agent/) for all available options.
      '';

      type = lib.types.submodule {
        options = {
          agent = {
            data_dir = lib.mkOption {
              default = "$STATE_DIRECTORY";
              description = "A directory the agent can use for its runtime data";
              type = lib.types.str;
            };

            join_token = lib.mkOption {
              default = null;
              description = "An optional token which has been generated by the SPIRE server";
              type = lib.types.nullOr lib.types.str;
            };

            join_token_file = lib.mkOption {
              default = null;
              description = "Path to a file containing an optional join token which has been generated by the SPIRE server";
              type = lib.types.nullOr lib.types.str;
            };

            server_address = lib.mkOption {
              description = "DNS name or IP address of the SPIRE server";
              example = "server.example.com";
              type = lib.types.str;
            };

            server_port = lib.mkOption {
              default = 8081;
              description = "Port number of the SPIRE server";
              type = lib.types.port;
            };

            socket_path = lib.mkOption {
              default = "/run/spire/agent/public/api.sock";
              description = "Location to bind the SPIRE Agent API socket (Unix only)";
              type = lib.types.path;
            };

            trust_domain = lib.mkOption {
              description = "The trust domain that this agent belongs to (should be no more than 255 characters)";
              example = "example.com";
              type = lib.types.str;
            };
          };

          plugins = lib.mkOption {
            description = ''
              Built-in plugin types can be found at [the plugin types documentation](https://spiffe.io/docs/latest/deploying/spire_agent/#plugin-types).
              See [plugin configuration](https://spiffe.io/docs/latest/deploying/spire_agent/#plugin-configuration) for options and how to configure external plugins.
            '';

            example = {
              KeyManager.memory.plugin_data = { };
              NodeAttestor.join_token.plugin_data = { };
              WorkloadAttestor.systemd.plugin_data = { };
              WorkloadAttestor.unix.plugin_data = { };
            };

            type = lib.types.submodule {
              options.NodeAttestor = lib.mkOption {
                default = { };

                description = ''
                  Gathers information used to attest the agent's identity to the server. Generally paired with a server plugin of the same type.
                '';

                type = lib.types.submodule {
                  options.join_token = lib.mkOption {
                    default = null;

                    description = ''
                      The `join_token` is responsible for attesting the agent's identity using a one-time-use pre-shared key.

                      Must be used in conjunction with the server-side `join_token` plugin.
                    '';

                    type = lib.types.nullOr (
                      lib.types.submodule {
                        options.plugin_data = lib.mkOption {
                          default = { };

                          description = ''
                            As a special case for node attestors, the join token itself is configured by a CLI flag (`-joinToken`)
                            or by configuring `join_token` in the agent's main config body.
                          '';

                          type = lib.types.submodule { };
                        };

                        freeformType = format.type;
                      }
                    );
                  };

                  freeformType = format.type;
                };
              };

              freeformType = format.type;
            };
          };
        };

        freeformType = format.type;
      };
    };

  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    systemd.services.spire-agent = {
      description = "SPIRE agent";

      serviceConfig = {
        ExecStart =
          "${lib.getExe' cfg.package "spire-agent"} run "
          + lib.cli.toCommandLineShellGNU { } {
            inherit (cfg) expandEnv;
            config = cfg.configFile;
          };

        Group = "spire-agent";
        Restart = "on-failure";
        RuntimeDirectory = "spire/agent/public";
        StateDirectory = "spire/agent";
        StateDirectoryMode = "0700";
        UMask = "0027";
        # TODO: Switch to DynamicUser once https://github.com/NixOS/nixpkgs/issues/299476 lands
        # Without it, the systemd plugin can not talk to dbus
        # DynamicUser = true;
        User = "spire-agent";
        # TODO: Hardening
      };

      wantedBy = [ "multi-user.target" ];
    };

    users.groups.spire-agent = { };

    # TODO: Switch to DynamicUser once https://github.com/NixOS/nixpkgs/issues/299476 lands
    users.users.spire-agent = {
      group = "spire-agent";
      isSystemUser = true;
    };
  };

  meta.maintainers = [ lib.maintainers.arianvp ];
}
