{
  lib,
  stdenv,
  alsa-utils,
  installShellFiles,
}:

stdenv.mkDerivation (finalAttrs: {
  inherit (alsa-utils) version src;
  pname = "alsa-utils-nhlt";

  outputs = [
    "out"
    "man"
  ];

  postPatch = ''
    # The aconfig.h header is normally generated by the configure script and
    # even though included it is not actually used. Drop in an empty dummy
    # header.
    touch nhlt/aconfig.h
  '';

  nativeBuildInputs = [ installShellFiles ];

  buildPhase = ''
    runHook preBuild

    # Compile flags -g -O2 mirroring configure script.
    $CC -g -O2 -o nhlt-dmic-info nhlt/nhlt-dmic-info.c

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    installBin nhlt-dmic-info
    installManPage nhlt/nhlt-dmic-info.1

    runHook postInstall
  '';

  # The configure script insists on various headers and libraries from
  # alsa-lib and cannot be convinced to forego the respective checks. To
  # avoid dependency on alsa-lib we therefore circumvent the usual build
  # flow and compile the source directly.
  dontConfigure = true;

  meta = {
    description = "Tool to extract microphone array information from ACPI NHLT table";
    homepage = "http://www.alsa-project.org/";
    license = lib.licenses.gpl2Plus;
    maintainers = with lib.maintainers; [ mvs ];
    platforms = lib.platforms.linux;
    mainProgram = "nhlt-dmic-info";
  };
})
