{
  lib,
  stdenv,
  fetchurl,
  autoreconfHook,
  brotli,
  c-aresMinimal,
  # for passthru.tests
  coeurl,
  curlpp,
  fetchpatch,
  gnutls,
  gsasl,
  haskellPackages,
  libidn2,
  libkrb5,
  libpsl,
  libssh2,
  nghttp2,
  nghttp3,
  ngtcp2,
  nixosTests,
  ocamlPackages,
  openldap,
  openssl,
  perl,
  phpExtensions,
  pkg-config,
  pkgsStatic,
  python3,
  rtmpdump,
  rustls-ffi,
  testers,
  tests,
  zlib,
  zstd,
  brotliSupport ? false,
  c-aresSupport ? false,
  gnutlsSupport ? false,
  gsaslSupport ? false,
  gssSupport ?
    with stdenv.hostPlatform;
    (
      # krb5 is broken on cygwin
      !(isWindows || isCygwin)
      &&
        # disable gss because of: undefined reference to `k5_bcmp'
        # a very sad story re static: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=439039
        !isStatic
      &&
        # the "mig" tool does not configure its compiler correctly. This could be
        # fixed in mig, but losing gss support on cross compilation to darwin is
        # not worth the effort.
        !(isDarwin && (stdenv.buildPlatform != stdenv.hostPlatform))
    ),
  http2Support ? true,
  http3Support ? false,
  idnSupport ? false,
  ldapSupport ? false,
  opensslSupport ? zlibSupport,
  pslSupport ? false,
  rtmpSupport ? false,
  rustlsSupport ? false,
  scpSupport ? zlibSupport && !stdenv.hostPlatform.isSunOS && !stdenv.hostPlatform.isCygwin,
  websocketSupport ? false,
  zlibSupport ? true,
  zstdSupport ? false,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

assert
  !(
    (lib.count (x: x) [
      gnutlsSupport
      opensslSupport
      rustlsSupport
    ]) > 1
  );

stdenv.mkDerivation (finalAttrs: {
  pname = "curl";
  version = "8.21.0";

  src = fetchurl {
    hash = "sha256-qhtmpw6s6D3GJFCHRWRsCK5WHeUSq0A63/uTrIf8cuY=";

    urls = [
      "https://curl.haxx.se/download/curl-${finalAttrs.version}.tar.xz"
      "https://github.com/curl/curl/releases/download/curl-${
        builtins.replaceStrings [ "." ] [ "_" ] finalAttrs.version
      }/curl-${finalAttrs.version}.tar.xz"
    ];
  };

  outputs = [
    "bin"
    "dev"
    "out"
    "man"
    "devdoc"
  ];

  # this could be accomplished by updateAutotoolsGnuConfigScriptsHook, but that causes infinite recursion
  # necessary for FreeBSD code path in configure
  postPatch = ''
    substituteInPlace ./config.guess --replace-fail /usr/bin/uname uname
    patchShebangs scripts
  '';

  strictDeps = true;

  nativeBuildInputs = [
    pkg-config
    perl
  ]
  ++ lib.optionals stdenv.hostPlatform.isOpenBSD [ autoreconfHook ];

  # Zlib and OpenSSL must be propagated because `libcurl.la' contains
  # "-lz -lssl", which aren't necessary direct build inputs of
  # applications that use Curl.
  propagatedBuildInputs =
    lib.optional brotliSupport brotli
    ++ lib.optional c-aresSupport c-aresMinimal
    ++ lib.optional gnutlsSupport gnutls
    ++ lib.optional gsaslSupport gsasl
    ++ lib.optional gssSupport libkrb5
    ++ lib.optional http2Support nghttp2
    ++ lib.optionals http3Support [
      nghttp3
      ngtcp2
    ]
    ++ lib.optional idnSupport libidn2
    ++ lib.optional ldapSupport openldap
    ++ lib.optional opensslSupport openssl
    ++ lib.optional pslSupport libpsl
    ++ lib.optional rtmpSupport rtmpdump
    ++ lib.optional scpSupport libssh2
    ++ lib.optional rustlsSupport rustls-ffi
    ++ lib.optional zlibSupport zlib
    ++ lib.optional zstdSupport zstd;

  configureFlags = [
    "--enable-versioned-symbols"
    # Build without manual
    "--disable-manual"
    (lib.enableFeature c-aresSupport "ares")
    (lib.enableFeature ldapSupport "ldap")
    (lib.enableFeature ldapSupport "ldaps")
    (lib.enableFeature websocketSupport "websockets")
    # --with-ca-fallback is only supported for openssl https://github.com/curl/curl/blame/curl-8_16_0/acinclude.m4#L1258
    (lib.withFeature opensslSupport "ca-fallback")
    (lib.withFeature http3Support "nghttp3")
    (lib.withFeature http3Support "ngtcp2")
    (lib.withFeature rtmpSupport "librtmp")
    (lib.withFeature rustlsSupport "rustls")
    (lib.withFeature zstdSupport "zstd")
    (lib.withFeature pslSupport "libpsl")
    (lib.withFeatureAs brotliSupport "brotli" (lib.getDev brotli))
    (lib.withFeatureAs gnutlsSupport "gnutls" (lib.getDev gnutls))
    (lib.withFeatureAs idnSupport "libidn2" (lib.getDev libidn2))
    (lib.withFeatureAs opensslSupport "openssl" (lib.getDev openssl))
    (lib.withFeatureAs scpSupport "libssh2" (lib.getDev libssh2))
  ]
  ++ lib.optional gssSupport "--with-gssapi=${lib.getDev libkrb5}"
  # For the 'urandom', maybe it should be a cross-system option
  ++ lib.optional (stdenv.hostPlatform != stdenv.buildPlatform) "--with-random=/dev/urandom"
  ++ lib.optionals stdenv.hostPlatform.isDarwin [
    # Disable default CA bundle, use NIX_SSL_CERT_FILE or fallback to nss-cacert from the default profile.
    # Without this curl might detect /etc/ssl/cert.pem at build time on macOS, causing curl to ignore NIX_SSL_CERT_FILE.
    "--without-ca-bundle"
    "--without-ca-path"
  ]
  ++ lib.optionals (!gnutlsSupport && !opensslSupport && !rustlsSupport) [
    "--without-ssl"
  ]
  ++ lib.optionals (rustlsSupport && !stdenv.hostPlatform.isDarwin) [
    "--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt"
  ]
  ++ lib.optionals (gnutlsSupport && !stdenv.hostPlatform.isDarwin) [
    "--with-ca-path=/etc/ssl/certs"
  ];

  env = {
    CXX = "${stdenv.cc.targetPrefix}c++";
    CXXCPP = "${stdenv.cc.targetPrefix}c++ -E";
  }
  // lib.optionalAttrs (stdenv.hostPlatform.isDarwin && stdenv.hostPlatform.isStatic) {
    # Not having this causes curl’s `configure` script to fail with static builds on Darwin because
    # some of curl’s propagated inputs need libiconv.
    NIX_LDFLAGS = "-liconv";
  };

  # for the second line see https://curl.haxx.se/mail/tracker-2014-03/0087.html
  preConfigure = ''
    sed -e 's|/usr/bin|/no-such-path|g' -i.bak configure
    rm src/tool_hugehelp.c
  '';

  # takes 14 minutes on a 24 core and because many other packages depend on curl
  # they cannot be run concurrently and are a bottleneck
  # tests are available in passthru.tests.withCheck
  doCheck = false;

  nativeCheckInputs = [
    # See https://github.com/curl/curl/pull/16928
    openssl
  ];

  preCheck = ''
    patchShebangs tests/
  ''
  + lib.optionalString stdenv.hostPlatform.isDarwin ''
    # bad interaction with sandbox if enabled?
    rm tests/data/test1453
    rm tests/data/test1086
  ''
  + lib.optionalString stdenv.hostPlatform.isMusl ''
    # different resolving behaviour?
    rm tests/data/test1592
  '';

  postInstall = ''
    moveToOutput bin/curl-config "$dev"

    # Install completions
    make -C scripts install
  ''
  + lib.optionalString scpSupport ''
    sed '/^dependency_libs/s|${lib.getDev libssh2}|${lib.getLib libssh2}|' -i "$out"/lib/*.la
  ''
  + lib.optionalString gnutlsSupport ''
    ln $out/lib/libcurl${stdenv.hostPlatform.extensions.sharedLibrary} $out/lib/libcurl-gnutls${stdenv.hostPlatform.extensions.sharedLibrary}
    ln $out/lib/libcurl${stdenv.hostPlatform.extensions.sharedLibrary} $out/lib/libcurl-gnutls${stdenv.hostPlatform.extensions.sharedLibrary}.4
    ln $out/lib/libcurl${stdenv.hostPlatform.extensions.sharedLibrary} $out/lib/libcurl-gnutls${stdenv.hostPlatform.extensions.sharedLibrary}.4.4.0
  '';

  __darwinAllowLocalNetworking = true;
  __structuredAttrs = true;
  enableParallelBuilding = true;
  separateDebugInfo = stdenv.hostPlatform.isLinux;

  passthru =
    let
      useThisCurl = attr: attr.override { curl = finalAttrs.finalPackage; };
    in
    {
      inherit opensslSupport openssl;

      tests = {
        coeurl = useThisCurl coeurl;
        curlpp = useThisCurl curlpp;

        fetchpatch = tests.fetchpatch.simple.override {
          fetchpatch = (fetchpatch.override { fetchurl = useThisCurl fetchurl; }) // {
            version = 1;
          };
        };

        haskell-curl = useThisCurl haskellPackages.curl;
        # error: attribute 'override' missing
        # Additional checking with support http3 protocol.
        # nginx-http3 = useThisCurl nixosTests.nginx-http3;
        nginx-http3 = nixosTests.nginx-http3;
        ocaml-curly = useThisCurl ocamlPackages.curly;
        php-curl = useThisCurl phpExtensions.curl;
        pkg-config = testers.testMetaPkgConfig finalAttrs.finalPackage;
        pycurl = useThisCurl python3.pkgs.pycurl;
        static = pkgsStatic.curl;

        withCheck = finalAttrs.finalPackage.overrideAttrs (_: {
          doCheck = true;
        });
      };
    };

  meta = {
    description = "Command line tool for transferring files with URL syntax";
    homepage = "https://curl.se/";
    changelog = "https://curl.se/ch/${finalAttrs.version}.html";
    license = lib.licenses.curl;

    maintainers = with lib.maintainers; [
      Scrumplex
    ];

    platforms = lib.platforms.all;
    mainProgram = "curl";
    # Fails to link against static gss
    broken = stdenv.hostPlatform.isStatic && gssSupport;
    donationPage = "https://curl.se/donation.html";
    identifiers.cpeParts = lib.meta.cpeFullVersionWithVendor "haxx" finalAttrs.version;
    pkgConfigModules = [ "libcurl" ];
    teams = [ lib.teams.security-review ];
  };
})
