{
  lib,
  buildPythonPackage,
  fetchPypi,
  hypothesis,
  pdm-backend,
  pytest,
  tqdm,
}:

buildPythonPackage rec {
  pname = "partial-json-parser";
  version = "0.2.1.1.post7";

  src = fetchPypi {
    inherit version;
    hash = "sha256-hlkOG6a8tnOaLfwX0jI/Aoy1iE9MbOI9s3aZkTLJqSI=";
    pname = "partial_json_parser";
  };

  doCheck = true;
  build-system = [ pdm-backend ];
  dependencies = [ ];

  dev-dependencies = [
    hypothesis
    tqdm
    pytest
  ];

  pyproject = true;
  pythonImportsCheck = [ "partial_json_parser" ];

  meta = {
    description = "Parse partial JSON generated by LLM";
    homepage = "https://github.com/promplate/partial-json-parser";
    license = lib.licenses.mit;
    maintainers = [ ];
  };
}
