{
  lib,
  stdenv,
  fetchFromGitHub,
  addBinToPathHook,
  procps,
  python3Packages,
  versionCheckHook,
}:

python3Packages.buildPythonApplication (finalAttrs: {
  pname = "multiqc";
  version = "1.30";

  # Multiqc cannot remove temporary directories in some case.
  # Default is 10 retries, lower it to 2
  postPatch = ''
    substituteInPlace multiqc/utils/util_functions.py \
      --replace-fail \
        "max_retries: int = 10," \
        "max_retries: int = 2,"
    substituteInPlace pyproject.toml \
      --replace 'polars-lts-cpu' 'polars'
  '';

  # Some tests run subprocess.run() with "ps"
  nativeCheckInputs =
    with python3Packages;
    [
      pytest-cov-stub
      pytest-xdist
      pytestCheckHook
      syrupy
      pygithub
      versionCheckHook
    ]
    ++ [
      procps
      addBinToPathHook
    ];

  # Some tests run subprocess.run() with "multiqc"
  preCheck = ''
    chmod -R u+w ../test-data
    ln -s ../test-data .
  '';

  build-system = with python3Packages; [
    setuptools
  ];

  dependencies = with python3Packages; [
    boto3
    click
    humanize
    importlib-metadata
    jinja2
    kaleido
    markdown
    natsort
    numpy
    packaging
    requests
    polars
    pillow
    plotly
    pyarrow
    pyyaml
    rich
    rich-click
    coloredlogs
    spectra
    pydantic
    tiktoken
    typeguard
    tqdm
    python-dotenv
    jsonschema
  ];

  disabledTests =
    # On darwin, kaleido fails to starts
    lib.optionals (stdenv.hostPlatform.isDarwin) [
      "test_flat_plot"
    ];

  pyproject = true;
  sourceRoot = "multiqc";

  # Two data sources. One for the code, another for the test data
  srcs = [
    (fetchFromGitHub {
      hash = "sha256-TR5YFoWj97gpsykIzc1lqtYVePsVLRIT0HXw+VPJ7o4=";
      name = "multiqc";
      owner = "MultiQC";
      repo = "MultiQC";
      tag = "v${finalAttrs.version}";
    })
    (fetchFromGitHub {
      hash = "sha256-/MiNnPayG6wpF2S09ENYTlEBF7Km4aH1RjdGOfMgZcA=";
      name = "test-data";
      owner = "MultiQC";
      repo = "test-data";
      rev = "cc9f853e7892eb537e91505e0e847ff63669138d";
    })
  ];

  meta = {
    description = "Aggregates bioinformatics results from multiple samples into a unified report";

    longDescription = ''
      MultiQC is a tool to create a single report with interactive plots for multiple bioinformatics analyses across many samples.

      Reports are generated by scanning given directories for recognised log files. These are parsed and a single HTML report is generated summarising the statistics for all logs found. MultiQC reports can describe multiple analysis steps and large numbers of samples within a single plot, and multiple analysis tools making it ideal for routine fast quality control.
    '';

    homepage = "https://multiqc.info";
    changelog = "https://github.com/MultiQC/MultiQC/releases/tag/v${finalAttrs.version}/";
    license = [ lib.licenses.gpl3Plus ];
    maintainers = [ lib.maintainers.apraga ];
    platforms = lib.platforms.unix;
    mainProgram = "multiqc";
  };

})
