{
  config,
  lib,
  pkgs,
  ...
}:
let

  cfgC = config.services.synergy.client;
  cfgS = config.services.synergy.server;

in

{
  ###### interface

  options = {

    services.synergy = {

      # !!! All these option descriptions needs to be cleaned up.

      client = {
        enable = lib.mkEnableOption "the Synergy client (receive keyboard and mouse events from a Synergy server)";

        autoStart = lib.mkOption {
          default = true;
          description = "Whether the Synergy client should be started automatically.";
          type = lib.types.bool;
        };

        screenName = lib.mkOption {
          default = "";

          description = ''
            Use the given name instead of the hostname to identify
            ourselves to the server.
          '';

          type = lib.types.str;
        };

        serverAddress = lib.mkOption {
          description = ''
            The server address is of the form: [hostname][:port].  The
            hostname must be the address or hostname of the server.  The
            port overrides the default port, 24800.
          '';

          type = lib.types.str;
        };
      };

      server = {
        enable = lib.mkEnableOption "the Synergy server (send keyboard and mouse events)";

        address = lib.mkOption {
          default = "";
          description = "Address on which to listen for clients.";
          type = lib.types.str;
        };

        autoStart = lib.mkOption {
          default = true;
          description = "Whether the Synergy server should be started automatically.";
          type = lib.types.bool;
        };

        configFile = lib.mkOption {
          default = "/etc/synergy-server.conf";
          description = "The Synergy server configuration file.";
          type = lib.types.path;
        };

        screenName = lib.mkOption {
          default = "";

          description = ''
            Use the given name instead of the hostname to identify
            this screen in the configuration.
          '';

          type = lib.types.str;
        };

        tls = {
          enable = lib.mkOption {
            default = false;

            description = ''
              Whether TLS encryption should be used.

              Using this requires a TLS certificate that can be
              generated by starting the Synergy GUI once and entering
              a valid product key.
            '';

            type = lib.types.bool;
          };

          cert = lib.mkOption {
            default = null;
            description = "The TLS certificate to use for encryption.";
            example = "~/.synergy/SSL/Synergy.pem";
            type = lib.types.nullOr lib.types.str;
          };
        };
      };
    };

  };

  ###### implementation

  config = lib.mkMerge [
    (lib.mkIf cfgC.enable {
      systemd.user.services.synergy-client = {
        after = [
          "network.target"
          "graphical-session.target"
        ];

        description = "Synergy client";
        path = [ pkgs.synergy ];

        serviceConfig.ExecStart = "${pkgs.synergy}/bin/synergyc -f ${
          lib.optionalString (cfgC.screenName != "") "-n ${cfgC.screenName}"
        } ${cfgC.serverAddress}";

        serviceConfig.Restart = "on-failure";
        wantedBy = lib.optional cfgC.autoStart "graphical-session.target";
      };
    })
    (lib.mkIf cfgS.enable {
      systemd.user.services.synergy-server = {
        after = [
          "network.target"
          "graphical-session.target"
        ];

        description = "Synergy server";
        path = [ pkgs.synergy ];

        serviceConfig.ExecStart = "${pkgs.synergy}/bin/synergys -c ${cfgS.configFile} -f${
          lib.optionalString (cfgS.address != "") " -a ${cfgS.address}"
        }${
          lib.optionalString (cfgS.screenName != "") " -n ${cfgS.screenName}"
        }${lib.optionalString cfgS.tls.enable " --enable-crypto"}${
          lib.optionalString (cfgS.tls.cert != null) " --tls-cert ${cfgS.tls.cert}"
        }";

        serviceConfig.Restart = "on-failure";
        wantedBy = lib.optional cfgS.autoStart "graphical-session.target";
      };
    })
  ];

}

/*
  SYNERGY SERVER example configuration file
  section: screens
    laptop:
    dm:
    win:
  end
  section: aliases
      laptop:
        192.168.5.5
      dm:
        192.168.5.78
      win:
        192.168.5.54
  end
  section: links
     laptop:
         left = dm
     dm:
         right = laptop
         left = win
    win:
        right = dm
  end
*/
