# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ fetchzip, linkFarm }:

linkFarm "zig-packages" [
  {
    name = "zig_dis_x86_64-0.0.1-bnhOUXf6AwDf1MpMgHZImLwqhFbUp2Fl_MoxhtPEeo4N";

    path = fetchzip {
      hash = "sha256-JsuAWOZnwtBikyHQma4SFfkDP7kPDE1qxPnQpCzx8m0=";
      url = "https://github.com/kubkon/zig-dis-x86_64/archive/48c399d7f9d879f46a69d4a06af3fa0699286ba5.tar.gz";
    };
  }
  {
    name = "zig_yaml-0.1.0-C1161miEAgBCwL3YAEQZwV_4GyaaT2Xqj9nKB6hNe_TL";

    path = fetchzip {
      hash = "sha256-HfxM1MgdlnnD13LG9AWULu/jy5zMRa3nkLUqkKj1RC4=";
      url = "https://github.com/kubkon/zig-yaml/archive/refs/tags/0.1.1.tar.gz";
    };
  }
]
