{
  lib,
  stdenv,
  fetchurl,
  attr,
  gettext,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

stdenv.mkDerivation (finalAttrs: {
  pname = "acl";
  version = "2.3.2";

  src = fetchurl {
    url = "mirror://savannah/acl/acl-${finalAttrs.version}.tar.gz";
    hash = "sha256-XyvbrWKXB6p9hcYj+ZSqih0t7FWnPeUgW6wL9gWKL3w=";
  };

  outputs = [
    "bin"
    "dev"
    "out"
    "man"
    "doc"
  ];

  postPatch = ''
    patchShebangs .
  '';

  strictDeps = true;
  nativeBuildInputs = [ gettext ];
  buildInputs = [ attr ];
  __structuredAttrs = true;
  enableParallelBuilding = true;

  meta = {
    inherit (attr.meta) platforms badPlatforms;
    description = "Library and tools for manipulating access control lists";
    homepage = "https://savannah.nongnu.org/projects/acl";
    license = lib.licenses.gpl2Plus;
    identifiers.cpeParts = lib.meta.cpeFullVersionWithVendor "acl_project" finalAttrs.version;
    teams = [ lib.teams.security-review ];
  };
})
