{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

{
  imports = [
    ../image/file-options.nix
  ];

  options.proxmoxLXC = {
    enable = mkOption {
      default = true;
      description = "Whether to enable the Proxmox VE LXC module.";
      type = types.bool;
    };

    manageHostName = mkOption {
      default = false;

      description = ''
        Whether to manage hostname through nix options
        When false, the hostname is picked up from /etc/hostname
        populated by proxmox.
      '';

      type = types.bool;
    };

    manageNetwork = mkOption {
      default = false;

      description = ''
        Whether to manage network interfaces through nix options
        When false, systemd-networkd is enabled to accept network
        configuration from proxmox.
      '';

      type = types.bool;
    };

    privileged = mkOption {
      default = false;

      description = ''
        Whether to enable privileged mounts
      '';

      type = types.bool;
    };
  };

  config =
    let
      cfg = config.proxmoxLXC;
    in
    mkIf cfg.enable {
      boot = {
        isContainer = true;
        loader.initScript.enable = true;
      };

      console.enable = true;
      image.extension = "tar.xz";
      image.filePath = "tarball/${config.image.fileName}";

      networking = mkIf (!cfg.manageNetwork) {
        # pick up hostname from /etc/hostname generated by proxmox
        hostName = mkIf (!cfg.manageHostName) (mkForce "");
        useDHCP = false;
        useHostResolvConf = false;
        useNetworkd = true;
      };

      # unprivileged LXCs can't set net.ipv4.ping_group_range
      security.wrappers.ping = mkIf (!cfg.privileged) {
        capabilities = "cap_net_raw+p";
        group = "root";
        owner = "root";
        source = "${pkgs.iputils.out}/bin/ping";
      };

      services.openssh = {
        enable = mkDefault true;
        startWhenNeeded = mkDefault true;
      };

      system.build.image = config.system.build.tarball;

      system.build.tarball = pkgs.callPackage ../../lib/make-system-tarball.nix {
        contents = [
          {
            source = config.system.build.toplevel + "/init";
            target = "/sbin/init";
          }
        ];

        extraCommands = "mkdir -p root etc/systemd/network";
        fileName = config.image.baseName;

        storeContents = [
          {
            object = config.system.build.toplevel;
            symlink = "none";
          }
        ];
      };

      system.nixos.tags = [
        "proxmox"
        "lxc"
      ];

      systemd = {
        mounts = mkIf (!cfg.privileged) [
          {
            enable = false;
            where = "/sys/kernel/debug";
          }
        ];

        services."autovt@".enable = lib.mkForce true;

        # By default only starts getty on tty0 but first on LXC is tty1
        services."autovt@".unitConfig.ConditionPathExists = [
          ""
          "/dev/%I"
        ];

        # These are disabled by `console.enable` but console via tty is the default in Proxmox
        services."getty@tty1".enable = lib.mkForce true;

        services.register-nix-paths = {
          after = [ "local-fs.target" ];

          before = [
            "sysinit.target"
            "shutdown.target"
            "nix-daemon.socket"
            "nix-daemon.service"
          ];

          conflicts = [ "shutdown.target" ];
          description = "Register Nix Store Paths";
          restartIfChanged = false;

          script = ''
            ${lib.getExe' config.nix.package.out "nix-store"} --load-db < /nix-path-registration
            rm /nix-path-registration

            # nixos-rebuild also requires a "system" profile
            ${lib.getExe' config.nix.package.out "nix-env"} -p /nix/var/nix/profiles/system --set /run/current-system
          '';

          serviceConfig = {
            RemainAfterExit = true;
            Type = "oneshot";
          };

          unitConfig = {
            ConditionPathExists = "/nix-path-registration";
            DefaultDependencies = false;
          };

          wantedBy = [ "sysinit.target" ];
        };
      };

    };
}
