{
  lib,
  stdenv,
  fetchurl,
  autoconf,
  autoconf269,
  automake,
  autoreconfHook,
  docbook_xml_dtd_412,
  docbook_xsl,
  fetchpatch,
  libtool,
  xmlto,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "opensp";
  version = "1.5.2";

  src = fetchurl {
    url = "mirror://sourceforge/openjade/OpenSP-${finalAttrs.version}.tar.gz";
    sha256 = "1khpasr6l0a8nfz6kcf3s81vgdab8fm2dj291n5r2s53k228kx2p";
  };

  patches = [
    (fetchpatch {
      sha256 = "04q14s8qsad0bkjmj067dn831i0r6v7742rafdlnbfm5y249m2q6";
      url = "https://gitweb.gentoo.org/repo/gentoo.git/plain/app-text/opensp/files/opensp-1.5.2-c11-using.patch?id=688d9675782dfc162d4e6cff04c668f7516118d0";
    })
    (fetchpatch {
      hash = "sha256-6pNsVh3BErAN4lyykhFJqCydplh4cVvxgwc5MuWFd+A=";
      name = "opensp-1.5.2-gcc15-musl.patch";
      url = "https://gitweb.gentoo.org/repo/gentoo.git/plain/app-text/opensp/files/opensp-1.5.2-gcc15-musl.patch?id=7143f4a01836f8991d6c90b61fa919e88bf9a0fd";
    })
    # Clang 16 defaults to C++17, which does not allow `register` as a storage class specifier.
    ./fix-register-storage-class.patch
  ];

  postPatch = ''
    sed -i s,/usr/share/sgml/docbook/xml-dtd-4.1.2/,${docbook_xml_dtd_412}/xml/dtd/docbook/, \
      docsrc/*.xml
  '';

  strictDeps = true;

  nativeBuildInputs = [
    xmlto
    docbook_xml_dtd_412
    docbook_xsl
  ]
  # Clang 16 fails to build due to inappropriate definitions in the `config.h` generated by the
  # existing configure scripts. Regenerate them to make sure they detect its features correctly.
  # autoconf269: as autoconf 2.73 is trying to force C23 (-std=gnu23) which will fail, we use 2.69.
  ++ lib.optionals stdenv.cc.isClang [
    autoconf269
    autoreconfHook
  ]
  ++ lib.optionals stdenv.hostPlatform.isCygwin [
    autoconf
    automake
    libtool
  ];

  env = lib.optionalAttrs stdenv.cc.isGNU {
    NIX_CFLAGS_COMPILE = "-fpermissive";
  };

  preConfigure = lib.optionalString stdenv.hostPlatform.isCygwin ''
    autoreconf -fi
  '';

  doCheck = false; # fails

  postFixup = ''
    # Remove random ids in the release notes
    sed -i -e 's/href="#idm.*"//g' $out/share/doc/OpenSP/releasenotes.html
    sed -i -e 's/name="idm.*"//g' $out/share/doc/OpenSP/releasenotes.html
  '';

  setupHook = ./setup-hook.sh;

  meta = {
    description = "Suite of SGML/XML processing tools";
    homepage = "https://openjade.sourceforge.net/";
    license = lib.licenses.mit;
    maintainers = [ ];
    platforms = lib.platforms.unix;
  };
})
