# Generated by ./update.sh - do not update manually!
# Last updated: 2026-04-01
{
  version = "4.1.1.4";

  aarch64-linux = {
    hash = "sha256-UKo7s1WyX6vJaobXZ8r7tuu6jFNtvi4+BWGSkPmTeBs=";
    url = "https://pro-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.wechat/com.tencent.wechat_4.1.1.4_arm64.deb";
  };

  loongarch64-linux = {
    hash = "sha256-kG1BwPD4yu+ZGi8me/l5ePUbw9SxX4jJ3Zy11MCMiSs=";
    url = "https://pro-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.wechat/com.tencent.wechat_4.1.1.4_loongarch64.deb";
  };

  x86_64-linux = {
    hash = "sha256-kizJow0voh21LSq6HIuSsI/oijDRT98c8Fu1gg+N/tc=";
    url = "https://pro-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.wechat/com.tencent.wechat_4.1.1.4_amd64.deb";
  };
}
